// Code generated by protoc-gen-go. DO NOT EDIT.
// source: company/v1/company.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompanyEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CompanyEntity) Reset()         { *m = CompanyEntity{} }
func (m *CompanyEntity) String() string { return proto.CompactTextString(m) }
func (*CompanyEntity) ProtoMessage()    {}
func (*CompanyEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{0}
}

func (m *CompanyEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyEntity.Unmarshal(m, b)
}
func (m *CompanyEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyEntity.Marshal(b, m, deterministic)
}
func (m *CompanyEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyEntity.Merge(m, src)
}
func (m *CompanyEntity) XXX_Size() int {
	return xxx_messageInfo_CompanyEntity.Size(m)
}
func (m *CompanyEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyEntity.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyEntity proto.InternalMessageInfo

func (m *CompanyEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CompanyEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompanyEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CompanyEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CompanyEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CompanyEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CompanyEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CompanyEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CompanyEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *CompanyEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CompanyEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CompanyEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CompanyEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CompanyEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateCompanyReq struct {
	Data                 *CompanyEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCompanyReq) Reset()         { *m = CreateCompanyReq{} }
func (m *CreateCompanyReq) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyReq) ProtoMessage()    {}
func (*CreateCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{1}
}

func (m *CreateCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyReq.Unmarshal(m, b)
}
func (m *CreateCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyReq.Marshal(b, m, deterministic)
}
func (m *CreateCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyReq.Merge(m, src)
}
func (m *CreateCompanyReq) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyReq.Size(m)
}
func (m *CreateCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyReq proto.InternalMessageInfo

func (m *CreateCompanyReq) GetData() *CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateCompanyRes struct {
	Success              bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CompanyEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCompanyRes) Reset()         { *m = CreateCompanyRes{} }
func (m *CreateCompanyRes) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRes) ProtoMessage()    {}
func (*CreateCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{2}
}

func (m *CreateCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRes.Unmarshal(m, b)
}
func (m *CreateCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRes.Marshal(b, m, deterministic)
}
func (m *CreateCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRes.Merge(m, src)
}
func (m *CreateCompanyRes) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRes.Size(m)
}
func (m *CreateCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRes proto.InternalMessageInfo

func (m *CreateCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCompanyRes) GetData() *CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCompanyReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyReq) Reset()         { *m = GetCompanyReq{} }
func (m *GetCompanyReq) String() string { return proto.CompactTextString(m) }
func (*GetCompanyReq) ProtoMessage()    {}
func (*GetCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{3}
}

func (m *GetCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyReq.Unmarshal(m, b)
}
func (m *GetCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyReq.Marshal(b, m, deterministic)
}
func (m *GetCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyReq.Merge(m, src)
}
func (m *GetCompanyReq) XXX_Size() int {
	return xxx_messageInfo_GetCompanyReq.Size(m)
}
func (m *GetCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyReq proto.InternalMessageInfo

func (m *GetCompanyReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCompanyRes struct {
	Success              bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CompanyEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCompanyRes) Reset()         { *m = GetCompanyRes{} }
func (m *GetCompanyRes) String() string { return proto.CompactTextString(m) }
func (*GetCompanyRes) ProtoMessage()    {}
func (*GetCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{4}
}

func (m *GetCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyRes.Unmarshal(m, b)
}
func (m *GetCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyRes.Marshal(b, m, deterministic)
}
func (m *GetCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyRes.Merge(m, src)
}
func (m *GetCompanyRes) XXX_Size() int {
	return xxx_messageInfo_GetCompanyRes.Size(m)
}
func (m *GetCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyRes proto.InternalMessageInfo

func (m *GetCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCompanyRes) GetData() *CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListCompanyReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCompanyReq) Reset()         { *m = ListCompanyReq{} }
func (m *ListCompanyReq) String() string { return proto.CompactTextString(m) }
func (*ListCompanyReq) ProtoMessage()    {}
func (*ListCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{5}
}

func (m *ListCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCompanyReq.Unmarshal(m, b)
}
func (m *ListCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCompanyReq.Marshal(b, m, deterministic)
}
func (m *ListCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCompanyReq.Merge(m, src)
}
func (m *ListCompanyReq) XXX_Size() int {
	return xxx_messageInfo_ListCompanyReq.Size(m)
}
func (m *ListCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCompanyReq proto.InternalMessageInfo

func (m *ListCompanyReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCompanyReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListCompanyReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListCompanyRes struct {
	Success              bool             `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*CompanyEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64            `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCompanyRes) Reset()         { *m = ListCompanyRes{} }
func (m *ListCompanyRes) String() string { return proto.CompactTextString(m) }
func (*ListCompanyRes) ProtoMessage()    {}
func (*ListCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{6}
}

func (m *ListCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCompanyRes.Unmarshal(m, b)
}
func (m *ListCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCompanyRes.Marshal(b, m, deterministic)
}
func (m *ListCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCompanyRes.Merge(m, src)
}
func (m *ListCompanyRes) XXX_Size() int {
	return xxx_messageInfo_ListCompanyRes.Size(m)
}
func (m *ListCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListCompanyRes proto.InternalMessageInfo

func (m *ListCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListCompanyRes) GetData() []*CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListCompanyRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateCompanyReq struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *CompanyEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateCompanyReq) Reset()         { *m = UpdateCompanyReq{} }
func (m *UpdateCompanyReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyReq) ProtoMessage()    {}
func (*UpdateCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{7}
}

func (m *UpdateCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyReq.Unmarshal(m, b)
}
func (m *UpdateCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyReq.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyReq.Merge(m, src)
}
func (m *UpdateCompanyReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyReq.Size(m)
}
func (m *UpdateCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyReq proto.InternalMessageInfo

func (m *UpdateCompanyReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCompanyReq) GetData() *CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateCompanyRes struct {
	Success              bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CompanyEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateCompanyRes) Reset()         { *m = UpdateCompanyRes{} }
func (m *UpdateCompanyRes) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyRes) ProtoMessage()    {}
func (*UpdateCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{8}
}

func (m *UpdateCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyRes.Unmarshal(m, b)
}
func (m *UpdateCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyRes.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyRes.Merge(m, src)
}
func (m *UpdateCompanyRes) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyRes.Size(m)
}
func (m *UpdateCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyRes proto.InternalMessageInfo

func (m *UpdateCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateCompanyRes) GetData() *CompanyEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteCompanyReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCompanyReq) Reset()         { *m = DeleteCompanyReq{} }
func (m *DeleteCompanyReq) String() string { return proto.CompactTextString(m) }
func (*DeleteCompanyReq) ProtoMessage()    {}
func (*DeleteCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{9}
}

func (m *DeleteCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCompanyReq.Unmarshal(m, b)
}
func (m *DeleteCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCompanyReq.Marshal(b, m, deterministic)
}
func (m *DeleteCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCompanyReq.Merge(m, src)
}
func (m *DeleteCompanyReq) XXX_Size() int {
	return xxx_messageInfo_DeleteCompanyReq.Size(m)
}
func (m *DeleteCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCompanyReq proto.InternalMessageInfo

func (m *DeleteCompanyReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCompanyRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCompanyRes) Reset()         { *m = DeleteCompanyRes{} }
func (m *DeleteCompanyRes) String() string { return proto.CompactTextString(m) }
func (*DeleteCompanyRes) ProtoMessage()    {}
func (*DeleteCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1452d620d4ff559a, []int{10}
}

func (m *DeleteCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCompanyRes.Unmarshal(m, b)
}
func (m *DeleteCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCompanyRes.Marshal(b, m, deterministic)
}
func (m *DeleteCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCompanyRes.Merge(m, src)
}
func (m *DeleteCompanyRes) XXX_Size() int {
	return xxx_messageInfo_DeleteCompanyRes.Size(m)
}
func (m *DeleteCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCompanyRes proto.InternalMessageInfo

func (m *DeleteCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CompanyEntity)(nil), "company.v1.CompanyEntity")
	proto.RegisterMapType((map[string]string)(nil), "company.v1.CompanyEntity.MetadataEntry")
	proto.RegisterType((*CreateCompanyReq)(nil), "company.v1.CreateCompanyReq")
	proto.RegisterType((*CreateCompanyRes)(nil), "company.v1.CreateCompanyRes")
	proto.RegisterType((*GetCompanyReq)(nil), "company.v1.GetCompanyReq")
	proto.RegisterType((*GetCompanyRes)(nil), "company.v1.GetCompanyRes")
	proto.RegisterType((*ListCompanyReq)(nil), "company.v1.ListCompanyReq")
	proto.RegisterType((*ListCompanyRes)(nil), "company.v1.ListCompanyRes")
	proto.RegisterType((*UpdateCompanyReq)(nil), "company.v1.UpdateCompanyReq")
	proto.RegisterType((*UpdateCompanyRes)(nil), "company.v1.UpdateCompanyRes")
	proto.RegisterType((*DeleteCompanyReq)(nil), "company.v1.DeleteCompanyReq")
	proto.RegisterType((*DeleteCompanyRes)(nil), "company.v1.DeleteCompanyRes")
}

func init() {
	proto.RegisterFile("company/v1/company.proto", fileDescriptor_1452d620d4ff559a)
}

var fileDescriptor_1452d620d4ff559a = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x96, 0xe3, 0xa4, 0x4d, 0x4f, 0x6e, 0x72, 0x73, 0x47, 0x55, 0xef, 0xd4, 0xea, 0x55, 0x2d,
	0x6f, 0xae, 0x55, 0x29, 0xb1, 0x5a, 0x10, 0x82, 0xb2, 0x4a, 0xd3, 0xc2, 0x06, 0x16, 0xb8, 0x65,
	0xc3, 0x02, 0x98, 0xc4, 0x43, 0x3a, 0xc2, 0x7f, 0x78, 0xc6, 0x91, 0x22, 0xc4, 0x86, 0x1d, 0x6b,
	0x78, 0x0b, 0x1e, 0x87, 0x57, 0xe0, 0x41, 0xd0, 0x8c, 0xed, 0x24, 0x76, 0x9b, 0xb4, 0x02, 0xa9,
	0xbb, 0x73, 0xe6, 0x9c, 0xf3, 0x9d, 0xdf, 0x2f, 0x0e, 0xe0, 0x71, 0x14, 0xc4, 0x24, 0x9c, 0x39,
	0xd3, 0x43, 0x27, 0x17, 0xfb, 0x71, 0x12, 0x89, 0x08, 0x41, 0xa1, 0x4e, 0x0f, 0x8d, 0xfd, 0x49,
	0x14, 0x4d, 0x7c, 0xea, 0x28, 0xcb, 0x28, 0x7d, 0xe7, 0x08, 0x16, 0x50, 0x2e, 0x48, 0x10, 0x67,
	0xce, 0xc6, 0x5e, 0xee, 0x40, 0x62, 0xe6, 0x90, 0x30, 0x8c, 0x04, 0x11, 0x2c, 0x0a, 0x79, 0x66,
	0xb5, 0xbe, 0xd7, 0xa1, 0x3d, 0xcc, 0xd0, 0xce, 0x42, 0xc1, 0xc4, 0x0c, 0x75, 0xa0, 0xc6, 0x3c,
	0xac, 0x99, 0x9a, 0xbd, 0xe5, 0xd6, 0x98, 0x87, 0x10, 0xd4, 0x43, 0x12, 0x50, 0x5c, 0x53, 0x2f,
	0x4a, 0x46, 0x26, 0xb4, 0x3c, 0xca, 0xc7, 0x09, 0x8b, 0x25, 0x16, 0xd6, 0x95, 0x69, 0xf9, 0x09,
	0xed, 0xc0, 0x06, 0x17, 0x44, 0xa4, 0x1c, 0xd7, 0x4d, 0xcd, 0x6e, 0xba, 0xb9, 0x86, 0xba, 0xa0,
	0x93, 0x09, 0xc5, 0x0d, 0x53, 0xb3, 0x1b, 0xae, 0x14, 0xd1, 0x36, 0x34, 0x44, 0x24, 0x88, 0x8f,
	0x37, 0x4c, 0xcd, 0xd6, 0xdd, 0x4c, 0x91, 0xaf, 0x71, 0xc2, 0xc6, 0x14, 0x6f, 0x9a, 0x9a, 0xad,
	0xb9, 0x99, 0x22, 0x6b, 0x11, 0x64, 0xc2, 0x71, 0xd3, 0xd4, 0x65, 0x2d, 0x52, 0x46, 0x18, 0x36,
	0xc3, 0x34, 0x18, 0xd1, 0x84, 0xe3, 0x2d, 0x53, 0xb7, 0x1b, 0x6e, 0xa1, 0xa2, 0x21, 0x34, 0x03,
	0x2a, 0x88, 0x47, 0x04, 0xc1, 0x60, 0xea, 0x76, 0xeb, 0xe8, 0xff, 0xfe, 0x62, 0x72, 0xfd, 0x52,
	0xdb, 0xfd, 0xe7, 0xb9, 0xe7, 0x59, 0x28, 0x92, 0x99, 0x3b, 0x0f, 0x44, 0xff, 0x01, 0x8c, 0x13,
	0x4a, 0x04, 0xf5, 0xde, 0x8c, 0x66, 0xb8, 0xa5, 0x3a, 0xdd, 0xca, 0x5f, 0x4e, 0x66, 0xe8, 0xd1,
	0xc2, 0x4c, 0x04, 0xfe, 0xcb, 0xd4, 0xec, 0xd6, 0x91, 0xd1, 0xcf, 0x46, 0xde, 0x2f, 0x76, 0xd2,
	0xbf, 0x28, 0x76, 0x32, 0x0f, 0x1d, 0x08, 0x19, 0x9a, 0xc6, 0x5e, 0x11, 0xda, 0xbe, 0x39, 0x34,
	0xf7, 0xce, 0x42, 0x3d, 0xea, 0xd3, 0x3c, 0xb4, 0x73, 0x73, 0x68, 0xee, 0x3d, 0x10, 0xc6, 0x63,
	0x68, 0x97, 0x5a, 0x95, 0x1b, 0x79, 0x4f, 0x67, 0xf9, 0xc2, 0xa5, 0x28, 0x67, 0x3f, 0x25, 0x7e,
	0x5a, 0xac, 0x3c, 0x53, 0x8e, 0x6b, 0x0f, 0x35, 0x6b, 0x00, 0xdd, 0xa1, 0xaa, 0x3f, 0x9f, 0x9d,
	0x4b, 0x3f, 0xa0, 0x1e, 0xd4, 0xd5, 0x84, 0x35, 0x55, 0xc5, 0xee, 0xca, 0x09, 0xbb, 0xca, 0xcd,
	0x4a, 0xaf, 0x40, 0xa8, 0x15, 0xf2, 0x74, 0x3c, 0xa6, 0x9c, 0x2b, 0x94, 0xa6, 0x5b, 0xa8, 0xd2,
	0x12, 0x50, 0xce, 0xe5, 0xc9, 0x64, 0xc5, 0x14, 0xea, 0x3c, 0xad, 0x7e, 0xbb, 0xb4, 0xfb, 0xd0,
	0x7e, 0x4a, 0xc5, 0x52, 0xd9, 0x95, 0x33, 0xb7, 0x92, 0xb2, 0xc3, 0x9d, 0x14, 0xe5, 0x42, 0xe7,
	0x19, 0xe3, 0xcb, 0x55, 0x21, 0xa8, 0xc7, 0x12, 0x57, 0x53, 0xfc, 0x50, 0xb2, 0x5c, 0x87, 0xcf,
	0x02, 0x26, 0x54, 0xb2, 0x86, 0x9b, 0x29, 0x8a, 0x60, 0x94, 0x24, 0xe3, 0xcb, 0x9c, 0x7d, 0xb9,
	0x66, 0x7d, 0xd1, 0x2a, 0xa0, 0x7f, 0xda, 0x89, 0x7e, 0x8b, 0x4e, 0x16, 0x24, 0xae, 0x2f, 0x91,
	0xd8, 0x7a, 0x01, 0xdd, 0x97, 0xea, 0x66, 0x57, 0xcf, 0x7d, 0x9e, 0xa8, 0x76, 0xeb, 0xf3, 0xa9,
	0x40, 0xde, 0xc9, 0xa6, 0x2c, 0xe8, 0x9e, 0x2a, 0x0a, 0xad, 0xb9, 0xa0, 0x27, 0x57, 0x7c, 0x7e,
	0xab, 0xb4, 0xa3, 0x6f, 0x75, 0xe8, 0xe4, 0x10, 0xe7, 0x34, 0x99, 0xca, 0xdf, 0xbd, 0x09, 0xb4,
	0x4b, 0xa4, 0x41, 0x7b, 0xa5, 0x82, 0x2b, 0x94, 0x34, 0xd6, 0x59, 0xb9, 0x65, 0x7c, 0xfe, 0xf1,
	0xf3, 0x6b, 0x6d, 0xdb, 0xfa, 0x5b, 0x7d, 0x12, 0x16, 0x1f, 0x97, 0x63, 0xed, 0x00, 0xbd, 0x05,
	0x58, 0xb0, 0x00, 0x95, 0xc6, 0x52, 0xa2, 0x8f, 0xb1, 0xd2, 0xc4, 0xad, 0x3d, 0x85, 0xbf, 0x83,
	0xb6, 0x2b, 0xf8, 0xce, 0x47, 0xe6, 0x7d, 0x42, 0xaf, 0xa1, 0xb5, 0x74, 0x9e, 0xc8, 0x58, 0xc6,
	0x29, 0x93, 0xc1, 0x58, 0x6d, 0xe3, 0xd6, 0xbf, 0x2a, 0xc9, 0x3f, 0xa8, 0xda, 0x04, 0xf2, 0xa1,
	0x5d, 0x3a, 0x90, 0xf2, 0xa8, 0xaa, 0xe7, 0x68, 0xac, 0xb3, 0x72, 0x6b, 0x5f, 0x65, 0xd9, 0x35,
	0xae, 0x6d, 0x45, 0xce, 0x8b, 0x41, 0xbb, 0xb4, 0xf3, 0x72, 0xb6, 0xea, 0xc9, 0x18, 0xeb, 0xac,
	0xf3, 0xc1, 0x1d, 0x5c, 0x9b, 0xed, 0xe4, 0xc1, 0xab, 0xfb, 0x13, 0x26, 0x2e, 0xd3, 0x91, 0xc4,
	0x70, 0xce, 0x4f, 0x07, 0x17, 0x83, 0xde, 0x30, 0xf2, 0xa3, 0x60, 0xc4, 0x88, 0xc3, 0x2f, 0x49,
	0x42, 0xbd, 0xde, 0x24, 0xea, 0xa9, 0x5f, 0x7f, 0x67, 0xf1, 0xd7, 0x61, 0xb4, 0xa1, 0x5e, 0xee,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x85, 0x6e, 0xa4, 0x4f, 0x08, 0x00, 0x00,
}
