syntax = "proto3";

package realtime.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/SDATA-Colombia/shared-go-proto/realtime/v1";

// -------------------------------------------------------------------
// Realtime Entity message
// -------------------------------------------------------------------

message RealtimeEntity {
  string id = 1;
  string name = 2;
  string description = 3;
  bool status = 4;
  int32 age = 5;
  int64 total = 6;
  double price = 7;
  repeated string tags = 8;
  repeated int32 numbers = 9;
  map<string, string> metadata = 10;

  string created_by = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  google.protobuf.Timestamp deleted_at = 14;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreateRealtime
// -------------------------------------------------------------------

message CreateRealtimeReq {
  RealtimeEntity data = 1;
}

message CreateRealtimeRes {
  bool success = 1;
  string message = 2;
  RealtimeEntity data = 3;
}

// -------------------------------------------------------------------
// GetRealtime
// -------------------------------------------------------------------

message GetRealtimeReq {
  string id = 1;
}

message GetRealtimeRes {
  bool success = 1;
  string message = 2;
  RealtimeEntity data = 3;
}

// -------------------------------------------------------------------
// ListRealtime
// -------------------------------------------------------------------

message ListRealtimeReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListRealtimeRes {
  bool success = 1;
  string message = 2;
  repeated RealtimeEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdateRealtime
// -------------------------------------------------------------------

message UpdateRealtimeReq {
  string id = 1;
  RealtimeEntity data = 2;
}

message UpdateRealtimeRes {
  bool success = 1;
  string message = 2;
  RealtimeEntity data = 3;
}

// -------------------------------------------------------------------
// DeleteRealtime
// -------------------------------------------------------------------

message DeleteRealtimeReq {
  string id = 1;
}

message DeleteRealtimeRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service RealtimeService {

  rpc CreateRealtime(CreateRealtimeReq) returns (CreateRealtimeRes) {
    option (google.api.http) = {
      post: "/api/v1/realtime"
      body: "*"
    };
  }

  rpc GetRealtime(GetRealtimeReq) returns (GetRealtimeRes) {
    option (google.api.http) = {
      get: "/api/v1/realtime/{id}"
    };
  }

  rpc ListRealtime(ListRealtimeReq) returns (ListRealtimeRes) {
    option (google.api.http) = {
      get: "/api/v1/realtime"
    };
  }

  rpc UpdateRealtime(UpdateRealtimeReq) returns (UpdateRealtimeRes) {
    option (google.api.http) = {
      put: "/api/v1/realtime/{id}"
      body: "*"
    };
  }

  rpc DeleteRealtime(DeleteRealtimeReq) returns (DeleteRealtimeRes) {
    option (google.api.http) = {
      delete: "/api/v1/realtime/{id}"
    };
  }

}
