// Code generated by protoc-gen-go. DO NOT EDIT.
// source: realtime/v1/realtime.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RealtimeEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RealtimeEntity) Reset()         { *m = RealtimeEntity{} }
func (m *RealtimeEntity) String() string { return proto.CompactTextString(m) }
func (*RealtimeEntity) ProtoMessage()    {}
func (*RealtimeEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{0}
}

func (m *RealtimeEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealtimeEntity.Unmarshal(m, b)
}
func (m *RealtimeEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealtimeEntity.Marshal(b, m, deterministic)
}
func (m *RealtimeEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealtimeEntity.Merge(m, src)
}
func (m *RealtimeEntity) XXX_Size() int {
	return xxx_messageInfo_RealtimeEntity.Size(m)
}
func (m *RealtimeEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RealtimeEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RealtimeEntity proto.InternalMessageInfo

func (m *RealtimeEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RealtimeEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RealtimeEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RealtimeEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *RealtimeEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RealtimeEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RealtimeEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RealtimeEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RealtimeEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *RealtimeEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RealtimeEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *RealtimeEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RealtimeEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RealtimeEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateRealtimeReq struct {
	Data                 *RealtimeEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateRealtimeReq) Reset()         { *m = CreateRealtimeReq{} }
func (m *CreateRealtimeReq) String() string { return proto.CompactTextString(m) }
func (*CreateRealtimeReq) ProtoMessage()    {}
func (*CreateRealtimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{1}
}

func (m *CreateRealtimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRealtimeReq.Unmarshal(m, b)
}
func (m *CreateRealtimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRealtimeReq.Marshal(b, m, deterministic)
}
func (m *CreateRealtimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRealtimeReq.Merge(m, src)
}
func (m *CreateRealtimeReq) XXX_Size() int {
	return xxx_messageInfo_CreateRealtimeReq.Size(m)
}
func (m *CreateRealtimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRealtimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRealtimeReq proto.InternalMessageInfo

func (m *CreateRealtimeReq) GetData() *RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRealtimeRes struct {
	Success              bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RealtimeEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateRealtimeRes) Reset()         { *m = CreateRealtimeRes{} }
func (m *CreateRealtimeRes) String() string { return proto.CompactTextString(m) }
func (*CreateRealtimeRes) ProtoMessage()    {}
func (*CreateRealtimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{2}
}

func (m *CreateRealtimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRealtimeRes.Unmarshal(m, b)
}
func (m *CreateRealtimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRealtimeRes.Marshal(b, m, deterministic)
}
func (m *CreateRealtimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRealtimeRes.Merge(m, src)
}
func (m *CreateRealtimeRes) XXX_Size() int {
	return xxx_messageInfo_CreateRealtimeRes.Size(m)
}
func (m *CreateRealtimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRealtimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRealtimeRes proto.InternalMessageInfo

func (m *CreateRealtimeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRealtimeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateRealtimeRes) GetData() *RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRealtimeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRealtimeReq) Reset()         { *m = GetRealtimeReq{} }
func (m *GetRealtimeReq) String() string { return proto.CompactTextString(m) }
func (*GetRealtimeReq) ProtoMessage()    {}
func (*GetRealtimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{3}
}

func (m *GetRealtimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRealtimeReq.Unmarshal(m, b)
}
func (m *GetRealtimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRealtimeReq.Marshal(b, m, deterministic)
}
func (m *GetRealtimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRealtimeReq.Merge(m, src)
}
func (m *GetRealtimeReq) XXX_Size() int {
	return xxx_messageInfo_GetRealtimeReq.Size(m)
}
func (m *GetRealtimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRealtimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRealtimeReq proto.InternalMessageInfo

func (m *GetRealtimeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRealtimeRes struct {
	Success              bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RealtimeEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRealtimeRes) Reset()         { *m = GetRealtimeRes{} }
func (m *GetRealtimeRes) String() string { return proto.CompactTextString(m) }
func (*GetRealtimeRes) ProtoMessage()    {}
func (*GetRealtimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{4}
}

func (m *GetRealtimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRealtimeRes.Unmarshal(m, b)
}
func (m *GetRealtimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRealtimeRes.Marshal(b, m, deterministic)
}
func (m *GetRealtimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRealtimeRes.Merge(m, src)
}
func (m *GetRealtimeRes) XXX_Size() int {
	return xxx_messageInfo_GetRealtimeRes.Size(m)
}
func (m *GetRealtimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRealtimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRealtimeRes proto.InternalMessageInfo

func (m *GetRealtimeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetRealtimeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetRealtimeRes) GetData() *RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListRealtimeReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRealtimeReq) Reset()         { *m = ListRealtimeReq{} }
func (m *ListRealtimeReq) String() string { return proto.CompactTextString(m) }
func (*ListRealtimeReq) ProtoMessage()    {}
func (*ListRealtimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{5}
}

func (m *ListRealtimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRealtimeReq.Unmarshal(m, b)
}
func (m *ListRealtimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRealtimeReq.Marshal(b, m, deterministic)
}
func (m *ListRealtimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRealtimeReq.Merge(m, src)
}
func (m *ListRealtimeReq) XXX_Size() int {
	return xxx_messageInfo_ListRealtimeReq.Size(m)
}
func (m *ListRealtimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRealtimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListRealtimeReq proto.InternalMessageInfo

func (m *ListRealtimeReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRealtimeReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRealtimeReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListRealtimeRes struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*RealtimeEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListRealtimeRes) Reset()         { *m = ListRealtimeRes{} }
func (m *ListRealtimeRes) String() string { return proto.CompactTextString(m) }
func (*ListRealtimeRes) ProtoMessage()    {}
func (*ListRealtimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{6}
}

func (m *ListRealtimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRealtimeRes.Unmarshal(m, b)
}
func (m *ListRealtimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRealtimeRes.Marshal(b, m, deterministic)
}
func (m *ListRealtimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRealtimeRes.Merge(m, src)
}
func (m *ListRealtimeRes) XXX_Size() int {
	return xxx_messageInfo_ListRealtimeRes.Size(m)
}
func (m *ListRealtimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRealtimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRealtimeRes proto.InternalMessageInfo

func (m *ListRealtimeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListRealtimeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListRealtimeRes) GetData() []*RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListRealtimeRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateRealtimeReq struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *RealtimeEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateRealtimeReq) Reset()         { *m = UpdateRealtimeReq{} }
func (m *UpdateRealtimeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRealtimeReq) ProtoMessage()    {}
func (*UpdateRealtimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{7}
}

func (m *UpdateRealtimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRealtimeReq.Unmarshal(m, b)
}
func (m *UpdateRealtimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRealtimeReq.Marshal(b, m, deterministic)
}
func (m *UpdateRealtimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRealtimeReq.Merge(m, src)
}
func (m *UpdateRealtimeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRealtimeReq.Size(m)
}
func (m *UpdateRealtimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRealtimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRealtimeReq proto.InternalMessageInfo

func (m *UpdateRealtimeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRealtimeReq) GetData() *RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRealtimeRes struct {
	Success              bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RealtimeEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateRealtimeRes) Reset()         { *m = UpdateRealtimeRes{} }
func (m *UpdateRealtimeRes) String() string { return proto.CompactTextString(m) }
func (*UpdateRealtimeRes) ProtoMessage()    {}
func (*UpdateRealtimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{8}
}

func (m *UpdateRealtimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRealtimeRes.Unmarshal(m, b)
}
func (m *UpdateRealtimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRealtimeRes.Marshal(b, m, deterministic)
}
func (m *UpdateRealtimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRealtimeRes.Merge(m, src)
}
func (m *UpdateRealtimeRes) XXX_Size() int {
	return xxx_messageInfo_UpdateRealtimeRes.Size(m)
}
func (m *UpdateRealtimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRealtimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRealtimeRes proto.InternalMessageInfo

func (m *UpdateRealtimeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateRealtimeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateRealtimeRes) GetData() *RealtimeEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRealtimeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRealtimeReq) Reset()         { *m = DeleteRealtimeReq{} }
func (m *DeleteRealtimeReq) String() string { return proto.CompactTextString(m) }
func (*DeleteRealtimeReq) ProtoMessage()    {}
func (*DeleteRealtimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{9}
}

func (m *DeleteRealtimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRealtimeReq.Unmarshal(m, b)
}
func (m *DeleteRealtimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRealtimeReq.Marshal(b, m, deterministic)
}
func (m *DeleteRealtimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRealtimeReq.Merge(m, src)
}
func (m *DeleteRealtimeReq) XXX_Size() int {
	return xxx_messageInfo_DeleteRealtimeReq.Size(m)
}
func (m *DeleteRealtimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRealtimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRealtimeReq proto.InternalMessageInfo

func (m *DeleteRealtimeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRealtimeRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRealtimeRes) Reset()         { *m = DeleteRealtimeRes{} }
func (m *DeleteRealtimeRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRealtimeRes) ProtoMessage()    {}
func (*DeleteRealtimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb371dcbe1c89bb, []int{10}
}

func (m *DeleteRealtimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRealtimeRes.Unmarshal(m, b)
}
func (m *DeleteRealtimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRealtimeRes.Marshal(b, m, deterministic)
}
func (m *DeleteRealtimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRealtimeRes.Merge(m, src)
}
func (m *DeleteRealtimeRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRealtimeRes.Size(m)
}
func (m *DeleteRealtimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRealtimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRealtimeRes proto.InternalMessageInfo

func (m *DeleteRealtimeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteRealtimeRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RealtimeEntity)(nil), "realtime.v1.RealtimeEntity")
	proto.RegisterMapType((map[string]string)(nil), "realtime.v1.RealtimeEntity.MetadataEntry")
	proto.RegisterType((*CreateRealtimeReq)(nil), "realtime.v1.CreateRealtimeReq")
	proto.RegisterType((*CreateRealtimeRes)(nil), "realtime.v1.CreateRealtimeRes")
	proto.RegisterType((*GetRealtimeReq)(nil), "realtime.v1.GetRealtimeReq")
	proto.RegisterType((*GetRealtimeRes)(nil), "realtime.v1.GetRealtimeRes")
	proto.RegisterType((*ListRealtimeReq)(nil), "realtime.v1.ListRealtimeReq")
	proto.RegisterType((*ListRealtimeRes)(nil), "realtime.v1.ListRealtimeRes")
	proto.RegisterType((*UpdateRealtimeReq)(nil), "realtime.v1.UpdateRealtimeReq")
	proto.RegisterType((*UpdateRealtimeRes)(nil), "realtime.v1.UpdateRealtimeRes")
	proto.RegisterType((*DeleteRealtimeReq)(nil), "realtime.v1.DeleteRealtimeReq")
	proto.RegisterType((*DeleteRealtimeRes)(nil), "realtime.v1.DeleteRealtimeRes")
}

func init() {
	proto.RegisterFile("realtime/v1/realtime.proto", fileDescriptor_7cb371dcbe1c89bb)
}

var fileDescriptor_7cb371dcbe1c89bb = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0x4f, 0xb7, 0xbb, 0xb0, 0xcc, 0x42, 0x81, 0x89, 0xe8, 0xa4, 0x80, 0x36, 0xf5, 0x52, 0x49,
	0x68, 0x03, 0xc6, 0xa8, 0x78, 0x5a, 0xfe, 0x84, 0x8b, 0x5e, 0x0a, 0x5e, 0xbc, 0x98, 0xd9, 0x76,
	0x58, 0x26, 0xf6, 0x9f, 0x9d, 0xe9, 0xc6, 0x8d, 0xf1, 0xe2, 0xd9, 0x9b, 0xdf, 0xc3, 0x8b, 0x1f,
	0xc5, 0xaf, 0xe0, 0x07, 0x31, 0x33, 0x6d, 0x97, 0xb6, 0x4b, 0x0a, 0x6a, 0xc2, 0xed, 0xbd, 0x79,
	0xff, 0x7f, 0xef, 0xfd, 0xb6, 0x0b, 0xf4, 0x94, 0xe0, 0x80, 0xd3, 0x90, 0x38, 0x93, 0x3d, 0xa7,
	0x94, 0xed, 0x24, 0x8d, 0x79, 0x0c, 0x07, 0x33, 0x7d, 0xb2, 0xa7, 0x3f, 0x1a, 0xc7, 0xf1, 0x38,
	0x20, 0x8e, 0x34, 0x8d, 0xb2, 0x0b, 0x47, 0x18, 0x18, 0xc7, 0x61, 0x92, 0x7b, 0xeb, 0x5b, 0x85,
	0x03, 0x4e, 0xa8, 0x83, 0xa3, 0x28, 0xe6, 0x98, 0xd3, 0x38, 0x62, 0xb9, 0xd5, 0xfc, 0xd1, 0x05,
	0x9a, 0x5b, 0xa4, 0x3b, 0x89, 0x38, 0xe5, 0x53, 0xa8, 0x81, 0x0e, 0xf5, 0x91, 0x62, 0x28, 0xd6,
	0x92, 0xdb, 0xa1, 0x3e, 0x84, 0xa0, 0x1b, 0xe1, 0x90, 0xa0, 0x8e, 0x7c, 0x91, 0x32, 0x34, 0xc0,
	0xc0, 0x27, 0xcc, 0x4b, 0x69, 0x22, 0x92, 0x21, 0x55, 0x9a, 0xaa, 0x4f, 0xf0, 0x3e, 0x58, 0x60,
	0x1c, 0xf3, 0x8c, 0xa1, 0xae, 0xa1, 0x58, 0x7d, 0xb7, 0xd0, 0xe0, 0x1a, 0x50, 0xf1, 0x98, 0xa0,
	0x9e, 0xa1, 0x58, 0x3d, 0x57, 0x88, 0xf0, 0x1e, 0xe8, 0xf1, 0x98, 0xe3, 0x00, 0x2d, 0x18, 0x8a,
	0xa5, 0xba, 0xb9, 0x22, 0x5e, 0x93, 0x94, 0x7a, 0x04, 0x2d, 0x1a, 0x8a, 0xa5, 0xb8, 0xb9, 0x22,
	0x7a, 0xe1, 0x78, 0xcc, 0x50, 0xdf, 0x50, 0x45, 0x2f, 0x42, 0x86, 0x08, 0x2c, 0x46, 0x59, 0x38,
	0x22, 0x29, 0x43, 0x4b, 0x86, 0x6a, 0xf5, 0xdc, 0x52, 0x85, 0x27, 0xa0, 0x1f, 0x12, 0x8e, 0x7d,
	0xcc, 0x31, 0x02, 0x86, 0x6a, 0x0d, 0xf6, 0x9f, 0xd8, 0x15, 0xec, 0xec, 0xfa, 0xe0, 0xf6, 0x9b,
	0xc2, 0xf7, 0x24, 0xe2, 0xe9, 0xd4, 0x9d, 0x85, 0xc2, 0x6d, 0x00, 0xbc, 0x94, 0x60, 0x4e, 0xfc,
	0xf7, 0xa3, 0x29, 0x1a, 0xc8, 0x59, 0x97, 0x8a, 0x97, 0xc3, 0x29, 0x7c, 0x79, 0x65, 0xc6, 0x1c,
	0x2d, 0x1b, 0x8a, 0x35, 0xd8, 0xd7, 0xed, 0x1c, 0x75, 0xbb, 0x5c, 0x8b, 0x7d, 0x5e, 0xae, 0x65,
	0x16, 0x3a, 0xe4, 0x22, 0x34, 0x4b, 0xfc, 0x32, 0x74, 0xe5, 0xe6, 0xd0, 0xc2, 0x3b, 0x0f, 0xf5,
	0x49, 0x40, 0x8a, 0x50, 0xed, 0xe6, 0xd0, 0xc2, 0x7b, 0xc8, 0xf5, 0x57, 0x60, 0xa5, 0x36, 0xaa,
	0xd8, 0xc9, 0x07, 0x32, 0x2d, 0x56, 0x2e, 0x44, 0x81, 0xfe, 0x04, 0x07, 0x59, 0xb9, 0xf4, 0x5c,
	0x39, 0xe8, 0xbc, 0x50, 0xcc, 0x63, 0xb0, 0x7e, 0x24, 0xfb, 0x2f, 0xc1, 0x73, 0xc9, 0x47, 0xe8,
	0x80, 0xae, 0x04, 0x59, 0x91, 0x6d, 0x6c, 0xb6, 0x80, 0xec, 0x4a, 0x47, 0xf3, 0xd3, 0x7c, 0x16,
	0xb9, 0x48, 0x96, 0x79, 0x1e, 0x61, 0x4c, 0x26, 0xea, 0xbb, 0xa5, 0x2a, 0x2c, 0x21, 0x61, 0x4c,
	0x1c, 0x4e, 0xde, 0x50, 0xa9, 0xce, 0x2a, 0xab, 0xb7, 0xad, 0x6c, 0x00, 0xed, 0x94, 0xf0, 0x6a,
	0xf3, 0x8d, 0x7b, 0x37, 0xb3, 0x86, 0xc7, 0x1d, 0x35, 0x76, 0x06, 0x56, 0x5f, 0x53, 0x56, 0xeb,
	0x0c, 0x82, 0x6e, 0x22, 0x52, 0x2b, 0x92, 0x2c, 0x52, 0x16, 0x9b, 0x09, 0x68, 0x48, 0xb9, 0xac,
	0xd7, 0x73, 0x73, 0x45, 0xb2, 0x8d, 0xe0, 0xd4, 0xbb, 0x2c, 0xa8, 0x58, 0x68, 0xe6, 0x37, 0xa5,
	0x99, 0xf5, 0x7f, 0xa7, 0x51, 0x6f, 0x35, 0xcd, 0x15, 0xa9, 0xbb, 0x15, 0x52, 0x9b, 0xe7, 0x60,
	0xfd, 0xad, 0xbc, 0xe0, 0x16, 0xfc, 0x67, 0xb5, 0x3a, 0x7f, 0x71, 0x4c, 0xcd, 0xac, 0x77, 0xb4,
	0xb3, 0xc7, 0x60, 0xfd, 0x58, 0xd2, 0xaa, 0xed, 0x9e, 0x4e, 0xe7, 0x9d, 0xfe, 0xa9, 0xbd, 0xfd,
	0x9f, 0x5d, 0xb0, 0x5a, 0xe6, 0x38, 0x23, 0xe9, 0x44, 0xfc, 0x20, 0x86, 0x40, 0xab, 0x13, 0x09,
	0x3e, 0xac, 0xb5, 0x3d, 0xc7, 0x55, 0xbd, 0xdd, 0xce, 0xcc, 0xcd, 0xaf, 0xbf, 0x7e, 0x7f, 0xef,
	0x6c, 0x98, 0x6b, 0xf2, 0x8b, 0x51, 0xf9, 0xfa, 0x1c, 0x28, 0x3b, 0xf0, 0x02, 0x0c, 0x2a, 0xdc,
	0x80, 0x75, 0x88, 0xea, 0xbc, 0xd2, 0x5b, 0x8c, 0xcc, 0xdc, 0x96, 0x55, 0x1e, 0xc0, 0x8d, 0x66,
	0x15, 0xe7, 0x33, 0xf5, 0xbf, 0x40, 0x1f, 0x2c, 0x57, 0xcf, 0x16, 0x6e, 0xd5, 0x72, 0x35, 0x78,
	0xa2, 0xb7, 0x59, 0x99, 0x89, 0x64, 0x29, 0x08, 0xe7, 0x06, 0x82, 0x29, 0xd0, 0xea, 0x87, 0xd3,
	0x00, 0x6f, 0xee, 0x56, 0xf5, 0x76, 0x3b, 0x33, 0x0d, 0x59, 0x4b, 0xd7, 0xaf, 0x1f, 0x4b, 0x20,
	0x18, 0x03, 0xad, 0x7e, 0x0d, 0x8d, 0x9a, 0x73, 0xf7, 0xa4, 0xb7, 0xdb, 0x67, 0x50, 0xee, 0x5c,
	0x5f, 0xf3, 0xf0, 0xf9, 0xbb, 0x67, 0x63, 0xca, 0x2f, 0xb3, 0x91, 0xed, 0xc5, 0xa1, 0x73, 0x76,
	0x3c, 0x3c, 0x1f, 0xee, 0x1e, 0xc5, 0x41, 0x1c, 0x8e, 0x28, 0x76, 0xd8, 0x25, 0x4e, 0x89, 0xbf,
	0x3b, 0x8e, 0x77, 0xe5, 0x27, 0xc3, 0xa9, 0xfc, 0xeb, 0x18, 0x2d, 0xc8, 0xa7, 0xa7, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xc1, 0x99, 0x5a, 0x52, 0x8b, 0x08, 0x00, 0x00,
}
