// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1/auth.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Correo               string                 `protobuf:"bytes,2,opt,name=correo,proto3" json:"correo,omitempty"`
	IdSujeto             string                 `protobuf:"bytes,3,opt,name=id_sujeto,json=idSujeto,proto3" json:"id_sujeto,omitempty"`
	TipoSujeto           string                 `protobuf:"bytes,4,opt,name=tipo_sujeto,json=tipoSujeto,proto3" json:"tipo_sujeto,omitempty"`
	Estado               bool                   `protobuf:"varint,5,opt,name=estado,proto3" json:"estado,omitempty"`
	Bloqueado            bool                   `protobuf:"varint,6,opt,name=bloqueado,proto3" json:"bloqueado,omitempty"`
	LoginAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AuthEntity) Reset()         { *m = AuthEntity{} }
func (m *AuthEntity) String() string { return proto.CompactTextString(m) }
func (*AuthEntity) ProtoMessage()    {}
func (*AuthEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{0}
}

func (m *AuthEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthEntity.Unmarshal(m, b)
}
func (m *AuthEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthEntity.Marshal(b, m, deterministic)
}
func (m *AuthEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthEntity.Merge(m, src)
}
func (m *AuthEntity) XXX_Size() int {
	return xxx_messageInfo_AuthEntity.Size(m)
}
func (m *AuthEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AuthEntity proto.InternalMessageInfo

func (m *AuthEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthEntity) GetCorreo() string {
	if m != nil {
		return m.Correo
	}
	return ""
}

func (m *AuthEntity) GetIdSujeto() string {
	if m != nil {
		return m.IdSujeto
	}
	return ""
}

func (m *AuthEntity) GetTipoSujeto() string {
	if m != nil {
		return m.TipoSujeto
	}
	return ""
}

func (m *AuthEntity) GetEstado() bool {
	if m != nil {
		return m.Estado
	}
	return false
}

func (m *AuthEntity) GetBloqueado() bool {
	if m != nil {
		return m.Bloqueado
	}
	return false
}

func (m *AuthEntity) GetLoginAt() *timestamppb.Timestamp {
	if m != nil {
		return m.LoginAt
	}
	return nil
}

func (m *AuthEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *AuthEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AuthEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateAuthReq struct {
	IdSujeto             string   `protobuf:"bytes,1,opt,name=id_sujeto,json=idSujeto,proto3" json:"id_sujeto,omitempty"`
	TipoSujeto           string   `protobuf:"bytes,2,opt,name=tipo_sujeto,json=tipoSujeto,proto3" json:"tipo_sujeto,omitempty"`
	Correo               string   `protobuf:"bytes,3,opt,name=correo,proto3" json:"correo,omitempty"`
	Contrasena           string   `protobuf:"bytes,4,opt,name=contrasena,proto3" json:"contrasena,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthReq) Reset()         { *m = CreateAuthReq{} }
func (m *CreateAuthReq) String() string { return proto.CompactTextString(m) }
func (*CreateAuthReq) ProtoMessage()    {}
func (*CreateAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{1}
}

func (m *CreateAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthReq.Unmarshal(m, b)
}
func (m *CreateAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthReq.Marshal(b, m, deterministic)
}
func (m *CreateAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthReq.Merge(m, src)
}
func (m *CreateAuthReq) XXX_Size() int {
	return xxx_messageInfo_CreateAuthReq.Size(m)
}
func (m *CreateAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthReq proto.InternalMessageInfo

func (m *CreateAuthReq) GetIdSujeto() string {
	if m != nil {
		return m.IdSujeto
	}
	return ""
}

func (m *CreateAuthReq) GetTipoSujeto() string {
	if m != nil {
		return m.TipoSujeto
	}
	return ""
}

func (m *CreateAuthReq) GetCorreo() string {
	if m != nil {
		return m.Correo
	}
	return ""
}

func (m *CreateAuthReq) GetContrasena() string {
	if m != nil {
		return m.Contrasena
	}
	return ""
}

type CreateAuthRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAuthRes) Reset()         { *m = CreateAuthRes{} }
func (m *CreateAuthRes) String() string { return proto.CompactTextString(m) }
func (*CreateAuthRes) ProtoMessage()    {}
func (*CreateAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{2}
}

func (m *CreateAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthRes.Unmarshal(m, b)
}
func (m *CreateAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthRes.Marshal(b, m, deterministic)
}
func (m *CreateAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthRes.Merge(m, src)
}
func (m *CreateAuthRes) XXX_Size() int {
	return xxx_messageInfo_CreateAuthRes.Size(m)
}
func (m *CreateAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthRes proto.InternalMessageInfo

func (m *CreateAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateAuthRes) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListAuthReq struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAuthReq) Reset()         { *m = ListAuthReq{} }
func (m *ListAuthReq) String() string { return proto.CompactTextString(m) }
func (*ListAuthReq) ProtoMessage()    {}
func (*ListAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{3}
}

func (m *ListAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthReq.Unmarshal(m, b)
}
func (m *ListAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthReq.Marshal(b, m, deterministic)
}
func (m *ListAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthReq.Merge(m, src)
}
func (m *ListAuthReq) XXX_Size() int {
	return xxx_messageInfo_ListAuthReq.Size(m)
}
func (m *ListAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthReq proto.InternalMessageInfo

func (m *ListAuthReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAuthReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAuthReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListAuthRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*AuthEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64         `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAuthRes) Reset()         { *m = ListAuthRes{} }
func (m *ListAuthRes) String() string { return proto.CompactTextString(m) }
func (*ListAuthRes) ProtoMessage()    {}
func (*ListAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{4}
}

func (m *ListAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthRes.Unmarshal(m, b)
}
func (m *ListAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthRes.Marshal(b, m, deterministic)
}
func (m *ListAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthRes.Merge(m, src)
}
func (m *ListAuthRes) XXX_Size() int {
	return xxx_messageInfo_ListAuthRes.Size(m)
}
func (m *ListAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthRes proto.InternalMessageInfo

func (m *ListAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListAuthRes) GetData() []*AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListAuthRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type LoginReq struct {
	Correo               string   `protobuf:"bytes,1,opt,name=correo,proto3" json:"correo,omitempty"`
	Contrasena           string   `protobuf:"bytes,2,opt,name=contrasena,proto3" json:"contrasena,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{5}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCorreo() string {
	if m != nil {
		return m.Correo
	}
	return ""
}

func (m *LoginReq) GetContrasena() string {
	if m != nil {
		return m.Contrasena
	}
	return ""
}

type LoginRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TokenAcceso          string   `protobuf:"bytes,3,opt,name=token_acceso,json=tokenAcceso,proto3" json:"token_acceso,omitempty"`
	RefrescarToken       string   `protobuf:"bytes,4,opt,name=refrescar_token,json=refrescarToken,proto3" json:"refrescar_token,omitempty"`
	TipoToken            string   `protobuf:"bytes,5,opt,name=tipo_token,json=tipoToken,proto3" json:"tipo_token,omitempty"`
	IdSujeto             string   `protobuf:"bytes,6,opt,name=id_sujeto,json=idSujeto,proto3" json:"id_sujeto,omitempty"`
	ExpiraEn             int64    `protobuf:"varint,7,opt,name=expira_en,json=expiraEn,proto3" json:"expira_en,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{6}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginRes) GetTokenAcceso() string {
	if m != nil {
		return m.TokenAcceso
	}
	return ""
}

func (m *LoginRes) GetRefrescarToken() string {
	if m != nil {
		return m.RefrescarToken
	}
	return ""
}

func (m *LoginRes) GetTipoToken() string {
	if m != nil {
		return m.TipoToken
	}
	return ""
}

func (m *LoginRes) GetIdSujeto() string {
	if m != nil {
		return m.IdSujeto
	}
	return ""
}

func (m *LoginRes) GetExpiraEn() int64 {
	if m != nil {
		return m.ExpiraEn
	}
	return 0
}

type ChangePasswordReq struct {
	IdSujeto             string   `protobuf:"bytes,1,opt,name=id_sujeto,json=idSujeto,proto3" json:"id_sujeto,omitempty"`
	ContrasenaActual     string   `protobuf:"bytes,2,opt,name=contrasena_actual,json=contrasenaActual,proto3" json:"contrasena_actual,omitempty"`
	NuevaContrasena      string   `protobuf:"bytes,3,opt,name=nueva_contrasena,json=nuevaContrasena,proto3" json:"nueva_contrasena,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReq) Reset()         { *m = ChangePasswordReq{} }
func (m *ChangePasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReq) ProtoMessage()    {}
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{7}
}

func (m *ChangePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReq.Unmarshal(m, b)
}
func (m *ChangePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReq.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReq.Merge(m, src)
}
func (m *ChangePasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReq.Size(m)
}
func (m *ChangePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReq proto.InternalMessageInfo

func (m *ChangePasswordReq) GetIdSujeto() string {
	if m != nil {
		return m.IdSujeto
	}
	return ""
}

func (m *ChangePasswordReq) GetContrasenaActual() string {
	if m != nil {
		return m.ContrasenaActual
	}
	return ""
}

func (m *ChangePasswordReq) GetNuevaContrasena() string {
	if m != nil {
		return m.NuevaContrasena
	}
	return ""
}

type ChangePasswordRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRes) Reset()         { *m = ChangePasswordRes{} }
func (m *ChangePasswordRes) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRes) ProtoMessage()    {}
func (*ChangePasswordRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{8}
}

func (m *ChangePasswordRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRes.Unmarshal(m, b)
}
func (m *ChangePasswordRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRes.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRes.Merge(m, src)
}
func (m *ChangePasswordRes) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRes.Size(m)
}
func (m *ChangePasswordRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRes.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRes proto.InternalMessageInfo

func (m *ChangePasswordRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangePasswordRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResetPasswordReq struct {
	RestablecerToken     string   `protobuf:"bytes,1,opt,name=restablecer_token,json=restablecerToken,proto3" json:"restablecer_token,omitempty"`
	NuevaContrasena      string   `protobuf:"bytes,2,opt,name=nueva_contrasena,json=nuevaContrasena,proto3" json:"nueva_contrasena,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordReq) Reset()         { *m = ResetPasswordReq{} }
func (m *ResetPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordReq) ProtoMessage()    {}
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{9}
}

func (m *ResetPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordReq.Unmarshal(m, b)
}
func (m *ResetPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordReq.Marshal(b, m, deterministic)
}
func (m *ResetPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordReq.Merge(m, src)
}
func (m *ResetPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordReq.Size(m)
}
func (m *ResetPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordReq proto.InternalMessageInfo

func (m *ResetPasswordReq) GetRestablecerToken() string {
	if m != nil {
		return m.RestablecerToken
	}
	return ""
}

func (m *ResetPasswordReq) GetNuevaContrasena() string {
	if m != nil {
		return m.NuevaContrasena
	}
	return ""
}

type ResetPasswordRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRes) Reset()         { *m = ResetPasswordRes{} }
func (m *ResetPasswordRes) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRes) ProtoMessage()    {}
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{10}
}

func (m *ResetPasswordRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRes.Unmarshal(m, b)
}
func (m *ResetPasswordRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRes.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRes.Merge(m, src)
}
func (m *ResetPasswordRes) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRes.Size(m)
}
func (m *ResetPasswordRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRes.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRes proto.InternalMessageInfo

func (m *ResetPasswordRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResetPasswordRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RefreshTokenReq struct {
	RefrescarToken       string   `protobuf:"bytes,1,opt,name=refrescar_token,json=refrescarToken,proto3" json:"refrescar_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{11}
}

func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(m, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetRefrescarToken() string {
	if m != nil {
		return m.RefrescarToken
	}
	return ""
}

type RefreshTokenRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TokenAcceso          string   `protobuf:"bytes,3,opt,name=token_acceso,json=tokenAcceso,proto3" json:"token_acceso,omitempty"`
	RefrescarToken       string   `protobuf:"bytes,4,opt,name=refrescar_token,json=refrescarToken,proto3" json:"refrescar_token,omitempty"`
	TipoToken            string   `protobuf:"bytes,5,opt,name=tipo_token,json=tipoToken,proto3" json:"tipo_token,omitempty"`
	ExpiraEn             int64    `protobuf:"varint,6,opt,name=expira_en,json=expiraEn,proto3" json:"expira_en,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRes) Reset()         { *m = RefreshTokenRes{} }
func (m *RefreshTokenRes) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRes) ProtoMessage()    {}
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{12}
}

func (m *RefreshTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRes.Unmarshal(m, b)
}
func (m *RefreshTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRes.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRes.Merge(m, src)
}
func (m *RefreshTokenRes) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRes.Size(m)
}
func (m *RefreshTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRes proto.InternalMessageInfo

func (m *RefreshTokenRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefreshTokenRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RefreshTokenRes) GetTokenAcceso() string {
	if m != nil {
		return m.TokenAcceso
	}
	return ""
}

func (m *RefreshTokenRes) GetRefrescarToken() string {
	if m != nil {
		return m.RefrescarToken
	}
	return ""
}

func (m *RefreshTokenRes) GetTipoToken() string {
	if m != nil {
		return m.TipoToken
	}
	return ""
}

func (m *RefreshTokenRes) GetExpiraEn() int64 {
	if m != nil {
		return m.ExpiraEn
	}
	return 0
}

type LogoutReq struct {
	RefrescarToken       string   `protobuf:"bytes,1,opt,name=refrescar_token,json=refrescarToken,proto3" json:"refrescar_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{13}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetRefrescarToken() string {
	if m != nil {
		return m.RefrescarToken
	}
	return ""
}

type LogoutRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRes) Reset()         { *m = LogoutRes{} }
func (m *LogoutRes) String() string { return proto.CompactTextString(m) }
func (*LogoutRes) ProtoMessage()    {}
func (*LogoutRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{14}
}

func (m *LogoutRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRes.Unmarshal(m, b)
}
func (m *LogoutRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRes.Marshal(b, m, deterministic)
}
func (m *LogoutRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRes.Merge(m, src)
}
func (m *LogoutRes) XXX_Size() int {
	return xxx_messageInfo_LogoutRes.Size(m)
}
func (m *LogoutRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRes.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRes proto.InternalMessageInfo

func (m *LogoutRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogoutRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAuthReq struct {
	IdSujeto             string   `protobuf:"bytes,1,opt,name=id_sujeto,json=idSujeto,proto3" json:"id_sujeto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthReq) Reset()         { *m = GetAuthReq{} }
func (m *GetAuthReq) String() string { return proto.CompactTextString(m) }
func (*GetAuthReq) ProtoMessage()    {}
func (*GetAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{15}
}

func (m *GetAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthReq.Unmarshal(m, b)
}
func (m *GetAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthReq.Marshal(b, m, deterministic)
}
func (m *GetAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthReq.Merge(m, src)
}
func (m *GetAuthReq) XXX_Size() int {
	return xxx_messageInfo_GetAuthReq.Size(m)
}
func (m *GetAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthReq proto.InternalMessageInfo

func (m *GetAuthReq) GetIdSujeto() string {
	if m != nil {
		return m.IdSujeto
	}
	return ""
}

type GetAuthRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AuthEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAuthRes) Reset()         { *m = GetAuthRes{} }
func (m *GetAuthRes) String() string { return proto.CompactTextString(m) }
func (*GetAuthRes) ProtoMessage()    {}
func (*GetAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_24d92db81f25f2da, []int{16}
}

func (m *GetAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthRes.Unmarshal(m, b)
}
func (m *GetAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthRes.Marshal(b, m, deterministic)
}
func (m *GetAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthRes.Merge(m, src)
}
func (m *GetAuthRes) XXX_Size() int {
	return xxx_messageInfo_GetAuthRes.Size(m)
}
func (m *GetAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthRes proto.InternalMessageInfo

func (m *GetAuthRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAuthRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAuthRes) GetData() *AuthEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthEntity)(nil), "auth.v1.AuthEntity")
	proto.RegisterType((*CreateAuthReq)(nil), "auth.v1.CreateAuthReq")
	proto.RegisterType((*CreateAuthRes)(nil), "auth.v1.CreateAuthRes")
	proto.RegisterType((*ListAuthReq)(nil), "auth.v1.ListAuthReq")
	proto.RegisterType((*ListAuthRes)(nil), "auth.v1.ListAuthRes")
	proto.RegisterType((*LoginReq)(nil), "auth.v1.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "auth.v1.LoginRes")
	proto.RegisterType((*ChangePasswordReq)(nil), "auth.v1.ChangePasswordReq")
	proto.RegisterType((*ChangePasswordRes)(nil), "auth.v1.ChangePasswordRes")
	proto.RegisterType((*ResetPasswordReq)(nil), "auth.v1.ResetPasswordReq")
	proto.RegisterType((*ResetPasswordRes)(nil), "auth.v1.ResetPasswordRes")
	proto.RegisterType((*RefreshTokenReq)(nil), "auth.v1.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenRes)(nil), "auth.v1.RefreshTokenRes")
	proto.RegisterType((*LogoutReq)(nil), "auth.v1.LogoutReq")
	proto.RegisterType((*LogoutRes)(nil), "auth.v1.LogoutRes")
	proto.RegisterType((*GetAuthReq)(nil), "auth.v1.GetAuthReq")
	proto.RegisterType((*GetAuthRes)(nil), "auth.v1.GetAuthRes")
}

func init() {
	proto.RegisterFile("auth/v1/auth.proto", fileDescriptor_24d92db81f25f2da)
}

var fileDescriptor_24d92db81f25f2da = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcb, 0x6f, 0x1b, 0x45,
	0x18, 0xd7, 0xda, 0xf5, 0xeb, 0x73, 0x9b, 0xc7, 0x10, 0x45, 0xee, 0xa6, 0x6d, 0xd2, 0x01, 0xda,
	0x94, 0x12, 0xaf, 0x92, 0xc0, 0x81, 0x0a, 0x09, 0xb9, 0xa1, 0xf4, 0x12, 0x09, 0xb4, 0x89, 0x38,
	0x70, 0xb1, 0xc6, 0xbb, 0x53, 0x7b, 0xca, 0x7a, 0xc7, 0xdd, 0x99, 0x0d, 0x70, 0x43, 0x48, 0x48,
	0x1c, 0x91, 0xf8, 0xbb, 0xb8, 0xc0, 0x9f, 0x00, 0x7f, 0x08, 0x9a, 0x6f, 0x67, 0xbd, 0x6b, 0x7b,
	0x93, 0x40, 0x10, 0x07, 0x4e, 0xf6, 0xf7, 0xfb, 0xde, 0xcf, 0x1d, 0x20, 0x2c, 0xd5, 0x13, 0xef,
	0xe2, 0xd0, 0x33, 0xbf, 0xfd, 0x59, 0x22, 0xb5, 0x24, 0x2d, 0xfc, 0x7f, 0x71, 0xe8, 0xee, 0x8e,
	0xa5, 0x1c, 0x47, 0xdc, 0x43, 0x78, 0x94, 0xbe, 0xf2, 0xb4, 0x98, 0x72, 0xa5, 0xd9, 0x74, 0x96,
	0x49, 0xba, 0xf7, 0xac, 0x00, 0x9b, 0x09, 0x8f, 0xc5, 0xb1, 0xd4, 0x4c, 0x0b, 0x19, 0xab, 0x8c,
	0x4b, 0x7f, 0xae, 0x03, 0x0c, 0x52, 0x3d, 0x79, 0x11, 0x6b, 0xa1, 0xbf, 0x23, 0x6b, 0x50, 0x13,
	0x61, 0xcf, 0xd9, 0x73, 0xf6, 0x3b, 0x7e, 0x4d, 0x84, 0x64, 0x1b, 0x9a, 0x81, 0x4c, 0x12, 0x2e,
	0x7b, 0x35, 0xc4, 0x2c, 0x45, 0x76, 0xa0, 0x23, 0xc2, 0xa1, 0x4a, 0x5f, 0x73, 0x2d, 0x7b, 0x75,
	0x64, 0xb5, 0x45, 0x78, 0x86, 0x34, 0xd9, 0x85, 0xae, 0x16, 0x33, 0x99, 0xb3, 0x6f, 0x21, 0x1b,
	0x0c, 0x64, 0x05, 0xb6, 0xa1, 0x69, 0x42, 0x0c, 0x65, 0xaf, 0xb1, 0xe7, 0xec, 0xb7, 0x7d, 0x4b,
	0x91, 0x7b, 0xd0, 0x19, 0x45, 0xf2, 0x4d, 0xca, 0x0d, 0xab, 0x89, 0xac, 0x02, 0x20, 0x1f, 0x42,
	0x3b, 0x92, 0x63, 0x11, 0x0f, 0x99, 0xee, 0xb5, 0xf6, 0x9c, 0xfd, 0xee, 0x91, 0xdb, 0xcf, 0x72,
	0xeb, 0xe7, 0xc9, 0xf7, 0xcf, 0xf3, 0xe4, 0xfd, 0x16, 0xca, 0x0e, 0x34, 0xf9, 0x08, 0x20, 0x48,
	0x38, 0xd3, 0x3c, 0x34, 0x8a, 0xed, 0x6b, 0x15, 0x3b, 0x56, 0x3a, 0x53, 0x4d, 0x67, 0x61, 0xae,
	0xda, 0xb9, 0x5e, 0xd5, 0x4a, 0x67, 0xaa, 0x21, 0x8f, 0xb8, 0x55, 0x85, 0xeb, 0x55, 0xad, 0xf4,
	0x40, 0xd3, 0x1f, 0x1d, 0xb8, 0x73, 0x82, 0x31, 0x98, 0xc6, 0xf8, 0xfc, 0xcd, 0x62, 0xb5, 0x9d,
	0xab, 0xab, 0x5d, 0xab, 0xaa, 0xb6, 0xed, 0x61, 0x7d, 0xa1, 0x87, 0x0f, 0x00, 0x02, 0x19, 0xeb,
	0x84, 0x29, 0x1e, 0xb3, 0xbc, 0x4b, 0x05, 0x42, 0xa3, 0xc5, 0x30, 0x14, 0xe9, 0x41, 0x4b, 0xa5,
	0x41, 0xc0, 0x95, 0xc2, 0x20, 0xda, 0x7e, 0x4e, 0x1a, 0xce, 0x94, 0x2b, 0xc5, 0xc6, 0xdc, 0xfa,
	0xcf, 0x49, 0xf2, 0x18, 0x6e, 0x85, 0x4c, 0x33, 0x74, 0xdd, 0x3d, 0x7a, 0xab, 0x6f, 0xc7, 0xb6,
	0x5f, 0xcc, 0x9c, 0x8f, 0x02, 0xf4, 0x73, 0xe8, 0x9e, 0x0a, 0xa5, 0xf3, 0x94, 0x09, 0xdc, 0x9a,
	0x19, 0x73, 0xc6, 0x51, 0xdd, 0xc7, 0xff, 0x64, 0x0b, 0x1a, 0x91, 0x98, 0x0a, 0x8d, 0x3e, 0xea,
	0x7e, 0x46, 0x98, 0xf4, 0x14, 0x67, 0x49, 0x30, 0xc9, 0xd3, 0xcb, 0x28, 0xfa, 0xbd, 0x53, 0xb6,
	0xf8, 0x6f, 0xa3, 0xaf, 0x5f, 0x19, 0xbd, 0x09, 0x4d, 0x4b, 0xcd, 0x22, 0x2c, 0x63, 0xdd, 0xcf,
	0x08, 0xfa, 0x1c, 0xda, 0xa7, 0x66, 0x0a, 0x4d, 0x42, 0x45, 0x17, 0x9c, 0x2b, 0xba, 0x50, 0x5b,
	0xe9, 0xc2, 0x1f, 0xce, 0xdc, 0xc8, 0xcd, 0x72, 0x78, 0x08, 0xb7, 0xb5, 0xfc, 0x9a, 0xc7, 0x43,
	0x66, 0x24, 0xf3, 0x21, 0xe8, 0x22, 0x36, 0x40, 0x88, 0x3c, 0x86, 0xf5, 0x84, 0xbf, 0x4a, 0xb8,
	0x0a, 0x58, 0x32, 0x44, 0x86, 0x1d, 0x87, 0xb5, 0x39, 0x7c, 0x6e, 0x50, 0x72, 0x1f, 0x70, 0xb0,
	0xac, 0x4c, 0x03, 0x65, 0x3a, 0x06, 0xc9, 0xd8, 0x0b, 0x73, 0xda, 0x5c, 0x9a, 0xd3, 0x1d, 0xe8,
	0xf0, 0x6f, 0x67, 0x22, 0x61, 0x43, 0x1e, 0xe3, 0xfe, 0xd6, 0xfd, 0x76, 0x06, 0xbc, 0x88, 0xe9,
	0x4f, 0x0e, 0x6c, 0x9e, 0x4c, 0x58, 0x3c, 0xe6, 0x5f, 0x30, 0xa5, 0xbe, 0x91, 0x49, 0x78, 0xed,
	0xdc, 0x3f, 0x85, 0xcd, 0xa2, 0x4c, 0x43, 0x16, 0xe8, 0x94, 0x45, 0x36, 0xf7, 0x8d, 0x82, 0x31,
	0x40, 0x9c, 0x3c, 0x81, 0x8d, 0x38, 0xe5, 0x17, 0x6c, 0x58, 0xaa, 0x75, 0x56, 0x88, 0x75, 0xc4,
	0x4f, 0x8a, 0x82, 0xbf, 0x5c, 0x8d, 0xe4, 0x46, 0x85, 0xa7, 0xaf, 0x61, 0xc3, 0xe7, 0x8a, 0xeb,
	0x72, 0x46, 0x4f, 0x61, 0x33, 0x31, 0x1b, 0x3f, 0x8a, 0x78, 0xc0, 0xf3, 0x5a, 0x67, 0x99, 0x6d,
	0x94, 0x18, 0x59, 0x39, 0xab, 0x82, 0xae, 0x55, 0x07, 0xfd, 0xd9, 0x8a, 0xaf, 0x9b, 0xc5, 0xfc,
	0x0c, 0xd6, 0x7d, 0x6c, 0xf9, 0x04, 0x43, 0x30, 0x21, 0x57, 0x0c, 0x87, 0x53, 0x35, 0x1c, 0xf4,
	0x57, 0x67, 0x59, 0xf9, 0xff, 0x30, 0xb0, 0xc5, 0x4c, 0x36, 0x97, 0x66, 0xf2, 0x03, 0xe8, 0x9c,
	0xca, 0xb1, 0x4c, 0xf5, 0x3f, 0xaa, 0xc2, 0x27, 0x85, 0xd6, 0xcd, 0x5a, 0xf0, 0x04, 0xe0, 0x25,
	0xd7, 0x7f, 0xe7, 0xf4, 0x53, 0x51, 0x12, 0xfd, 0x6f, 0xcf, 0xf3, 0xd1, 0x6f, 0x0d, 0xe8, 0x1a,
	0xf0, 0x8c, 0x27, 0x17, 0x22, 0xe0, 0xe4, 0x63, 0x80, 0xe2, 0xe3, 0x40, 0xb6, 0xe7, 0x8a, 0x0b,
	0x1f, 0x2e, 0xb7, 0x1a, 0x57, 0xc4, 0x87, 0x76, 0x7e, 0x9a, 0xc9, 0xd6, 0x5c, 0xa6, 0x74, 0xff,
	0xdd, 0x2a, 0x54, 0x51, 0xf7, 0x87, 0xdf, 0xff, 0xfc, 0xa5, 0xb6, 0x45, 0x08, 0xbe, 0x66, 0xec,
	0x8b, 0xc8, 0x63, 0xe1, 0x54, 0xc4, 0xc4, 0x87, 0x06, 0xde, 0x49, 0xb2, 0x59, 0xa8, 0xda, 0xe3,
	0xeb, 0xae, 0x40, 0x8a, 0xbe, 0x8d, 0xa6, 0xee, 0xd3, 0xde, 0xaa, 0x29, 0x0f, 0x9f, 0x0e, 0xcf,
	0x9c, 0xf7, 0xc8, 0x0c, 0xd6, 0x16, 0x6f, 0x01, 0x71, 0x8b, 0x8c, 0x96, 0xcf, 0x95, 0x7b, 0x39,
	0x4f, 0xd1, 0x47, 0xe8, 0x6e, 0xcf, 0xdd, 0xa9, 0x70, 0x37, 0xb3, 0x72, 0xc6, 0xa3, 0x82, 0x3b,
	0x0b, 0x8b, 0x4c, 0xee, 0xce, 0x8d, 0x2e, 0x1f, 0x13, 0xf7, 0x52, 0x96, 0xa2, 0xef, 0xa3, 0xbb,
	0x47, 0xf4, 0xe1, 0x15, 0xee, 0xbc, 0xc4, 0x68, 0x19, 0xa7, 0x02, 0x6e, 0x97, 0x17, 0x97, 0xf4,
	0x4a, 0x86, 0x17, 0x8e, 0x81, 0x7b, 0x19, 0x47, 0xd1, 0x77, 0xd1, 0xe3, 0x2e, 0x75, 0x2b, 0x3c,
	0x66, 0x2b, 0x32, 0x31, 0xae, 0xbe, 0x84, 0x66, 0xb6, 0x1e, 0x84, 0x94, 0x7b, 0x92, 0x6d, 0x99,
	0xbb, 0x8a, 0x29, 0xfa, 0x0e, 0x1a, 0x7e, 0x40, 0xef, 0x56, 0x37, 0x4a, 0xa6, 0x98, 0xc2, 0x31,
	0xb4, 0xec, 0x2a, 0x90, 0x62, 0x8a, 0x8b, 0x3d, 0x72, 0x2b, 0x40, 0xf5, 0xfc, 0xf8, 0xab, 0xc3,
	0xb1, 0xd0, 0x93, 0x74, 0xd4, 0x0f, 0xe4, 0xd4, 0x3b, 0xfb, 0x74, 0x70, 0x3e, 0x38, 0x38, 0x91,
	0x91, 0x9c, 0x8e, 0x04, 0xf3, 0xd4, 0x84, 0x25, 0x3c, 0x3c, 0x18, 0xcb, 0x03, 0x7c, 0xae, 0x79,
	0xf6, 0x11, 0x3e, 0x6a, 0x22, 0x79, 0xfc, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xfa, 0xf5,
	0x3d, 0x96, 0x0b, 0x00, 0x00,
}
