syntax = "proto3";

package branch.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/OSCARstacku/shared-go-proto/branch/v1";

// -------------------------------------------------------------------
// Branch Entity message
// -------------------------------------------------------------------

message BranchEntity {
  string id = 1;
  string name = 2;
  string description = 3;
  bool status = 4;
  int32 age = 5;
  int64 total = 6;
  double price = 7;
  repeated string tags = 8;
  repeated int32 numbers = 9;
  map<string, string> metadata = 10;

  string created_by = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  google.protobuf.Timestamp deleted_at = 14;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreateBranch
// -------------------------------------------------------------------

message CreateBranchReq {
  BranchEntity data = 1;
}

message CreateBranchRes {
  bool success = 1;
  string message = 2;
  BranchEntity data = 3;
}

// -------------------------------------------------------------------
// GetBranch
// -------------------------------------------------------------------

message GetBranchReq {
  string id = 1;
}

message GetBranchRes {
  bool success = 1;
  string message = 2;
  BranchEntity data = 3;
}

// -------------------------------------------------------------------
// ListBranch
// -------------------------------------------------------------------

message ListBranchReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListBranchRes {
  bool success = 1;
  string message = 2;
  repeated BranchEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdateBranch
// -------------------------------------------------------------------

message UpdateBranchReq {
  string id = 1;
  BranchEntity data = 2;
}

message UpdateBranchRes {
  bool success = 1;
  string message = 2;
  BranchEntity data = 3;
}

// -------------------------------------------------------------------
// DeleteBranch
// -------------------------------------------------------------------

message DeleteBranchReq {
  string id = 1;
}

message DeleteBranchRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service BranchService {

  rpc CreateBranch(CreateBranchReq) returns (CreateBranchRes) {
    option (google.api.http) = {
      post: "/api/v1/branch"
      body: "*"
    };
  }

  rpc GetBranch(GetBranchReq) returns (GetBranchRes) {
    option (google.api.http) = {
      get: "/api/v1/branch/{id}"
    };
  }

  rpc ListBranch(ListBranchReq) returns (ListBranchRes) {
    option (google.api.http) = {
      get: "/api/v1/branch"
    };
  }

  rpc UpdateBranch(UpdateBranchReq) returns (UpdateBranchRes) {
    option (google.api.http) = {
      put: "/api/v1/branch/{id}"
      body: "*"
    };
  }

  rpc DeleteBranch(DeleteBranchReq) returns (DeleteBranchRes) {
    option (google.api.http) = {
      delete: "/api/v1/branch/{id}"
    };
  }

}
