// Code generated by protoc-gen-go. DO NOT EDIT.
// source: branch/v1/branch.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BranchEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BranchEntity) Reset()         { *m = BranchEntity{} }
func (m *BranchEntity) String() string { return proto.CompactTextString(m) }
func (*BranchEntity) ProtoMessage()    {}
func (*BranchEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{0}
}

func (m *BranchEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchEntity.Unmarshal(m, b)
}
func (m *BranchEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchEntity.Marshal(b, m, deterministic)
}
func (m *BranchEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchEntity.Merge(m, src)
}
func (m *BranchEntity) XXX_Size() int {
	return xxx_messageInfo_BranchEntity.Size(m)
}
func (m *BranchEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BranchEntity proto.InternalMessageInfo

func (m *BranchEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BranchEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BranchEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BranchEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *BranchEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *BranchEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BranchEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BranchEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BranchEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *BranchEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BranchEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *BranchEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *BranchEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *BranchEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateBranchReq struct {
	Data                 *BranchEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateBranchReq) Reset()         { *m = CreateBranchReq{} }
func (m *CreateBranchReq) String() string { return proto.CompactTextString(m) }
func (*CreateBranchReq) ProtoMessage()    {}
func (*CreateBranchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{1}
}

func (m *CreateBranchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBranchReq.Unmarshal(m, b)
}
func (m *CreateBranchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBranchReq.Marshal(b, m, deterministic)
}
func (m *CreateBranchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBranchReq.Merge(m, src)
}
func (m *CreateBranchReq) XXX_Size() int {
	return xxx_messageInfo_CreateBranchReq.Size(m)
}
func (m *CreateBranchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBranchReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBranchReq proto.InternalMessageInfo

func (m *CreateBranchReq) GetData() *BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateBranchRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BranchEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateBranchRes) Reset()         { *m = CreateBranchRes{} }
func (m *CreateBranchRes) String() string { return proto.CompactTextString(m) }
func (*CreateBranchRes) ProtoMessage()    {}
func (*CreateBranchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{2}
}

func (m *CreateBranchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBranchRes.Unmarshal(m, b)
}
func (m *CreateBranchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBranchRes.Marshal(b, m, deterministic)
}
func (m *CreateBranchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBranchRes.Merge(m, src)
}
func (m *CreateBranchRes) XXX_Size() int {
	return xxx_messageInfo_CreateBranchRes.Size(m)
}
func (m *CreateBranchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBranchRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBranchRes proto.InternalMessageInfo

func (m *CreateBranchRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateBranchRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateBranchRes) GetData() *BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBranchReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBranchReq) Reset()         { *m = GetBranchReq{} }
func (m *GetBranchReq) String() string { return proto.CompactTextString(m) }
func (*GetBranchReq) ProtoMessage()    {}
func (*GetBranchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{3}
}

func (m *GetBranchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBranchReq.Unmarshal(m, b)
}
func (m *GetBranchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBranchReq.Marshal(b, m, deterministic)
}
func (m *GetBranchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBranchReq.Merge(m, src)
}
func (m *GetBranchReq) XXX_Size() int {
	return xxx_messageInfo_GetBranchReq.Size(m)
}
func (m *GetBranchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBranchReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBranchReq proto.InternalMessageInfo

func (m *GetBranchReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBranchRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BranchEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetBranchRes) Reset()         { *m = GetBranchRes{} }
func (m *GetBranchRes) String() string { return proto.CompactTextString(m) }
func (*GetBranchRes) ProtoMessage()    {}
func (*GetBranchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{4}
}

func (m *GetBranchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBranchRes.Unmarshal(m, b)
}
func (m *GetBranchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBranchRes.Marshal(b, m, deterministic)
}
func (m *GetBranchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBranchRes.Merge(m, src)
}
func (m *GetBranchRes) XXX_Size() int {
	return xxx_messageInfo_GetBranchRes.Size(m)
}
func (m *GetBranchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBranchRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetBranchRes proto.InternalMessageInfo

func (m *GetBranchRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetBranchRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetBranchRes) GetData() *BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListBranchReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBranchReq) Reset()         { *m = ListBranchReq{} }
func (m *ListBranchReq) String() string { return proto.CompactTextString(m) }
func (*ListBranchReq) ProtoMessage()    {}
func (*ListBranchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{5}
}

func (m *ListBranchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBranchReq.Unmarshal(m, b)
}
func (m *ListBranchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBranchReq.Marshal(b, m, deterministic)
}
func (m *ListBranchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBranchReq.Merge(m, src)
}
func (m *ListBranchReq) XXX_Size() int {
	return xxx_messageInfo_ListBranchReq.Size(m)
}
func (m *ListBranchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBranchReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListBranchReq proto.InternalMessageInfo

func (m *ListBranchReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListBranchReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListBranchReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListBranchRes struct {
	Success              bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*BranchEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListBranchRes) Reset()         { *m = ListBranchRes{} }
func (m *ListBranchRes) String() string { return proto.CompactTextString(m) }
func (*ListBranchRes) ProtoMessage()    {}
func (*ListBranchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{6}
}

func (m *ListBranchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBranchRes.Unmarshal(m, b)
}
func (m *ListBranchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBranchRes.Marshal(b, m, deterministic)
}
func (m *ListBranchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBranchRes.Merge(m, src)
}
func (m *ListBranchRes) XXX_Size() int {
	return xxx_messageInfo_ListBranchRes.Size(m)
}
func (m *ListBranchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBranchRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListBranchRes proto.InternalMessageInfo

func (m *ListBranchRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListBranchRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListBranchRes) GetData() []*BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListBranchRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateBranchReq struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *BranchEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateBranchReq) Reset()         { *m = UpdateBranchReq{} }
func (m *UpdateBranchReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBranchReq) ProtoMessage()    {}
func (*UpdateBranchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{7}
}

func (m *UpdateBranchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBranchReq.Unmarshal(m, b)
}
func (m *UpdateBranchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBranchReq.Marshal(b, m, deterministic)
}
func (m *UpdateBranchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBranchReq.Merge(m, src)
}
func (m *UpdateBranchReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBranchReq.Size(m)
}
func (m *UpdateBranchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBranchReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBranchReq proto.InternalMessageInfo

func (m *UpdateBranchReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBranchReq) GetData() *BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateBranchRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *BranchEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateBranchRes) Reset()         { *m = UpdateBranchRes{} }
func (m *UpdateBranchRes) String() string { return proto.CompactTextString(m) }
func (*UpdateBranchRes) ProtoMessage()    {}
func (*UpdateBranchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{8}
}

func (m *UpdateBranchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBranchRes.Unmarshal(m, b)
}
func (m *UpdateBranchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBranchRes.Marshal(b, m, deterministic)
}
func (m *UpdateBranchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBranchRes.Merge(m, src)
}
func (m *UpdateBranchRes) XXX_Size() int {
	return xxx_messageInfo_UpdateBranchRes.Size(m)
}
func (m *UpdateBranchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBranchRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBranchRes proto.InternalMessageInfo

func (m *UpdateBranchRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateBranchRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateBranchRes) GetData() *BranchEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteBranchReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBranchReq) Reset()         { *m = DeleteBranchReq{} }
func (m *DeleteBranchReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBranchReq) ProtoMessage()    {}
func (*DeleteBranchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{9}
}

func (m *DeleteBranchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBranchReq.Unmarshal(m, b)
}
func (m *DeleteBranchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBranchReq.Marshal(b, m, deterministic)
}
func (m *DeleteBranchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBranchReq.Merge(m, src)
}
func (m *DeleteBranchReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBranchReq.Size(m)
}
func (m *DeleteBranchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBranchReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBranchReq proto.InternalMessageInfo

func (m *DeleteBranchReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBranchRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBranchRes) Reset()         { *m = DeleteBranchRes{} }
func (m *DeleteBranchRes) String() string { return proto.CompactTextString(m) }
func (*DeleteBranchRes) ProtoMessage()    {}
func (*DeleteBranchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccaf623f341f2830, []int{10}
}

func (m *DeleteBranchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBranchRes.Unmarshal(m, b)
}
func (m *DeleteBranchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBranchRes.Marshal(b, m, deterministic)
}
func (m *DeleteBranchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBranchRes.Merge(m, src)
}
func (m *DeleteBranchRes) XXX_Size() int {
	return xxx_messageInfo_DeleteBranchRes.Size(m)
}
func (m *DeleteBranchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBranchRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBranchRes proto.InternalMessageInfo

func (m *DeleteBranchRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteBranchRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BranchEntity)(nil), "branch.v1.BranchEntity")
	proto.RegisterMapType((map[string]string)(nil), "branch.v1.BranchEntity.MetadataEntry")
	proto.RegisterType((*CreateBranchReq)(nil), "branch.v1.CreateBranchReq")
	proto.RegisterType((*CreateBranchRes)(nil), "branch.v1.CreateBranchRes")
	proto.RegisterType((*GetBranchReq)(nil), "branch.v1.GetBranchReq")
	proto.RegisterType((*GetBranchRes)(nil), "branch.v1.GetBranchRes")
	proto.RegisterType((*ListBranchReq)(nil), "branch.v1.ListBranchReq")
	proto.RegisterType((*ListBranchRes)(nil), "branch.v1.ListBranchRes")
	proto.RegisterType((*UpdateBranchReq)(nil), "branch.v1.UpdateBranchReq")
	proto.RegisterType((*UpdateBranchRes)(nil), "branch.v1.UpdateBranchRes")
	proto.RegisterType((*DeleteBranchReq)(nil), "branch.v1.DeleteBranchReq")
	proto.RegisterType((*DeleteBranchRes)(nil), "branch.v1.DeleteBranchRes")
}

func init() {
	proto.RegisterFile("branch/v1/branch.proto", fileDescriptor_ccaf623f341f2830)
}

var fileDescriptor_ccaf623f341f2830 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xe3, 0xa4, 0x4d, 0x26, 0x49, 0x5b, 0x6d, 0xcf, 0xe9, 0xd9, 0xe3, 0x73, 0x28, 0xc6,
	0x12, 0x92, 0x55, 0x54, 0x9b, 0x86, 0x1b, 0x28, 0x12, 0x52, 0x5a, 0x2a, 0x6e, 0xf8, 0x11, 0x2e,
	0x48, 0xa8, 0x37, 0x68, 0x63, 0x6f, 0x13, 0xab, 0xb1, 0x1d, 0xbc, 0xeb, 0x48, 0x11, 0xe2, 0x86,
	0x0b, 0x5e, 0x80, 0x97, 0xe0, 0x7d, 0x78, 0x05, 0x5e, 0x81, 0x7b, 0xb4, 0x6b, 0xc7, 0xb1, 0xad,
	0x5a, 0xad, 0x40, 0xea, 0xdd, 0xce, 0xce, 0xcc, 0x37, 0xdf, 0xce, 0x7c, 0x63, 0xc3, 0xce, 0x28,
	0x26, 0xa1, 0x3b, 0xb1, 0xe7, 0x07, 0x76, 0x7a, 0xb2, 0x66, 0x71, 0xc4, 0x23, 0xd4, 0xc9, 0xac,
	0xf9, 0x81, 0x76, 0x7b, 0x1c, 0x45, 0xe3, 0x29, 0xb5, 0xa5, 0x63, 0x94, 0x9c, 0xdb, 0xdc, 0x0f,
	0x28, 0xe3, 0x24, 0x98, 0xa5, 0xb1, 0xda, 0xff, 0x59, 0x00, 0x99, 0xf9, 0x36, 0x09, 0xc3, 0x88,
	0x13, 0xee, 0x47, 0x21, 0x4b, 0xbd, 0xc6, 0xb7, 0x26, 0xf4, 0x8e, 0x24, 0xd8, 0x49, 0xc8, 0x7d,
	0xbe, 0x40, 0x1b, 0xd0, 0xf0, 0x3d, 0xac, 0xe8, 0x8a, 0xd9, 0x71, 0x1a, 0xbe, 0x87, 0x10, 0x34,
	0x43, 0x12, 0x50, 0xdc, 0x90, 0x37, 0xf2, 0x8c, 0x74, 0xe8, 0x7a, 0x94, 0xb9, 0xb1, 0x3f, 0x13,
	0x50, 0x58, 0x95, 0xae, 0xe2, 0x15, 0xda, 0x81, 0x35, 0xc6, 0x09, 0x4f, 0x18, 0x6e, 0xea, 0x8a,
	0xd9, 0x76, 0x32, 0x0b, 0x6d, 0x81, 0x4a, 0xc6, 0x14, 0xb7, 0x74, 0xc5, 0x6c, 0x39, 0xe2, 0x88,
	0xfe, 0x82, 0x16, 0x8f, 0x38, 0x99, 0xe2, 0x35, 0x5d, 0x31, 0x55, 0x27, 0x35, 0xc4, 0xed, 0x2c,
	0xf6, 0x5d, 0x8a, 0xd7, 0x75, 0xc5, 0x54, 0x9c, 0xd4, 0x10, 0x5c, 0x38, 0x19, 0x33, 0xdc, 0xd6,
	0x55, 0xc1, 0x45, 0x9c, 0x11, 0x86, 0xf5, 0x30, 0x09, 0x46, 0x34, 0x66, 0xb8, 0xa3, 0xab, 0x66,
	0xcb, 0x59, 0x9a, 0x68, 0x08, 0xed, 0x80, 0x72, 0xe2, 0x11, 0x4e, 0x30, 0xe8, 0xaa, 0xd9, 0x1d,
	0xdc, 0xb5, 0xf2, 0xbe, 0x59, 0xc5, 0x47, 0x5b, 0x2f, 0xb2, 0xb8, 0x93, 0x90, 0xc7, 0x0b, 0x27,
	0x4f, 0x43, 0xb7, 0x00, 0xdc, 0x98, 0x12, 0x4e, 0xbd, 0xf7, 0xa3, 0x05, 0xee, 0xca, 0x77, 0x76,
	0xb2, 0x9b, 0xa3, 0x05, 0x7a, 0xb4, 0x72, 0x13, 0x8e, 0x7b, 0xba, 0x62, 0x76, 0x07, 0x9a, 0x95,
	0xf6, 0xdb, 0x5a, 0x0e, 0xc4, 0x7a, 0xb3, 0x1c, 0x48, 0x9e, 0x3a, 0xe4, 0x22, 0x35, 0x99, 0x79,
	0xcb, 0xd4, 0xfe, 0xd5, 0xa9, 0x59, 0x74, 0x9a, 0xea, 0xd1, 0x29, 0xcd, 0x52, 0x37, 0xae, 0x4e,
	0xcd, 0xa2, 0x87, 0x5c, 0x7b, 0x0c, 0xfd, 0xd2, 0x53, 0xc5, 0x3c, 0x2e, 0xe8, 0x22, 0x1b, 0xb7,
	0x38, 0x8a, 0xce, 0xcf, 0xc9, 0x34, 0x59, 0x0e, 0x3c, 0x35, 0x0e, 0x1b, 0x0f, 0x15, 0xe3, 0x09,
	0x6c, 0x1e, 0x4b, 0xfe, 0x69, 0xeb, 0x1c, 0xfa, 0x01, 0xdd, 0x83, 0xa6, 0x6c, 0xaf, 0x22, 0x49,
	0xfc, 0x53, 0xd3, 0x5e, 0x47, 0x06, 0x19, 0x71, 0x35, 0x5f, 0x0e, 0x8f, 0x25, 0xae, 0x4b, 0x19,
	0x93, 0x10, 0x6d, 0x67, 0x69, 0x0a, 0x4f, 0x40, 0x19, 0x13, 0x62, 0x49, 0x89, 0x2c, 0xcd, 0xbc,
	0xa6, 0x7a, 0x9d, 0x9a, 0xbb, 0xd0, 0x7b, 0x46, 0xf9, 0x8a, 0x70, 0x45, 0xdd, 0x46, 0x54, 0xf2,
	0xdf, 0x00, 0xa1, 0xd7, 0xd0, 0x7f, 0xee, 0xb3, 0x02, 0x23, 0x04, 0xcd, 0x99, 0x00, 0x55, 0xe4,
	0x4a, 0xc8, 0xb3, 0x98, 0xc1, 0xd4, 0x0f, 0x7c, 0x2e, 0x2b, 0xb5, 0x9c, 0xd4, 0x90, 0x3b, 0x45,
	0x49, 0xec, 0x4e, 0xb2, 0x85, 0xcb, 0x2c, 0xe3, 0x8b, 0x52, 0xc6, 0xfc, 0xd3, 0x57, 0xa8, 0x57,
	0xbe, 0x62, 0xb5, 0xb4, 0xcd, 0xc2, 0xd2, 0x1a, 0x2f, 0x61, 0xf3, 0xad, 0x54, 0x69, 0x6d, 0xbf,
	0xf3, 0x2a, 0x8d, 0x6b, 0x0a, 0xa6, 0x8c, 0x77, 0x03, 0xf3, 0xb9, 0x03, 0x9b, 0x4f, 0xe5, 0xba,
	0xd4, 0x6b, 0xe6, 0xa4, 0x1a, 0xf2, 0x5b, 0xb4, 0x06, 0x3f, 0x55, 0xe8, 0xa7, 0x08, 0xa7, 0x34,
	0x9e, 0x8b, 0xcf, 0x1b, 0x81, 0x5e, 0x71, 0x41, 0x90, 0x56, 0xa0, 0x5a, 0xd9, 0x3c, 0xad, 0xde,
	0xc7, 0x8c, 0x7f, 0x3f, 0x7f, 0xff, 0xf1, 0xb5, 0xb1, 0x6d, 0x6c, 0xc8, 0x6f, 0x7e, 0xfe, 0xef,
	0x38, 0x54, 0xf6, 0xd0, 0x19, 0x74, 0x72, 0xbd, 0xa3, 0x62, 0x2b, 0x8a, 0x5b, 0xa2, 0xd5, 0x38,
	0x98, 0xf1, 0x9f, 0x44, 0xfe, 0x1b, 0x6d, 0x97, 0x91, 0xed, 0x8f, 0xbe, 0xf7, 0x09, 0xbd, 0x03,
	0x58, 0xc9, 0x10, 0xe1, 0x02, 0x46, 0x49, 0xf1, 0x5a, 0x9d, 0x87, 0x19, 0x3b, 0x12, 0x7e, 0x0b,
	0x55, 0x88, 0xa3, 0x73, 0xe8, 0x15, 0x85, 0x50, 0x6a, 0x4c, 0x45, 0x71, 0x5a, 0xbd, 0x8f, 0x19,
	0xbb, 0x12, 0x1f, 0x6b, 0x97, 0xd1, 0x17, 0xdd, 0x71, 0xa1, 0x57, 0x9c, 0x6c, 0xa9, 0x4e, 0x45,
	0x15, 0x5a, 0xbd, 0x2f, 0x6f, 0xd3, 0xde, 0x65, 0x75, 0x8e, 0x06, 0x67, 0xf7, 0xc7, 0x3e, 0x9f,
	0x24, 0x23, 0xcb, 0x8d, 0x02, 0xfb, 0xd5, 0xe9, 0xf1, 0xd0, 0x61, 0x9c, 0xb8, 0x17, 0x89, 0xcd,
	0x26, 0x24, 0xa6, 0xde, 0xfe, 0x38, 0xda, 0x97, 0x5f, 0x71, 0x3b, 0xff, 0xf9, 0x8f, 0xd6, 0xe4,
	0xc5, 0x83, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0xa2, 0x71, 0x22, 0x10, 0x08, 0x00, 0x00,
}
