// Code generated by protoc-gen-go. DO NOT EDIT.
// source: centrifugo/v1/centrifugo.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CentrifugoEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CentrifugoEntity) Reset()         { *m = CentrifugoEntity{} }
func (m *CentrifugoEntity) String() string { return proto.CompactTextString(m) }
func (*CentrifugoEntity) ProtoMessage()    {}
func (*CentrifugoEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{0}
}

func (m *CentrifugoEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CentrifugoEntity.Unmarshal(m, b)
}
func (m *CentrifugoEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CentrifugoEntity.Marshal(b, m, deterministic)
}
func (m *CentrifugoEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CentrifugoEntity.Merge(m, src)
}
func (m *CentrifugoEntity) XXX_Size() int {
	return xxx_messageInfo_CentrifugoEntity.Size(m)
}
func (m *CentrifugoEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_CentrifugoEntity.DiscardUnknown(m)
}

var xxx_messageInfo_CentrifugoEntity proto.InternalMessageInfo

func (m *CentrifugoEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CentrifugoEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CentrifugoEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CentrifugoEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CentrifugoEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CentrifugoEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CentrifugoEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CentrifugoEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CentrifugoEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *CentrifugoEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CentrifugoEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CentrifugoEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CentrifugoEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CentrifugoEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateCentrifugoReq struct {
	Data                 *CentrifugoEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCentrifugoReq) Reset()         { *m = CreateCentrifugoReq{} }
func (m *CreateCentrifugoReq) String() string { return proto.CompactTextString(m) }
func (*CreateCentrifugoReq) ProtoMessage()    {}
func (*CreateCentrifugoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{1}
}

func (m *CreateCentrifugoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCentrifugoReq.Unmarshal(m, b)
}
func (m *CreateCentrifugoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCentrifugoReq.Marshal(b, m, deterministic)
}
func (m *CreateCentrifugoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCentrifugoReq.Merge(m, src)
}
func (m *CreateCentrifugoReq) XXX_Size() int {
	return xxx_messageInfo_CreateCentrifugoReq.Size(m)
}
func (m *CreateCentrifugoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCentrifugoReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCentrifugoReq proto.InternalMessageInfo

func (m *CreateCentrifugoReq) GetData() *CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateCentrifugoRes struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugoEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCentrifugoRes) Reset()         { *m = CreateCentrifugoRes{} }
func (m *CreateCentrifugoRes) String() string { return proto.CompactTextString(m) }
func (*CreateCentrifugoRes) ProtoMessage()    {}
func (*CreateCentrifugoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{2}
}

func (m *CreateCentrifugoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCentrifugoRes.Unmarshal(m, b)
}
func (m *CreateCentrifugoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCentrifugoRes.Marshal(b, m, deterministic)
}
func (m *CreateCentrifugoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCentrifugoRes.Merge(m, src)
}
func (m *CreateCentrifugoRes) XXX_Size() int {
	return xxx_messageInfo_CreateCentrifugoRes.Size(m)
}
func (m *CreateCentrifugoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCentrifugoRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCentrifugoRes proto.InternalMessageInfo

func (m *CreateCentrifugoRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateCentrifugoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCentrifugoRes) GetData() *CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCentrifugoReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCentrifugoReq) Reset()         { *m = GetCentrifugoReq{} }
func (m *GetCentrifugoReq) String() string { return proto.CompactTextString(m) }
func (*GetCentrifugoReq) ProtoMessage()    {}
func (*GetCentrifugoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{3}
}

func (m *GetCentrifugoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentrifugoReq.Unmarshal(m, b)
}
func (m *GetCentrifugoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentrifugoReq.Marshal(b, m, deterministic)
}
func (m *GetCentrifugoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentrifugoReq.Merge(m, src)
}
func (m *GetCentrifugoReq) XXX_Size() int {
	return xxx_messageInfo_GetCentrifugoReq.Size(m)
}
func (m *GetCentrifugoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentrifugoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentrifugoReq proto.InternalMessageInfo

func (m *GetCentrifugoReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCentrifugoRes struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugoEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCentrifugoRes) Reset()         { *m = GetCentrifugoRes{} }
func (m *GetCentrifugoRes) String() string { return proto.CompactTextString(m) }
func (*GetCentrifugoRes) ProtoMessage()    {}
func (*GetCentrifugoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{4}
}

func (m *GetCentrifugoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentrifugoRes.Unmarshal(m, b)
}
func (m *GetCentrifugoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentrifugoRes.Marshal(b, m, deterministic)
}
func (m *GetCentrifugoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentrifugoRes.Merge(m, src)
}
func (m *GetCentrifugoRes) XXX_Size() int {
	return xxx_messageInfo_GetCentrifugoRes.Size(m)
}
func (m *GetCentrifugoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentrifugoRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentrifugoRes proto.InternalMessageInfo

func (m *GetCentrifugoRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetCentrifugoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCentrifugoRes) GetData() *CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListCentrifugoReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCentrifugoReq) Reset()         { *m = ListCentrifugoReq{} }
func (m *ListCentrifugoReq) String() string { return proto.CompactTextString(m) }
func (*ListCentrifugoReq) ProtoMessage()    {}
func (*ListCentrifugoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{5}
}

func (m *ListCentrifugoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCentrifugoReq.Unmarshal(m, b)
}
func (m *ListCentrifugoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCentrifugoReq.Marshal(b, m, deterministic)
}
func (m *ListCentrifugoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCentrifugoReq.Merge(m, src)
}
func (m *ListCentrifugoReq) XXX_Size() int {
	return xxx_messageInfo_ListCentrifugoReq.Size(m)
}
func (m *ListCentrifugoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCentrifugoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCentrifugoReq proto.InternalMessageInfo

func (m *ListCentrifugoReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCentrifugoReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListCentrifugoReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListCentrifugoRes struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*CentrifugoEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64               `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListCentrifugoRes) Reset()         { *m = ListCentrifugoRes{} }
func (m *ListCentrifugoRes) String() string { return proto.CompactTextString(m) }
func (*ListCentrifugoRes) ProtoMessage()    {}
func (*ListCentrifugoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{6}
}

func (m *ListCentrifugoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCentrifugoRes.Unmarshal(m, b)
}
func (m *ListCentrifugoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCentrifugoRes.Marshal(b, m, deterministic)
}
func (m *ListCentrifugoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCentrifugoRes.Merge(m, src)
}
func (m *ListCentrifugoRes) XXX_Size() int {
	return xxx_messageInfo_ListCentrifugoRes.Size(m)
}
func (m *ListCentrifugoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCentrifugoRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListCentrifugoRes proto.InternalMessageInfo

func (m *ListCentrifugoRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListCentrifugoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListCentrifugoRes) GetData() []*CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListCentrifugoRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateCentrifugoReq struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *CentrifugoEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCentrifugoReq) Reset()         { *m = UpdateCentrifugoReq{} }
func (m *UpdateCentrifugoReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCentrifugoReq) ProtoMessage()    {}
func (*UpdateCentrifugoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{7}
}

func (m *UpdateCentrifugoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCentrifugoReq.Unmarshal(m, b)
}
func (m *UpdateCentrifugoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCentrifugoReq.Marshal(b, m, deterministic)
}
func (m *UpdateCentrifugoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCentrifugoReq.Merge(m, src)
}
func (m *UpdateCentrifugoReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCentrifugoReq.Size(m)
}
func (m *UpdateCentrifugoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCentrifugoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCentrifugoReq proto.InternalMessageInfo

func (m *UpdateCentrifugoReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCentrifugoReq) GetData() *CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateCentrifugoRes struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugoEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCentrifugoRes) Reset()         { *m = UpdateCentrifugoRes{} }
func (m *UpdateCentrifugoRes) String() string { return proto.CompactTextString(m) }
func (*UpdateCentrifugoRes) ProtoMessage()    {}
func (*UpdateCentrifugoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{8}
}

func (m *UpdateCentrifugoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCentrifugoRes.Unmarshal(m, b)
}
func (m *UpdateCentrifugoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCentrifugoRes.Marshal(b, m, deterministic)
}
func (m *UpdateCentrifugoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCentrifugoRes.Merge(m, src)
}
func (m *UpdateCentrifugoRes) XXX_Size() int {
	return xxx_messageInfo_UpdateCentrifugoRes.Size(m)
}
func (m *UpdateCentrifugoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCentrifugoRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCentrifugoRes proto.InternalMessageInfo

func (m *UpdateCentrifugoRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateCentrifugoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateCentrifugoRes) GetData() *CentrifugoEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteCentrifugoReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCentrifugoReq) Reset()         { *m = DeleteCentrifugoReq{} }
func (m *DeleteCentrifugoReq) String() string { return proto.CompactTextString(m) }
func (*DeleteCentrifugoReq) ProtoMessage()    {}
func (*DeleteCentrifugoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{9}
}

func (m *DeleteCentrifugoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCentrifugoReq.Unmarshal(m, b)
}
func (m *DeleteCentrifugoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCentrifugoReq.Marshal(b, m, deterministic)
}
func (m *DeleteCentrifugoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCentrifugoReq.Merge(m, src)
}
func (m *DeleteCentrifugoReq) XXX_Size() int {
	return xxx_messageInfo_DeleteCentrifugoReq.Size(m)
}
func (m *DeleteCentrifugoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCentrifugoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCentrifugoReq proto.InternalMessageInfo

func (m *DeleteCentrifugoReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCentrifugoRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCentrifugoRes) Reset()         { *m = DeleteCentrifugoRes{} }
func (m *DeleteCentrifugoRes) String() string { return proto.CompactTextString(m) }
func (*DeleteCentrifugoRes) ProtoMessage()    {}
func (*DeleteCentrifugoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0172cae6a00abd, []int{10}
}

func (m *DeleteCentrifugoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCentrifugoRes.Unmarshal(m, b)
}
func (m *DeleteCentrifugoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCentrifugoRes.Marshal(b, m, deterministic)
}
func (m *DeleteCentrifugoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCentrifugoRes.Merge(m, src)
}
func (m *DeleteCentrifugoRes) XXX_Size() int {
	return xxx_messageInfo_DeleteCentrifugoRes.Size(m)
}
func (m *DeleteCentrifugoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCentrifugoRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCentrifugoRes proto.InternalMessageInfo

func (m *DeleteCentrifugoRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteCentrifugoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CentrifugoEntity)(nil), "centrifugo.v1.CentrifugoEntity")
	proto.RegisterMapType((map[string]string)(nil), "centrifugo.v1.CentrifugoEntity.MetadataEntry")
	proto.RegisterType((*CreateCentrifugoReq)(nil), "centrifugo.v1.CreateCentrifugoReq")
	proto.RegisterType((*CreateCentrifugoRes)(nil), "centrifugo.v1.CreateCentrifugoRes")
	proto.RegisterType((*GetCentrifugoReq)(nil), "centrifugo.v1.GetCentrifugoReq")
	proto.RegisterType((*GetCentrifugoRes)(nil), "centrifugo.v1.GetCentrifugoRes")
	proto.RegisterType((*ListCentrifugoReq)(nil), "centrifugo.v1.ListCentrifugoReq")
	proto.RegisterType((*ListCentrifugoRes)(nil), "centrifugo.v1.ListCentrifugoRes")
	proto.RegisterType((*UpdateCentrifugoReq)(nil), "centrifugo.v1.UpdateCentrifugoReq")
	proto.RegisterType((*UpdateCentrifugoRes)(nil), "centrifugo.v1.UpdateCentrifugoRes")
	proto.RegisterType((*DeleteCentrifugoReq)(nil), "centrifugo.v1.DeleteCentrifugoReq")
	proto.RegisterType((*DeleteCentrifugoRes)(nil), "centrifugo.v1.DeleteCentrifugoRes")
}

func init() {
	proto.RegisterFile("centrifugo/v1/centrifugo.proto", fileDescriptor_2b0172cae6a00abd)
}

var fileDescriptor_2b0172cae6a00abd = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcb, 0x4e, 0xdb, 0x4c,
	0x14, 0x96, 0xe3, 0x04, 0xc2, 0xe4, 0x0f, 0x0a, 0x03, 0xfa, 0x71, 0x2d, 0x28, 0xd6, 0x48, 0x95,
	0x2c, 0xa4, 0xd8, 0x02, 0x16, 0x2d, 0x74, 0x15, 0x2e, 0xaa, 0xa8, 0xda, 0x8d, 0x81, 0x0d, 0x9b,
	0x6a, 0x62, 0x0f, 0x61, 0xd4, 0xf8, 0x52, 0xcf, 0x38, 0x52, 0x84, 0xca, 0xa2, 0x8f, 0xd0, 0xbe,
	0x4a, 0xdf, 0xa4, 0xaf, 0xd0, 0x17, 0xe8, 0x1b, 0x54, 0x33, 0x76, 0x12, 0x6c, 0x07, 0x5c, 0x5a,
	0x89, 0xdd, 0x9c, 0x99, 0xef, 0x9c, 0xef, 0xdc, 0xbe, 0x38, 0xe0, 0xb9, 0x4b, 0x02, 0x1e, 0xd3,
	0xab, 0x64, 0x10, 0xda, 0xa3, 0x1d, 0x7b, 0x66, 0x59, 0x51, 0x1c, 0xf2, 0x10, 0xb6, 0xef, 0xdc,
	0x8c, 0x76, 0xf4, 0xad, 0x41, 0x18, 0x0e, 0x86, 0xc4, 0x96, 0x8f, 0xfd, 0xe4, 0xca, 0xe6, 0xd4,
	0x27, 0x8c, 0x63, 0x3f, 0x4a, 0xf1, 0xfa, 0x46, 0x06, 0xc0, 0x11, 0xb5, 0x71, 0x10, 0x84, 0x1c,
	0x73, 0x1a, 0x06, 0x2c, 0x7d, 0x45, 0xdf, 0xeb, 0xa0, 0x73, 0x34, 0x0d, 0x78, 0x12, 0x70, 0xca,
	0xc7, 0x70, 0x19, 0xd4, 0xa8, 0xa7, 0x29, 0x86, 0x62, 0x2e, 0x39, 0x35, 0xea, 0x41, 0x08, 0xea,
	0x01, 0xf6, 0x89, 0x56, 0x93, 0x37, 0xf2, 0x0c, 0x0d, 0xd0, 0xf2, 0x08, 0x73, 0x63, 0x1a, 0x89,
	0x70, 0x9a, 0x2a, 0x9f, 0xee, 0x5e, 0xc1, 0xff, 0xc1, 0x02, 0xe3, 0x98, 0x27, 0x4c, 0xab, 0x1b,
	0x8a, 0xd9, 0x74, 0x32, 0x0b, 0x76, 0x80, 0x8a, 0x07, 0x44, 0x6b, 0x18, 0x8a, 0xd9, 0x70, 0xc4,
	0x11, 0xae, 0x81, 0x06, 0x0f, 0x39, 0x1e, 0x6a, 0x0b, 0x86, 0x62, 0xaa, 0x4e, 0x6a, 0x88, 0xdb,
	0x28, 0xa6, 0x2e, 0xd1, 0x16, 0x0d, 0xc5, 0x54, 0x9c, 0xd4, 0x10, 0xb9, 0x70, 0x3c, 0x60, 0x5a,
	0xd3, 0x50, 0x45, 0x2e, 0xe2, 0x0c, 0x35, 0xb0, 0x18, 0x24, 0x7e, 0x9f, 0xc4, 0x4c, 0x5b, 0x32,
	0x54, 0xb3, 0xe1, 0x4c, 0x4c, 0x78, 0x0a, 0x9a, 0x3e, 0xe1, 0xd8, 0xc3, 0x1c, 0x6b, 0xc0, 0x50,
	0xcd, 0xd6, 0x6e, 0xd7, 0xca, 0xf5, 0xcf, 0x2a, 0x16, 0x6f, 0xbd, 0xcf, 0xf0, 0x27, 0x01, 0x8f,
	0xc7, 0xce, 0xd4, 0x1d, 0x6e, 0x02, 0xe0, 0xc6, 0x04, 0x73, 0xe2, 0x7d, 0xe8, 0x8f, 0xb5, 0x96,
	0xac, 0x77, 0x29, 0xbb, 0x39, 0x1c, 0xc3, 0xfd, 0xd9, 0x33, 0xe6, 0xda, 0x7f, 0x86, 0x62, 0xb6,
	0x76, 0x75, 0x2b, 0xed, 0xbd, 0x35, 0x19, 0x8e, 0x75, 0x3e, 0x19, 0xce, 0xd4, 0xb5, 0xc7, 0x85,
	0x6b, 0x12, 0x79, 0x13, 0xd7, 0x76, 0xb5, 0x6b, 0x86, 0x4e, 0x5d, 0x3d, 0x32, 0x24, 0x99, 0xeb,
	0x72, 0xb5, 0x6b, 0x86, 0xee, 0x71, 0xfd, 0x35, 0x68, 0xe7, 0x4a, 0x15, 0x73, 0xf9, 0x48, 0xc6,
	0xd9, 0xd8, 0xc5, 0x51, 0x4c, 0x60, 0x84, 0x87, 0xc9, 0x64, 0xf0, 0xa9, 0x71, 0x50, 0x7b, 0xa5,
	0xa0, 0xb7, 0x60, 0xf5, 0x48, 0xe6, 0x3f, 0x6b, 0x9f, 0x43, 0x3e, 0xc1, 0x3d, 0x50, 0x97, 0xad,
	0x56, 0x64, 0x22, 0x5b, 0x15, 0xad, 0x76, 0x24, 0x18, 0xdd, 0xce, 0x8b, 0x25, 0x87, 0xca, 0x12,
	0xd7, 0x25, 0x8c, 0xc9, 0x70, 0x4d, 0x67, 0x62, 0x8a, 0x17, 0x9f, 0x30, 0x26, 0x96, 0x28, 0x4d,
	0x6c, 0x62, 0x4e, 0xf9, 0xd5, 0xc7, 0xf0, 0x23, 0xd0, 0x79, 0x43, 0x78, 0xbe, 0x90, 0x82, 0x02,
	0xd0, 0x4d, 0x09, 0xf3, 0x84, 0x09, 0x5e, 0x80, 0x95, 0x77, 0x94, 0x15, 0x32, 0x84, 0xa0, 0x1e,
	0x09, 0x02, 0x45, 0xca, 0x48, 0x9e, 0xc5, 0xbc, 0x86, 0xd4, 0xa7, 0x5c, 0xb2, 0x36, 0x9c, 0xd4,
	0x90, 0x3a, 0x24, 0x38, 0x76, 0xaf, 0x33, 0x91, 0x66, 0x16, 0xfa, 0xaa, 0x94, 0xe3, 0xfe, 0x6b,
	0x55, 0xea, 0x1f, 0x57, 0x35, 0x13, 0x7d, 0xfd, 0x8e, 0xe8, 0xd1, 0x25, 0x58, 0xbd, 0x90, 0xdb,
	0xfd, 0xe0, 0x3c, 0xa6, 0x8c, 0xb5, 0x47, 0x2e, 0x5a, 0x39, 0xf6, 0x13, 0xce, 0xf1, 0x05, 0x58,
	0x3d, 0x96, 0xf2, 0x7b, 0x78, 0xd7, 0x4e, 0xe7, 0xc1, 0xfe, 0x2a, 0xcd, 0xdd, 0x5f, 0x75, 0xb0,
	0x32, 0x8b, 0x72, 0x46, 0xe2, 0x91, 0xf8, 0x09, 0x1d, 0x83, 0x4e, 0x51, 0x70, 0x10, 0x15, 0x4b,
	0x28, 0xab, 0x5b, 0xaf, 0xc6, 0x30, 0xb4, 0xf9, 0xe5, 0xc7, 0xcf, 0x6f, 0xb5, 0x75, 0x04, 0xe5,
	0xf7, 0x26, 0xf7, 0xfd, 0x3a, 0x50, 0xb6, 0x61, 0x0c, 0xda, 0x39, 0x1d, 0xc1, 0x62, 0xeb, 0x8a,
	0x4a, 0xd4, 0x2b, 0x00, 0x0c, 0x6d, 0x49, 0xc6, 0x67, 0x70, 0xbd, 0xcc, 0x68, 0xdf, 0x50, 0xef,
	0x33, 0x8c, 0xc0, 0x72, 0x7e, 0xcd, 0xa1, 0x51, 0x88, 0x59, 0x52, 0x97, 0x5e, 0x85, 0x60, 0x48,
	0x97, 0xb4, 0x6b, 0x70, 0x4e, 0xa1, 0xf0, 0x16, 0x74, 0x8a, 0x8b, 0x56, 0x6a, 0xf0, 0x9c, 0x2d,
	0xd7, 0xab, 0x31, 0x0c, 0x21, 0xc9, 0xbb, 0xa1, 0xdf, 0x57, 0xae, 0xe8, 0xf2, 0x0d, 0xe8, 0x14,
	0x37, 0xa8, 0xc4, 0x3f, 0x67, 0x13, 0xf5, 0x6a, 0xcc, 0xb4, 0xdd, 0xdb, 0xf7, 0xf1, 0x1f, 0xee,
	0x5f, 0xbe, 0x1c, 0x50, 0x7e, 0x9d, 0xf4, 0x2d, 0x37, 0xf4, 0xed, 0xb3, 0xe3, 0xde, 0x79, 0xaf,
	0x7b, 0x14, 0x0e, 0x43, 0xbf, 0x4f, 0xb1, 0xcd, 0xae, 0x71, 0x4c, 0xbc, 0xee, 0x20, 0xec, 0xca,
	0x8f, 0x93, 0x9d, 0xfb, 0xaf, 0xd3, 0x5f, 0x90, 0x97, 0x7b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x6f, 0x00, 0x92, 0xb9, 0x03, 0x09, 0x00, 0x00,
}
