syntax = "proto3";

package centrifugo.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/SDATA-Colombia/shared-go-proto/centrifugo/v1";

// -------------------------------------------------------------------
// Centrifugo Entity message
// -------------------------------------------------------------------

message CentrifugoEntity {
  string id = 1;
  string name = 2;
  string description = 3;
  bool status = 4;
  int32 age = 5;
  int64 total = 6;
  double price = 7;
  repeated string tags = 8;
  repeated int32 numbers = 9;
  map<string, string> metadata = 10;

  string created_by = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  google.protobuf.Timestamp deleted_at = 14;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreateCentrifugo
// -------------------------------------------------------------------

message CreateCentrifugoReq {
  CentrifugoEntity data = 1;
}

message CreateCentrifugoRes {
  bool success = 1;
  string message = 2;
  CentrifugoEntity data = 3;
}

// -------------------------------------------------------------------
// GetCentrifugo
// -------------------------------------------------------------------

message GetCentrifugoReq {
  string id = 1;
}

message GetCentrifugoRes {
  bool success = 1;
  string message = 2;
  CentrifugoEntity data = 3;
}

// -------------------------------------------------------------------
// ListCentrifugo
// -------------------------------------------------------------------

message ListCentrifugoReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListCentrifugoRes {
  bool success = 1;
  string message = 2;
  repeated CentrifugoEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdateCentrifugo
// -------------------------------------------------------------------

message UpdateCentrifugoReq {
  string id = 1;
  CentrifugoEntity data = 2;
}

message UpdateCentrifugoRes {
  bool success = 1;
  string message = 2;
  CentrifugoEntity data = 3;
}

// -------------------------------------------------------------------
// DeleteCentrifugo
// -------------------------------------------------------------------

message DeleteCentrifugoReq {
  string id = 1;
}

message DeleteCentrifugoRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service CentrifugoService {

  rpc CreateCentrifugo(CreateCentrifugoReq) returns (CreateCentrifugoRes) {
    option (google.api.http) = {
      post: "/api/v1/centrifugo"
      body: "*"
    };
  }

  rpc GetCentrifugo(GetCentrifugoReq) returns (GetCentrifugoRes) {
    option (google.api.http) = {
      get: "/api/v1/centrifugo/{id}"
    };
  }

  rpc ListCentrifugo(ListCentrifugoReq) returns (ListCentrifugoRes) {
    option (google.api.http) = {
      get: "/api/v1/centrifugo"
    };
  }

  rpc UpdateCentrifugo(UpdateCentrifugoReq) returns (UpdateCentrifugoRes) {
    option (google.api.http) = {
      put: "/api/v1/centrifugo/{id}"
      body: "*"
    };
  }

  rpc DeleteCentrifugo(DeleteCentrifugoReq) returns (DeleteCentrifugoRes) {
    option (google.api.http) = {
      delete: "/api/v1/centrifugo/{id}"
    };
  }

}
