// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plan/v1/plan.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanEntity struct {
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanIdCompany          string                 `protobuf:"bytes,2,opt,name=plan_id_company,json=planIdCompany,proto3" json:"plan_id_company,omitempty"`
	PlanAccentColor        string                 `protobuf:"bytes,3,opt,name=plan_accent_color,json=planAccentColor,proto3" json:"plan_accent_color,omitempty"`
	PlanAccentTextColor    string                 `protobuf:"bytes,4,opt,name=plan_accent_text_color,json=planAccentTextColor,proto3" json:"plan_accent_text_color,omitempty"`
	PlanTitle              string                 `protobuf:"bytes,5,opt,name=plan_title,json=planTitle,proto3" json:"plan_title,omitempty"`
	PlanSubtitle           string                 `protobuf:"bytes,6,opt,name=plan_subtitle,json=planSubtitle,proto3" json:"plan_subtitle,omitempty"`
	PlanDescriptionTinymce string                 `protobuf:"bytes,7,opt,name=plan_description_tinymce,json=planDescriptionTinymce,proto3" json:"plan_description_tinymce,omitempty"`
	PlanType               string                 `protobuf:"bytes,8,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	PlanCurrencyPrice      string                 `protobuf:"bytes,9,opt,name=plan_currency_price,json=planCurrencyPrice,proto3" json:"plan_currency_price,omitempty"`
	PlanMenu               string                 `protobuf:"bytes,10,opt,name=plan_menu,json=planMenu,proto3" json:"plan_menu,omitempty"`
	PlanDescriptionItems   string                 `protobuf:"bytes,11,opt,name=plan_description_items,json=planDescriptionItems,proto3" json:"plan_description_items,omitempty"`
	PlanDays               int32                  `protobuf:"varint,12,opt,name=plan_days,json=planDays,proto3" json:"plan_days,omitempty"`
	PlanOffices            int32                  `protobuf:"varint,13,opt,name=plan_offices,json=planOffices,proto3" json:"plan_offices,omitempty"`
	PlanUsers              int32                  `protobuf:"varint,14,opt,name=plan_users,json=planUsers,proto3" json:"plan_users,omitempty"`
	PlanTotalSales         int32                  `protobuf:"varint,15,opt,name=plan_total_sales,json=planTotalSales,proto3" json:"plan_total_sales,omitempty"`
	PlanPrice              float64                `protobuf:"fixed64,16,opt,name=plan_price,json=planPrice,proto3" json:"plan_price,omitempty"`
	PlanFeatured           bool                   `protobuf:"varint,17,opt,name=plan_featured,json=planFeatured,proto3" json:"plan_featured,omitempty"`
	PlanCustom             bool                   `protobuf:"varint,18,opt,name=plan_custom,json=planCustom,proto3" json:"plan_custom,omitempty"`
	ActivePlan             bool                   `protobuf:"varint,19,opt,name=active_plan,json=activePlan,proto3" json:"active_plan,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt              *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *PlanEntity) Reset()         { *m = PlanEntity{} }
func (m *PlanEntity) String() string { return proto.CompactTextString(m) }
func (*PlanEntity) ProtoMessage()    {}
func (*PlanEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{0}
}

func (m *PlanEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanEntity.Unmarshal(m, b)
}
func (m *PlanEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanEntity.Marshal(b, m, deterministic)
}
func (m *PlanEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanEntity.Merge(m, src)
}
func (m *PlanEntity) XXX_Size() int {
	return xxx_messageInfo_PlanEntity.Size(m)
}
func (m *PlanEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanEntity.DiscardUnknown(m)
}

var xxx_messageInfo_PlanEntity proto.InternalMessageInfo

func (m *PlanEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlanEntity) GetPlanIdCompany() string {
	if m != nil {
		return m.PlanIdCompany
	}
	return ""
}

func (m *PlanEntity) GetPlanAccentColor() string {
	if m != nil {
		return m.PlanAccentColor
	}
	return ""
}

func (m *PlanEntity) GetPlanAccentTextColor() string {
	if m != nil {
		return m.PlanAccentTextColor
	}
	return ""
}

func (m *PlanEntity) GetPlanTitle() string {
	if m != nil {
		return m.PlanTitle
	}
	return ""
}

func (m *PlanEntity) GetPlanSubtitle() string {
	if m != nil {
		return m.PlanSubtitle
	}
	return ""
}

func (m *PlanEntity) GetPlanDescriptionTinymce() string {
	if m != nil {
		return m.PlanDescriptionTinymce
	}
	return ""
}

func (m *PlanEntity) GetPlanType() string {
	if m != nil {
		return m.PlanType
	}
	return ""
}

func (m *PlanEntity) GetPlanCurrencyPrice() string {
	if m != nil {
		return m.PlanCurrencyPrice
	}
	return ""
}

func (m *PlanEntity) GetPlanMenu() string {
	if m != nil {
		return m.PlanMenu
	}
	return ""
}

func (m *PlanEntity) GetPlanDescriptionItems() string {
	if m != nil {
		return m.PlanDescriptionItems
	}
	return ""
}

func (m *PlanEntity) GetPlanDays() int32 {
	if m != nil {
		return m.PlanDays
	}
	return 0
}

func (m *PlanEntity) GetPlanOffices() int32 {
	if m != nil {
		return m.PlanOffices
	}
	return 0
}

func (m *PlanEntity) GetPlanUsers() int32 {
	if m != nil {
		return m.PlanUsers
	}
	return 0
}

func (m *PlanEntity) GetPlanTotalSales() int32 {
	if m != nil {
		return m.PlanTotalSales
	}
	return 0
}

func (m *PlanEntity) GetPlanPrice() float64 {
	if m != nil {
		return m.PlanPrice
	}
	return 0
}

func (m *PlanEntity) GetPlanFeatured() bool {
	if m != nil {
		return m.PlanFeatured
	}
	return false
}

func (m *PlanEntity) GetPlanCustom() bool {
	if m != nil {
		return m.PlanCustom
	}
	return false
}

func (m *PlanEntity) GetActivePlan() bool {
	if m != nil {
		return m.ActivePlan
	}
	return false
}

func (m *PlanEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PlanEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *PlanEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreatePlanReq struct {
	Data                 *PlanEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatePlanReq) Reset()         { *m = CreatePlanReq{} }
func (m *CreatePlanReq) String() string { return proto.CompactTextString(m) }
func (*CreatePlanReq) ProtoMessage()    {}
func (*CreatePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{1}
}

func (m *CreatePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanReq.Unmarshal(m, b)
}
func (m *CreatePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanReq.Marshal(b, m, deterministic)
}
func (m *CreatePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanReq.Merge(m, src)
}
func (m *CreatePlanReq) XXX_Size() int {
	return xxx_messageInfo_CreatePlanReq.Size(m)
}
func (m *CreatePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanReq proto.InternalMessageInfo

func (m *CreatePlanReq) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreatePlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatePlanRes) Reset()         { *m = CreatePlanRes{} }
func (m *CreatePlanRes) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRes) ProtoMessage()    {}
func (*CreatePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{2}
}

func (m *CreatePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRes.Unmarshal(m, b)
}
func (m *CreatePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRes.Marshal(b, m, deterministic)
}
func (m *CreatePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRes.Merge(m, src)
}
func (m *CreatePlanRes) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRes.Size(m)
}
func (m *CreatePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRes proto.InternalMessageInfo

func (m *CreatePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreatePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPlanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanReq) Reset()         { *m = GetPlanReq{} }
func (m *GetPlanReq) String() string { return proto.CompactTextString(m) }
func (*GetPlanReq) ProtoMessage()    {}
func (*GetPlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{3}
}

func (m *GetPlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanReq.Unmarshal(m, b)
}
func (m *GetPlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanReq.Marshal(b, m, deterministic)
}
func (m *GetPlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanReq.Merge(m, src)
}
func (m *GetPlanReq) XXX_Size() int {
	return xxx_messageInfo_GetPlanReq.Size(m)
}
func (m *GetPlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanReq proto.InternalMessageInfo

func (m *GetPlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPlanRes) Reset()         { *m = GetPlanRes{} }
func (m *GetPlanRes) String() string { return proto.CompactTextString(m) }
func (*GetPlanRes) ProtoMessage()    {}
func (*GetPlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{4}
}

func (m *GetPlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanRes.Unmarshal(m, b)
}
func (m *GetPlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanRes.Marshal(b, m, deterministic)
}
func (m *GetPlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanRes.Merge(m, src)
}
func (m *GetPlanRes) XXX_Size() int {
	return xxx_messageInfo_GetPlanRes.Size(m)
}
func (m *GetPlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanRes proto.InternalMessageInfo

func (m *GetPlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetPlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPlanCompanyReq struct {
	PlanIdCompany        string   `protobuf:"bytes,1,opt,name=plan_id_company,json=planIdCompany,proto3" json:"plan_id_company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanCompanyReq) Reset()         { *m = GetPlanCompanyReq{} }
func (m *GetPlanCompanyReq) String() string { return proto.CompactTextString(m) }
func (*GetPlanCompanyReq) ProtoMessage()    {}
func (*GetPlanCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{5}
}

func (m *GetPlanCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanCompanyReq.Unmarshal(m, b)
}
func (m *GetPlanCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanCompanyReq.Marshal(b, m, deterministic)
}
func (m *GetPlanCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanCompanyReq.Merge(m, src)
}
func (m *GetPlanCompanyReq) XXX_Size() int {
	return xxx_messageInfo_GetPlanCompanyReq.Size(m)
}
func (m *GetPlanCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanCompanyReq proto.InternalMessageInfo

func (m *GetPlanCompanyReq) GetPlanIdCompany() string {
	if m != nil {
		return m.PlanIdCompany
	}
	return ""
}

type GetPlanCompanyRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPlanCompanyRes) Reset()         { *m = GetPlanCompanyRes{} }
func (m *GetPlanCompanyRes) String() string { return proto.CompactTextString(m) }
func (*GetPlanCompanyRes) ProtoMessage()    {}
func (*GetPlanCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{6}
}

func (m *GetPlanCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanCompanyRes.Unmarshal(m, b)
}
func (m *GetPlanCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanCompanyRes.Marshal(b, m, deterministic)
}
func (m *GetPlanCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanCompanyRes.Merge(m, src)
}
func (m *GetPlanCompanyRes) XXX_Size() int {
	return xxx_messageInfo_GetPlanCompanyRes.Size(m)
}
func (m *GetPlanCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanCompanyRes proto.InternalMessageInfo

func (m *GetPlanCompanyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetPlanCompanyRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPlanCompanyRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListPlanReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlanReq) Reset()         { *m = ListPlanReq{} }
func (m *ListPlanReq) String() string { return proto.CompactTextString(m) }
func (*ListPlanReq) ProtoMessage()    {}
func (*ListPlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{7}
}

func (m *ListPlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanReq.Unmarshal(m, b)
}
func (m *ListPlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanReq.Marshal(b, m, deterministic)
}
func (m *ListPlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanReq.Merge(m, src)
}
func (m *ListPlanReq) XXX_Size() int {
	return xxx_messageInfo_ListPlanReq.Size(m)
}
func (m *ListPlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanReq proto.InternalMessageInfo

func (m *ListPlanReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPlanReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPlanReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListPlanRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*PlanEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64         `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPlanRes) Reset()         { *m = ListPlanRes{} }
func (m *ListPlanRes) String() string { return proto.CompactTextString(m) }
func (*ListPlanRes) ProtoMessage()    {}
func (*ListPlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{8}
}

func (m *ListPlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanRes.Unmarshal(m, b)
}
func (m *ListPlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanRes.Marshal(b, m, deterministic)
}
func (m *ListPlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanRes.Merge(m, src)
}
func (m *ListPlanRes) XXX_Size() int {
	return xxx_messageInfo_ListPlanRes.Size(m)
}
func (m *ListPlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanRes proto.InternalMessageInfo

func (m *ListPlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListPlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListPlanRes) GetData() []*PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListPlanRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdatePlanReq struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatePlanReq) Reset()         { *m = UpdatePlanReq{} }
func (m *UpdatePlanReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanReq) ProtoMessage()    {}
func (*UpdatePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{9}
}

func (m *UpdatePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanReq.Unmarshal(m, b)
}
func (m *UpdatePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanReq.Marshal(b, m, deterministic)
}
func (m *UpdatePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanReq.Merge(m, src)
}
func (m *UpdatePlanReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanReq.Size(m)
}
func (m *UpdatePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanReq proto.InternalMessageInfo

func (m *UpdatePlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePlanReq) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatePlanRes) Reset()         { *m = UpdatePlanRes{} }
func (m *UpdatePlanRes) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanRes) ProtoMessage()    {}
func (*UpdatePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{10}
}

func (m *UpdatePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanRes.Unmarshal(m, b)
}
func (m *UpdatePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanRes.Marshal(b, m, deterministic)
}
func (m *UpdatePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanRes.Merge(m, src)
}
func (m *UpdatePlanRes) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanRes.Size(m)
}
func (m *UpdatePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanRes proto.InternalMessageInfo

func (m *UpdatePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdatePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeletePlanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanReq) Reset()         { *m = DeletePlanReq{} }
func (m *DeletePlanReq) String() string { return proto.CompactTextString(m) }
func (*DeletePlanReq) ProtoMessage()    {}
func (*DeletePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{11}
}

func (m *DeletePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanReq.Unmarshal(m, b)
}
func (m *DeletePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanReq.Marshal(b, m, deterministic)
}
func (m *DeletePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanReq.Merge(m, src)
}
func (m *DeletePlanReq) XXX_Size() int {
	return xxx_messageInfo_DeletePlanReq.Size(m)
}
func (m *DeletePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanReq proto.InternalMessageInfo

func (m *DeletePlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlanRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanRes) Reset()         { *m = DeletePlanRes{} }
func (m *DeletePlanRes) String() string { return proto.CompactTextString(m) }
func (*DeletePlanRes) ProtoMessage()    {}
func (*DeletePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{12}
}

func (m *DeletePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanRes.Unmarshal(m, b)
}
func (m *DeletePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanRes.Marshal(b, m, deterministic)
}
func (m *DeletePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanRes.Merge(m, src)
}
func (m *DeletePlanRes) XXX_Size() int {
	return xxx_messageInfo_DeletePlanRes.Size(m)
}
func (m *DeletePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanRes proto.InternalMessageInfo

func (m *DeletePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeletePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteFeaturePlanReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId               string   `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeaturePlanReq) Reset()         { *m = DeleteFeaturePlanReq{} }
func (m *DeleteFeaturePlanReq) String() string { return proto.CompactTextString(m) }
func (*DeleteFeaturePlanReq) ProtoMessage()    {}
func (*DeleteFeaturePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{13}
}

func (m *DeleteFeaturePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeaturePlanReq.Unmarshal(m, b)
}
func (m *DeleteFeaturePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeaturePlanReq.Marshal(b, m, deterministic)
}
func (m *DeleteFeaturePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeaturePlanReq.Merge(m, src)
}
func (m *DeleteFeaturePlanReq) XXX_Size() int {
	return xxx_messageInfo_DeleteFeaturePlanReq.Size(m)
}
func (m *DeleteFeaturePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeaturePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeaturePlanReq proto.InternalMessageInfo

func (m *DeleteFeaturePlanReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteFeaturePlanReq) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type DeleteFeaturePlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteFeaturePlanRes) Reset()         { *m = DeleteFeaturePlanRes{} }
func (m *DeleteFeaturePlanRes) String() string { return proto.CompactTextString(m) }
func (*DeleteFeaturePlanRes) ProtoMessage()    {}
func (*DeleteFeaturePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{14}
}

func (m *DeleteFeaturePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeaturePlanRes.Unmarshal(m, b)
}
func (m *DeleteFeaturePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeaturePlanRes.Marshal(b, m, deterministic)
}
func (m *DeleteFeaturePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeaturePlanRes.Merge(m, src)
}
func (m *DeleteFeaturePlanRes) XXX_Size() int {
	return xxx_messageInfo_DeleteFeaturePlanRes.Size(m)
}
func (m *DeleteFeaturePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeaturePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeaturePlanRes proto.InternalMessageInfo

func (m *DeleteFeaturePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteFeaturePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteFeaturePlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PlanEntity)(nil), "plan.v1.PlanEntity")
	proto.RegisterType((*CreatePlanReq)(nil), "plan.v1.CreatePlanReq")
	proto.RegisterType((*CreatePlanRes)(nil), "plan.v1.CreatePlanRes")
	proto.RegisterType((*GetPlanReq)(nil), "plan.v1.GetPlanReq")
	proto.RegisterType((*GetPlanRes)(nil), "plan.v1.GetPlanRes")
	proto.RegisterType((*GetPlanCompanyReq)(nil), "plan.v1.GetPlanCompanyReq")
	proto.RegisterType((*GetPlanCompanyRes)(nil), "plan.v1.GetPlanCompanyRes")
	proto.RegisterType((*ListPlanReq)(nil), "plan.v1.ListPlanReq")
	proto.RegisterType((*ListPlanRes)(nil), "plan.v1.ListPlanRes")
	proto.RegisterType((*UpdatePlanReq)(nil), "plan.v1.UpdatePlanReq")
	proto.RegisterType((*UpdatePlanRes)(nil), "plan.v1.UpdatePlanRes")
	proto.RegisterType((*DeletePlanReq)(nil), "plan.v1.DeletePlanReq")
	proto.RegisterType((*DeletePlanRes)(nil), "plan.v1.DeletePlanRes")
	proto.RegisterType((*DeleteFeaturePlanReq)(nil), "plan.v1.DeleteFeaturePlanReq")
	proto.RegisterType((*DeleteFeaturePlanRes)(nil), "plan.v1.DeleteFeaturePlanRes")
}

func init() {
	proto.RegisterFile("plan/v1/plan.proto", fileDescriptor_59f392a4656940dd)
}

var fileDescriptor_59f392a4656940dd = []byte{
	// 1007 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x4e, 0xe4, 0x46,
	0x10, 0x95, 0x81, 0x61, 0xa0, 0x86, 0x81, 0x9d, 0x86, 0x65, 0x1d, 0x2f, 0x08, 0xe2, 0x95, 0x36,
	0x23, 0x24, 0xc6, 0x02, 0xf2, 0xb0, 0x49, 0x1e, 0x22, 0x02, 0xb9, 0xac, 0x94, 0xcd, 0xae, 0x06,
	0x50, 0xa4, 0x7d, 0xb1, 0x1a, 0xbb, 0x81, 0x96, 0x7c, 0x8b, 0xbb, 0x3d, 0x62, 0xb4, 0x42, 0x8a,
	0x92, 0x4f, 0xc8, 0x5f, 0xe4, 0x77, 0xf2, 0x0b, 0xf9, 0x90, 0xa8, 0xab, 0x7b, 0x6c, 0xcf, 0x85,
	0x25, 0x4a, 0xc4, 0x13, 0xd3, 0xa7, 0x4e, 0x9d, 0x2a, 0x97, 0xfb, 0x14, 0x06, 0x92, 0x45, 0x34,
	0xf1, 0x06, 0x07, 0x9e, 0xfa, 0xdb, 0xcb, 0xf2, 0x54, 0xa6, 0xa4, 0x89, 0xbf, 0x07, 0x07, 0xce,
	0xce, 0x75, 0x9a, 0x5e, 0x47, 0xcc, 0x43, 0xf8, 0xb2, 0xb8, 0xf2, 0x24, 0x8f, 0x99, 0x90, 0x34,
	0xce, 0x34, 0xd3, 0xd9, 0x32, 0x04, 0x9a, 0x71, 0x8f, 0x26, 0x49, 0x2a, 0xa9, 0xe4, 0x69, 0x22,
	0x74, 0xd4, 0xfd, 0xbd, 0x09, 0xf0, 0x2e, 0xa2, 0xc9, 0xb7, 0x89, 0xe4, 0x72, 0x48, 0x56, 0x61,
	0x8e, 0x87, 0xb6, 0xb5, 0x6b, 0x75, 0x97, 0xfb, 0x73, 0x3c, 0x24, 0x2f, 0x61, 0x4d, 0x15, 0xf2,
	0x79, 0xe8, 0x07, 0x69, 0x9c, 0xd1, 0x64, 0x68, 0xcf, 0x61, 0xb0, 0xad, 0xe0, 0xd7, 0xe1, 0x89,
	0x06, 0xc9, 0x1e, 0x74, 0x90, 0x47, 0x83, 0x80, 0x25, 0xd2, 0x0f, 0xd2, 0x28, 0xcd, 0xed, 0x79,
	0x64, 0xa2, 0xc0, 0x31, 0xe2, 0x27, 0x0a, 0x26, 0x47, 0xb0, 0x59, 0xe7, 0x4a, 0x76, 0x3b, 0x4a,
	0x58, 0xc0, 0x84, 0xf5, 0x2a, 0xe1, 0x9c, 0xdd, 0x9a, 0xa4, 0x6d, 0x00, 0x4c, 0x92, 0x5c, 0x46,
	0xcc, 0x6e, 0x20, 0x71, 0x59, 0x21, 0xe7, 0x0a, 0x20, 0x2f, 0x00, 0x1b, 0xf2, 0x45, 0x71, 0xa9,
	0x19, 0x8b, 0xc8, 0x58, 0x51, 0xe0, 0x99, 0xc1, 0xc8, 0x2b, 0xb0, 0x91, 0x14, 0x32, 0x11, 0xe4,
	0x3c, 0x53, 0x63, 0xf0, 0x25, 0x4f, 0x86, 0x71, 0xc0, 0xec, 0x26, 0xf2, 0xb1, 0xb1, 0xd3, 0x2a,
	0x7c, 0xae, 0xa3, 0xe4, 0x39, 0x2c, 0xeb, 0xea, 0xc3, 0x8c, 0xd9, 0x4b, 0x48, 0x5d, 0xc2, 0xe2,
	0xc3, 0x8c, 0x91, 0x1e, 0x60, 0xc7, 0x7e, 0x50, 0xe4, 0x39, 0x4b, 0x82, 0xa1, 0x9f, 0xe5, 0x3c,
	0x60, 0xf6, 0x32, 0xd2, 0x70, 0x2c, 0x27, 0x26, 0xf2, 0x4e, 0x05, 0x4a, 0xb1, 0x98, 0x25, 0x85,
	0x0d, 0x95, 0xd8, 0x1b, 0x96, 0x14, 0xe4, 0x73, 0x33, 0x9c, 0x7a, 0x8f, 0x5c, 0xb2, 0x58, 0xd8,
	0x2d, 0x64, 0x6e, 0x4c, 0x74, 0xf8, 0x5a, 0xc5, 0x4a, 0xc9, 0x90, 0x0e, 0x85, 0xbd, 0xb2, 0x6b,
	0x75, 0x1b, 0x5a, 0xf2, 0x94, 0x0e, 0x05, 0xf9, 0x14, 0x70, 0x0c, 0x7e, 0x7a, 0x75, 0xc5, 0x03,
	0x26, 0xec, 0x36, 0xc6, 0x5b, 0x0a, 0x7b, 0xab, 0xa1, 0x72, 0xba, 0x85, 0x60, 0xb9, 0xb0, 0x57,
	0x91, 0x80, 0x8a, 0x17, 0x0a, 0x20, 0x5d, 0x78, 0xa2, 0x1f, 0x3f, 0x95, 0x34, 0xf2, 0x05, 0x8d,
	0x98, 0xb0, 0xd7, 0x90, 0xb4, 0x8a, 0x53, 0x50, 0xf0, 0x99, 0x42, 0x4b, 0x21, 0x3d, 0x82, 0x27,
	0xbb, 0x56, 0xd7, 0xd2, 0x42, 0xfa, 0xd1, 0x47, 0xaf, 0xe9, 0x8a, 0x51, 0x59, 0xe4, 0x2c, 0xb4,
	0x3b, 0xbb, 0x56, 0x77, 0x49, 0xbf, 0xa6, 0xef, 0x0c, 0x46, 0x76, 0xa0, 0x65, 0xe6, 0x29, 0x64,
	0x1a, 0xdb, 0x04, 0x29, 0xa0, 0xe7, 0xa8, 0x10, 0x45, 0xa0, 0x81, 0xe4, 0x03, 0xe6, 0x2b, 0xd0,
	0x5e, 0xd7, 0x04, 0x0d, 0xa9, 0xbb, 0x4c, 0xbe, 0x00, 0x08, 0x72, 0x46, 0x25, 0x0b, 0x7d, 0x2a,
	0xed, 0x8d, 0x5d, 0xab, 0xdb, 0x3a, 0x74, 0x7a, 0xda, 0x07, 0xbd, 0x91, 0x51, 0x7a, 0xe7, 0x23,
	0xa3, 0xf4, 0x97, 0x0d, 0xfb, 0x58, 0xaa, 0xd4, 0x22, 0x0b, 0x47, 0xa9, 0x4f, 0x1f, 0x4e, 0x35,
	0x6c, 0x9d, 0x1a, 0xb2, 0x88, 0x99, 0xd4, 0xcd, 0x87, 0x53, 0x0d, 0xfb, 0x58, 0xba, 0xaf, 0xa0,
	0x7d, 0x82, 0x2d, 0xa8, 0xf6, 0xfb, 0xec, 0x17, 0xf2, 0x19, 0x2c, 0x84, 0x54, 0x52, 0x74, 0x62,
	0xeb, 0x70, 0xbd, 0x67, 0xdc, 0xde, 0xab, 0xac, 0xda, 0x47, 0x82, 0x1b, 0x8d, 0x67, 0x0a, 0x62,
	0x43, 0x53, 0x14, 0x41, 0xc0, 0x84, 0xc0, 0xe4, 0xa5, 0xfe, 0xe8, 0xa8, 0x22, 0x31, 0x13, 0x82,
	0x5e, 0x33, 0xe3, 0xe1, 0xd1, 0xb1, 0xac, 0x36, 0xff, 0x50, 0xb5, 0x2d, 0x80, 0xef, 0x99, 0x1c,
	0x35, 0x39, 0xb1, 0x2c, 0x5c, 0x5e, 0x8b, 0x3e, 0x72, 0x23, 0x5f, 0x41, 0xc7, 0x94, 0x32, 0x1b,
	0x48, 0xf5, 0x33, 0x63, 0x59, 0x59, 0x33, 0x96, 0x95, 0x9b, 0x4d, 0x27, 0x3f, 0x72, 0xbb, 0x6f,
	0xa1, 0xf5, 0x23, 0x17, 0xe5, 0xe0, 0x08, 0x2c, 0x64, 0x4a, 0xce, 0x42, 0x0f, 0xe1, 0x6f, 0xb2,
	0x01, 0x8d, 0x88, 0xc7, 0x5c, 0x62, 0x8d, 0x46, 0x5f, 0x1f, 0xc8, 0x26, 0x2c, 0x0a, 0x46, 0xf3,
	0xe0, 0xc6, 0x2c, 0x53, 0x73, 0x72, 0x7f, 0xb5, 0xea, 0x8a, 0xff, 0xb7, 0xfb, 0xf9, 0x8f, 0x76,
	0xaf, 0x5a, 0x43, 0xe7, 0xe3, 0x7e, 0x9e, 0xef, 0xeb, 0x83, 0xfb, 0x03, 0xb4, 0x2f, 0xf0, 0xee,
	0xdf, 0x73, 0x1d, 0x4a, 0xfd, 0xb9, 0x7f, 0x71, 0x87, 0xeb, 0x4a, 0x8f, 0xfc, 0x2e, 0x76, 0xa0,
	0x7d, 0x8a, 0xc6, 0xbb, 0xef, 0x1a, 0x9f, 0x8c, 0x13, 0xfe, 0x53, 0x3b, 0xee, 0xd7, 0xb0, 0xa1,
	0x45, 0xcc, 0x5a, 0x9b, 0x2e, 0xd6, 0xc0, 0x21, 0x3d, 0x83, 0xa6, 0xb9, 0xb3, 0x46, 0x61, 0x51,
	0xdf, 0x55, 0x57, 0xcc, 0x14, 0x78, 0xdc, 0xd9, 0x1c, 0xfe, 0xd9, 0x80, 0x96, 0x02, 0xcf, 0x58,
	0x3e, 0x50, 0xfb, 0xfa, 0x02, 0xa0, 0xda, 0x2e, 0x64, 0xb3, 0x4c, 0x1c, 0x5b, 0x56, 0xce, 0x6c,
	0x5c, 0xb8, 0xcf, 0x7e, 0xfb, 0xeb, 0xef, 0x3f, 0xe6, 0x3a, 0xee, 0x0a, 0x7e, 0x7b, 0x98, 0xef,
	0x97, 0x2f, 0xad, 0x3d, 0xf2, 0x13, 0x34, 0x8d, 0x01, 0x49, 0xd5, 0x4c, 0xb5, 0x58, 0x9c, 0x19,
	0xa0, 0x70, 0x3f, 0x41, 0xb5, 0x75, 0xd2, 0xa9, 0xab, 0x79, 0x1f, 0x78, 0x78, 0x47, 0x6e, 0x61,
	0x75, 0xdc, 0xd0, 0xc4, 0x99, 0x54, 0xa8, 0xd6, 0x84, 0x73, 0x7f, 0x4c, 0xb8, 0x3d, 0x2c, 0xd2,
	0x25, 0x2f, 0xc7, 0x8a, 0x98, 0x6d, 0xe2, 0x7d, 0x98, 0x58, 0x2f, 0x77, 0xe4, 0x0d, 0x2c, 0x8d,
	0x6c, 0x48, 0x36, 0x4a, 0xdd, 0x9a, 0xd7, 0x9d, 0x59, 0xa8, 0x70, 0x9f, 0x62, 0x9d, 0x35, 0xd2,
	0xae, 0xd7, 0x11, 0xe4, 0x3d, 0x40, 0xe5, 0x84, 0xda, 0xbc, 0xc7, 0x8c, 0xe6, 0xcc, 0xc6, 0x85,
	0xbb, 0x85, 0xa2, 0x9b, 0xce, 0xf4, 0x84, 0xd4, 0xd0, 0x7f, 0x06, 0xa8, 0xae, 0x75, 0x4d, 0x7b,
	0xcc, 0x0c, 0xce, 0x6c, 0xbc, 0x9c, 0xfe, 0xde, 0x8c, 0xe9, 0x0f, 0xa0, 0x33, 0x75, 0x53, 0xc9,
	0xf6, 0x84, 0xce, 0xb8, 0x0d, 0x9c, 0x8f, 0x86, 0x85, 0xfb, 0x02, 0xab, 0x6d, 0xef, 0x3d, 0x9f,
	0xaa, 0x56, 0xbe, 0x83, 0xbb, 0x6f, 0x8e, 0xde, 0x1f, 0x5c, 0x73, 0x79, 0x53, 0x5c, 0xf6, 0x82,
	0x34, 0xf6, 0xce, 0x4e, 0x8f, 0xcf, 0x8f, 0xf7, 0xd5, 0xc7, 0x62, 0x7c, 0xc9, 0xa9, 0x27, 0x6e,
	0x68, 0xce, 0xc2, 0xfd, 0xeb, 0x74, 0x1f, 0xff, 0xf3, 0x7a, 0xe6, 0x13, 0xfa, 0x72, 0x11, 0x8f,
	0x47, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x14, 0xed, 0xf0, 0x54, 0x0b, 0x00, 0x00,
}
