// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: plan/v1/plan.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlanService_CreatePlan_FullMethodName        = "/plan.v1.PlanService/CreatePlan"
	PlanService_GetPlan_FullMethodName           = "/plan.v1.PlanService/GetPlan"
	PlanService_GetPlanCompany_FullMethodName    = "/plan.v1.PlanService/GetPlanCompany"
	PlanService_ListPlan_FullMethodName          = "/plan.v1.PlanService/ListPlan"
	PlanService_UpdatePlan_FullMethodName        = "/plan.v1.PlanService/UpdatePlan"
	PlanService_DeletePlan_FullMethodName        = "/plan.v1.PlanService/DeletePlan"
	PlanService_DeleteFeaturePlan_FullMethodName = "/plan.v1.PlanService/DeleteFeaturePlan"
)

// PlanServiceClient is the client API for PlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanServiceClient interface {
	CreatePlan(ctx context.Context, in *CreatePlanReq, opts ...grpc.CallOption) (*CreatePlanRes, error)
	GetPlan(ctx context.Context, in *GetPlanReq, opts ...grpc.CallOption) (*GetPlanRes, error)
	GetPlanCompany(ctx context.Context, in *GetPlanCompanyReq, opts ...grpc.CallOption) (*GetPlanCompanyRes, error)
	ListPlan(ctx context.Context, in *ListPlanReq, opts ...grpc.CallOption) (*ListPlanRes, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanReq, opts ...grpc.CallOption) (*UpdatePlanRes, error)
	DeletePlan(ctx context.Context, in *DeletePlanReq, opts ...grpc.CallOption) (*DeletePlanRes, error)
	DeleteFeaturePlan(ctx context.Context, in *DeleteFeaturePlanReq, opts ...grpc.CallOption) (*DeleteFeaturePlanRes, error)
}

type planServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanServiceClient(cc grpc.ClientConnInterface) PlanServiceClient {
	return &planServiceClient{cc}
}

func (c *planServiceClient) CreatePlan(ctx context.Context, in *CreatePlanReq, opts ...grpc.CallOption) (*CreatePlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanRes)
	err := c.cc.Invoke(ctx, PlanService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetPlan(ctx context.Context, in *GetPlanReq, opts ...grpc.CallOption) (*GetPlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanRes)
	err := c.cc.Invoke(ctx, PlanService_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetPlanCompany(ctx context.Context, in *GetPlanCompanyReq, opts ...grpc.CallOption) (*GetPlanCompanyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanCompanyRes)
	err := c.cc.Invoke(ctx, PlanService_GetPlanCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) ListPlan(ctx context.Context, in *ListPlanReq, opts ...grpc.CallOption) (*ListPlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlanRes)
	err := c.cc.Invoke(ctx, PlanService_ListPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) UpdatePlan(ctx context.Context, in *UpdatePlanReq, opts ...grpc.CallOption) (*UpdatePlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlanRes)
	err := c.cc.Invoke(ctx, PlanService_UpdatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeletePlan(ctx context.Context, in *DeletePlanReq, opts ...grpc.CallOption) (*DeletePlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlanRes)
	err := c.cc.Invoke(ctx, PlanService_DeletePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeleteFeaturePlan(ctx context.Context, in *DeleteFeaturePlanReq, opts ...grpc.CallOption) (*DeleteFeaturePlanRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeaturePlanRes)
	err := c.cc.Invoke(ctx, PlanService_DeleteFeaturePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanServiceServer is the server API for PlanService service.
// All implementations must embed UnimplementedPlanServiceServer
// for forward compatibility.
type PlanServiceServer interface {
	CreatePlan(context.Context, *CreatePlanReq) (*CreatePlanRes, error)
	GetPlan(context.Context, *GetPlanReq) (*GetPlanRes, error)
	GetPlanCompany(context.Context, *GetPlanCompanyReq) (*GetPlanCompanyRes, error)
	ListPlan(context.Context, *ListPlanReq) (*ListPlanRes, error)
	UpdatePlan(context.Context, *UpdatePlanReq) (*UpdatePlanRes, error)
	DeletePlan(context.Context, *DeletePlanReq) (*DeletePlanRes, error)
	DeleteFeaturePlan(context.Context, *DeleteFeaturePlanReq) (*DeleteFeaturePlanRes, error)
	mustEmbedUnimplementedPlanServiceServer()
}

// UnimplementedPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanServiceServer struct{}

func (UnimplementedPlanServiceServer) CreatePlan(context.Context, *CreatePlanReq) (*CreatePlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedPlanServiceServer) GetPlan(context.Context, *GetPlanReq) (*GetPlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedPlanServiceServer) GetPlanCompany(context.Context, *GetPlanCompanyReq) (*GetPlanCompanyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanCompany not implemented")
}
func (UnimplementedPlanServiceServer) ListPlan(context.Context, *ListPlanReq) (*ListPlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlan not implemented")
}
func (UnimplementedPlanServiceServer) UpdatePlan(context.Context, *UpdatePlanReq) (*UpdatePlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (UnimplementedPlanServiceServer) DeletePlan(context.Context, *DeletePlanReq) (*DeletePlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlan not implemented")
}
func (UnimplementedPlanServiceServer) DeleteFeaturePlan(context.Context, *DeleteFeaturePlanReq) (*DeleteFeaturePlanRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeaturePlan not implemented")
}
func (UnimplementedPlanServiceServer) mustEmbedUnimplementedPlanServiceServer() {}
func (UnimplementedPlanServiceServer) testEmbeddedByValue()                     {}

// UnsafePlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanServiceServer will
// result in compilation errors.
type UnsafePlanServiceServer interface {
	mustEmbedUnimplementedPlanServiceServer()
}

func RegisterPlanServiceServer(s grpc.ServiceRegistrar, srv PlanServiceServer) {
	// If the following call panics, it indicates UnimplementedPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanService_ServiceDesc, srv)
}

func _PlanService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CreatePlan(ctx, req.(*CreatePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlan(ctx, req.(*GetPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetPlanCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetPlanCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetPlanCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetPlanCompany(ctx, req.(*GetPlanCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_ListPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).ListPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_ListPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).ListPlan(ctx, req.(*ListPlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_UpdatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).UpdatePlan(ctx, req.(*UpdatePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_DeletePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).DeletePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_DeletePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).DeletePlan(ctx, req.(*DeletePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_DeleteFeaturePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeaturePlanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).DeleteFeaturePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_DeleteFeaturePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).DeleteFeaturePlan(ctx, req.(*DeleteFeaturePlanReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanService_ServiceDesc is the grpc.ServiceDesc for PlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plan.v1.PlanService",
	HandlerType: (*PlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _PlanService_CreatePlan_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _PlanService_GetPlan_Handler,
		},
		{
			MethodName: "GetPlanCompany",
			Handler:    _PlanService_GetPlanCompany_Handler,
		},
		{
			MethodName: "ListPlan",
			Handler:    _PlanService_ListPlan_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _PlanService_UpdatePlan_Handler,
		},
		{
			MethodName: "DeletePlan",
			Handler:    _PlanService_DeletePlan_Handler,
		},
		{
			MethodName: "DeleteFeaturePlan",
			Handler:    _PlanService_DeleteFeaturePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plan/v1/plan.proto",
}
