syntax = "proto3";

package plan.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/SDATA-Colombia/shared-go-proto/plan/v1";

// -------------------------------------------------------------------
// Plan Entity message
// -------------------------------------------------------------------

message PlanEntity {
  string id = 1;
  string plan_id_company = 2;
  string plan_accent_color = 3;
  string plan_accent_text_color = 4;
  string plan_title = 5;
  string plan_subtitle = 6;
  string plan_description_tinymce = 7;
  string plan_type = 8;
  string plan_currency_price = 9;
  string plan_menu = 10;
  string plan_description_items = 11;
  
  int32 plan_days = 12;
  int32 plan_offices = 13;
  int32 plan_users = 14;
  int32 plan_total_sales = 15;
  
  double plan_price = 16;
  
  bool plan_featured = 17;
  bool plan_custom = 18;
  bool active_plan = 19;

  google.protobuf.Timestamp created_at = 20;
  google.protobuf.Timestamp updated_at = 21;
  google.protobuf.Timestamp deleted_at = 22;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreatePlan
// -------------------------------------------------------------------

message CreatePlanReq {
  PlanEntity data = 1;
}

message CreatePlanRes {
  bool success = 1;
  string message = 2;
  PlanEntity data = 3;
}

// -------------------------------------------------------------------
// GetPlan
// -------------------------------------------------------------------

message GetPlanReq {
  string id = 1;
}

message GetPlanRes {
  bool success = 1;
  string message = 2;
  PlanEntity data = 3;
}

// -------------------------------------------------------------------
// GetPlanCompany
// -------------------------------------------------------------------

message GetPlanCompanyReq {
  string plan_id_company = 1;
}

message GetPlanCompanyRes {
  bool success = 1;
  string message = 2;
  PlanEntity data = 3;
}

// -------------------------------------------------------------------
// ListPlan
// -------------------------------------------------------------------

message ListPlanReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListPlanRes {
  bool success = 1;
  string message = 2;
  repeated PlanEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdatePlan
// -------------------------------------------------------------------

message UpdatePlanReq {
  string id = 1;
  PlanEntity data = 2;
}

message UpdatePlanRes {
  bool success = 1;
  string message = 2;
  PlanEntity data = 3;
}

// -------------------------------------------------------------------
// DeletePlan
// -------------------------------------------------------------------

message DeletePlanReq {
  string id = 1;
}

message DeletePlanRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// DeleteFeaturePlan
// -------------------------------------------------------------------

message DeleteFeaturePlanReq {
  string id = 1;
  string plan_id = 2;
}

message DeleteFeaturePlanRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service PlanService {

  rpc CreatePlan(CreatePlanReq) returns (CreatePlanRes) {
    option (google.api.http) = {
      post: "/api/v1/plan"
      body: "*"
    };
  }

  rpc GetPlan(GetPlanReq) returns (GetPlanRes) {
    option (google.api.http) = {
      get: "/api/v1/plan/{id}"
    };
  }

  rpc GetPlanCompany(GetPlanCompanyReq) returns (GetPlanCompanyRes) {
    option (google.api.http) = {
      get: "/api/v1/plan/company/{plan_id_company}"
    };
  }

  rpc ListPlan(ListPlanReq) returns (ListPlanRes) {
    option (google.api.http) = {
      get: "/api/v1/plans"
    };
  }

  rpc UpdatePlan(UpdatePlanReq) returns (UpdatePlanRes) {
    option (google.api.http) = {
      put: "/api/v1/plan/{id}"
      body: "*"
    };
  }

  rpc DeletePlan(DeletePlanReq) returns (DeletePlanRes) {
    option (google.api.http) = {
      delete: "/api/v1/plan/{id}"
    };
  }

  rpc DeleteFeaturePlan(DeleteFeaturePlanReq) returns (DeleteFeaturePlanRes) {
    option (google.api.http) = {
      delete: "/api/v1/plan/{id}/{plan_id}"
    };
  }

}
