// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plan/v1/plan.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PlanEntity) Reset()         { *m = PlanEntity{} }
func (m *PlanEntity) String() string { return proto.CompactTextString(m) }
func (*PlanEntity) ProtoMessage()    {}
func (*PlanEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{0}
}

func (m *PlanEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanEntity.Unmarshal(m, b)
}
func (m *PlanEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanEntity.Marshal(b, m, deterministic)
}
func (m *PlanEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanEntity.Merge(m, src)
}
func (m *PlanEntity) XXX_Size() int {
	return xxx_messageInfo_PlanEntity.Size(m)
}
func (m *PlanEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanEntity.DiscardUnknown(m)
}

var xxx_messageInfo_PlanEntity proto.InternalMessageInfo

func (m *PlanEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlanEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlanEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PlanEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PlanEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PlanEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PlanEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PlanEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PlanEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *PlanEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PlanEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *PlanEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PlanEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *PlanEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreatePlanReq struct {
	Data                 *PlanEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatePlanReq) Reset()         { *m = CreatePlanReq{} }
func (m *CreatePlanReq) String() string { return proto.CompactTextString(m) }
func (*CreatePlanReq) ProtoMessage()    {}
func (*CreatePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{1}
}

func (m *CreatePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanReq.Unmarshal(m, b)
}
func (m *CreatePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanReq.Marshal(b, m, deterministic)
}
func (m *CreatePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanReq.Merge(m, src)
}
func (m *CreatePlanReq) XXX_Size() int {
	return xxx_messageInfo_CreatePlanReq.Size(m)
}
func (m *CreatePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanReq proto.InternalMessageInfo

func (m *CreatePlanReq) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreatePlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatePlanRes) Reset()         { *m = CreatePlanRes{} }
func (m *CreatePlanRes) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRes) ProtoMessage()    {}
func (*CreatePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{2}
}

func (m *CreatePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRes.Unmarshal(m, b)
}
func (m *CreatePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRes.Marshal(b, m, deterministic)
}
func (m *CreatePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRes.Merge(m, src)
}
func (m *CreatePlanRes) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRes.Size(m)
}
func (m *CreatePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRes proto.InternalMessageInfo

func (m *CreatePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreatePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPlanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanReq) Reset()         { *m = GetPlanReq{} }
func (m *GetPlanReq) String() string { return proto.CompactTextString(m) }
func (*GetPlanReq) ProtoMessage()    {}
func (*GetPlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{3}
}

func (m *GetPlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanReq.Unmarshal(m, b)
}
func (m *GetPlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanReq.Marshal(b, m, deterministic)
}
func (m *GetPlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanReq.Merge(m, src)
}
func (m *GetPlanReq) XXX_Size() int {
	return xxx_messageInfo_GetPlanReq.Size(m)
}
func (m *GetPlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanReq proto.InternalMessageInfo

func (m *GetPlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPlanRes) Reset()         { *m = GetPlanRes{} }
func (m *GetPlanRes) String() string { return proto.CompactTextString(m) }
func (*GetPlanRes) ProtoMessage()    {}
func (*GetPlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{4}
}

func (m *GetPlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanRes.Unmarshal(m, b)
}
func (m *GetPlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanRes.Marshal(b, m, deterministic)
}
func (m *GetPlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanRes.Merge(m, src)
}
func (m *GetPlanRes) XXX_Size() int {
	return xxx_messageInfo_GetPlanRes.Size(m)
}
func (m *GetPlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanRes proto.InternalMessageInfo

func (m *GetPlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetPlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListPlanReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlanReq) Reset()         { *m = ListPlanReq{} }
func (m *ListPlanReq) String() string { return proto.CompactTextString(m) }
func (*ListPlanReq) ProtoMessage()    {}
func (*ListPlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{5}
}

func (m *ListPlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanReq.Unmarshal(m, b)
}
func (m *ListPlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanReq.Marshal(b, m, deterministic)
}
func (m *ListPlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanReq.Merge(m, src)
}
func (m *ListPlanReq) XXX_Size() int {
	return xxx_messageInfo_ListPlanReq.Size(m)
}
func (m *ListPlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanReq proto.InternalMessageInfo

func (m *ListPlanReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPlanReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPlanReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListPlanRes struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*PlanEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64         `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPlanRes) Reset()         { *m = ListPlanRes{} }
func (m *ListPlanRes) String() string { return proto.CompactTextString(m) }
func (*ListPlanRes) ProtoMessage()    {}
func (*ListPlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{6}
}

func (m *ListPlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanRes.Unmarshal(m, b)
}
func (m *ListPlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanRes.Marshal(b, m, deterministic)
}
func (m *ListPlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanRes.Merge(m, src)
}
func (m *ListPlanRes) XXX_Size() int {
	return xxx_messageInfo_ListPlanRes.Size(m)
}
func (m *ListPlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanRes proto.InternalMessageInfo

func (m *ListPlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListPlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListPlanRes) GetData() []*PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListPlanRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdatePlanReq struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatePlanReq) Reset()         { *m = UpdatePlanReq{} }
func (m *UpdatePlanReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanReq) ProtoMessage()    {}
func (*UpdatePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{7}
}

func (m *UpdatePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanReq.Unmarshal(m, b)
}
func (m *UpdatePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanReq.Marshal(b, m, deterministic)
}
func (m *UpdatePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanReq.Merge(m, src)
}
func (m *UpdatePlanReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanReq.Size(m)
}
func (m *UpdatePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanReq proto.InternalMessageInfo

func (m *UpdatePlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePlanReq) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePlanRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *PlanEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatePlanRes) Reset()         { *m = UpdatePlanRes{} }
func (m *UpdatePlanRes) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanRes) ProtoMessage()    {}
func (*UpdatePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{8}
}

func (m *UpdatePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanRes.Unmarshal(m, b)
}
func (m *UpdatePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanRes.Marshal(b, m, deterministic)
}
func (m *UpdatePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanRes.Merge(m, src)
}
func (m *UpdatePlanRes) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanRes.Size(m)
}
func (m *UpdatePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanRes proto.InternalMessageInfo

func (m *UpdatePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdatePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePlanRes) GetData() *PlanEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeletePlanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanReq) Reset()         { *m = DeletePlanReq{} }
func (m *DeletePlanReq) String() string { return proto.CompactTextString(m) }
func (*DeletePlanReq) ProtoMessage()    {}
func (*DeletePlanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{9}
}

func (m *DeletePlanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanReq.Unmarshal(m, b)
}
func (m *DeletePlanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanReq.Marshal(b, m, deterministic)
}
func (m *DeletePlanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanReq.Merge(m, src)
}
func (m *DeletePlanReq) XXX_Size() int {
	return xxx_messageInfo_DeletePlanReq.Size(m)
}
func (m *DeletePlanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanReq proto.InternalMessageInfo

func (m *DeletePlanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlanRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanRes) Reset()         { *m = DeletePlanRes{} }
func (m *DeletePlanRes) String() string { return proto.CompactTextString(m) }
func (*DeletePlanRes) ProtoMessage()    {}
func (*DeletePlanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f392a4656940dd, []int{10}
}

func (m *DeletePlanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanRes.Unmarshal(m, b)
}
func (m *DeletePlanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanRes.Marshal(b, m, deterministic)
}
func (m *DeletePlanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanRes.Merge(m, src)
}
func (m *DeletePlanRes) XXX_Size() int {
	return xxx_messageInfo_DeletePlanRes.Size(m)
}
func (m *DeletePlanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanRes proto.InternalMessageInfo

func (m *DeletePlanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeletePlanRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PlanEntity)(nil), "plan.v1.PlanEntity")
	proto.RegisterMapType((map[string]string)(nil), "plan.v1.PlanEntity.MetadataEntry")
	proto.RegisterType((*CreatePlanReq)(nil), "plan.v1.CreatePlanReq")
	proto.RegisterType((*CreatePlanRes)(nil), "plan.v1.CreatePlanRes")
	proto.RegisterType((*GetPlanReq)(nil), "plan.v1.GetPlanReq")
	proto.RegisterType((*GetPlanRes)(nil), "plan.v1.GetPlanRes")
	proto.RegisterType((*ListPlanReq)(nil), "plan.v1.ListPlanReq")
	proto.RegisterType((*ListPlanRes)(nil), "plan.v1.ListPlanRes")
	proto.RegisterType((*UpdatePlanReq)(nil), "plan.v1.UpdatePlanReq")
	proto.RegisterType((*UpdatePlanRes)(nil), "plan.v1.UpdatePlanRes")
	proto.RegisterType((*DeletePlanReq)(nil), "plan.v1.DeletePlanReq")
	proto.RegisterType((*DeletePlanRes)(nil), "plan.v1.DeletePlanRes")
}

func init() {
	proto.RegisterFile("plan/v1/plan.proto", fileDescriptor_59f392a4656940dd)
}

var fileDescriptor_59f392a4656940dd = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xe3, 0xa4, 0x49, 0x27, 0x4d, 0x75, 0xba, 0xad, 0x7a, 0x7c, 0xac, 0x1e, 0xd5, 0xc7,
	0x37, 0xc7, 0xaa, 0x54, 0x9b, 0x96, 0x9b, 0x52, 0xc4, 0x45, 0x5b, 0x2a, 0xb8, 0x28, 0x14, 0xb9,
	0x54, 0x48, 0xbd, 0x41, 0x1b, 0x7b, 0x49, 0xad, 0xfa, 0x0f, 0xef, 0x3a, 0x52, 0x84, 0x90, 0x10,
	0xaf, 0xc0, 0x1b, 0xf0, 0x12, 0x3c, 0x08, 0xaf, 0xc0, 0x83, 0xa0, 0x5d, 0xaf, 0xff, 0x68, 0x4a,
	0x11, 0xa8, 0x57, 0xd9, 0x99, 0x9d, 0x6f, 0xfc, 0xcd, 0xcc, 0x37, 0x1b, 0x40, 0x69, 0x88, 0x63,
	0x67, 0xba, 0xe3, 0xf0, 0x5f, 0x3b, 0xcd, 0x12, 0x96, 0xa0, 0xbe, 0x38, 0x4f, 0x77, 0xf4, 0xcd,
	0x49, 0x92, 0x4c, 0x42, 0xe2, 0x08, 0xf7, 0x38, 0x7f, 0xe3, 0xb0, 0x20, 0x22, 0x94, 0xe1, 0x28,
	0x2d, 0x22, 0xf5, 0x0d, 0x19, 0x80, 0xd3, 0xc0, 0xc1, 0x71, 0x9c, 0x30, 0xcc, 0x82, 0x24, 0xa6,
	0xc5, 0xad, 0xf9, 0xb9, 0x0b, 0xf0, 0x22, 0xc4, 0xf1, 0x71, 0xcc, 0x02, 0x36, 0x43, 0xcb, 0xd0,
	0x09, 0x7c, 0x4d, 0x31, 0x14, 0x6b, 0xd1, 0xed, 0x04, 0x3e, 0x42, 0xd0, 0x8d, 0x71, 0x44, 0xb4,
	0x8e, 0xf0, 0x88, 0x33, 0x32, 0x60, 0xe8, 0x13, 0xea, 0x65, 0x41, 0xca, 0x13, 0x69, 0xaa, 0xb8,
	0x6a, 0xba, 0xd0, 0x3a, 0x2c, 0x50, 0x86, 0x59, 0x4e, 0xb5, 0xae, 0xa1, 0x58, 0x03, 0x57, 0x5a,
	0xe8, 0x2f, 0x50, 0xf1, 0x84, 0x68, 0x3d, 0x43, 0xb1, 0x7a, 0x2e, 0x3f, 0xa2, 0x35, 0xe8, 0xb1,
	0x84, 0xe1, 0x50, 0x5b, 0x30, 0x14, 0x4b, 0x75, 0x0b, 0x83, 0x7b, 0xd3, 0x2c, 0xf0, 0x88, 0xd6,
	0x37, 0x14, 0x4b, 0x71, 0x0b, 0x83, 0x73, 0x61, 0x78, 0x42, 0xb5, 0x81, 0xa1, 0x72, 0x2e, 0xfc,
	0x8c, 0x34, 0xe8, 0xc7, 0x79, 0x34, 0x26, 0x19, 0xd5, 0x16, 0x0d, 0xd5, 0xea, 0xb9, 0xa5, 0x89,
	0x1e, 0xc1, 0x20, 0x22, 0x0c, 0xfb, 0x98, 0x61, 0x0d, 0x0c, 0xd5, 0x1a, 0xee, 0xfe, 0x67, 0xcb,
	0x9e, 0xd9, 0x75, 0xc1, 0xf6, 0x33, 0x19, 0x73, 0x1c, 0xb3, 0x6c, 0xe6, 0x56, 0x10, 0xf4, 0x2f,
	0x80, 0x97, 0x11, 0xcc, 0x88, 0xff, 0x7a, 0x3c, 0xd3, 0x86, 0xa2, 0xc6, 0x45, 0xe9, 0x39, 0x9c,
	0xa1, 0x07, 0xf5, 0x35, 0x66, 0xda, 0x92, 0xa1, 0x58, 0xc3, 0x5d, 0xdd, 0x2e, 0x3a, 0x6d, 0x97,
	0xa3, 0xb0, 0x5f, 0x96, 0xa3, 0xa8, 0xa0, 0x07, 0x8c, 0x43, 0xf3, 0xd4, 0x2f, 0xa1, 0xa3, 0xdb,
	0xa1, 0x32, 0xba, 0x80, 0xfa, 0x24, 0x24, 0x12, 0xba, 0x7c, 0x3b, 0x54, 0x46, 0x1f, 0x30, 0xfd,
	0x21, 0x8c, 0x5a, 0xa5, 0xf2, 0x59, 0x5c, 0x91, 0x99, 0x1c, 0x35, 0x3f, 0xf2, 0xae, 0x4f, 0x71,
	0x98, 0x97, 0xc3, 0x2e, 0x8c, 0xfd, 0xce, 0x9e, 0x62, 0xee, 0xc1, 0xe8, 0x48, 0xf0, 0xe7, 0x8d,
	0x73, 0xc9, 0x5b, 0xf4, 0x3f, 0x74, 0x45, 0x63, 0x15, 0x41, 0x61, 0x75, 0x4e, 0x63, 0x5d, 0x11,
	0x60, 0x86, 0x6d, 0xa4, 0x18, 0x18, 0xcd, 0x3d, 0x8f, 0x50, 0x2a, 0xc0, 0x03, 0xb7, 0x34, 0xf9,
	0x4d, 0x44, 0x28, 0xe5, 0x02, 0x29, 0x08, 0x94, 0x66, 0xf5, 0x35, 0xf5, 0xb6, 0xaf, 0x6d, 0x00,
	0x3c, 0x21, 0xac, 0x24, 0xf9, 0x83, 0x96, 0xcd, 0xa0, 0x71, 0x7b, 0xc7, 0x44, 0x4e, 0x61, 0x78,
	0x12, 0xd0, 0x8a, 0x09, 0x82, 0x6e, 0xca, 0xd3, 0x29, 0x42, 0xf8, 0xe2, 0xcc, 0xbb, 0x1d, 0x06,
	0x51, 0xc0, 0xc4, 0x37, 0x7a, 0x6e, 0x61, 0x88, 0xcd, 0x21, 0x38, 0xf3, 0x2e, 0xe5, 0x5a, 0x49,
	0xcb, 0xfc, 0xa0, 0x34, 0x33, 0xfe, 0x29, 0x7b, 0xf5, 0xa7, 0xec, 0xeb, 0xa5, 0xec, 0x36, 0x96,
	0xd2, 0x7c, 0x0a, 0xa3, 0x73, 0xa1, 0xc4, 0x1b, 0xfa, 0x5b, 0xe5, 0xef, 0xfc, 0x82, 0x28, 0x9a,
	0x99, 0xee, 0x78, 0x16, 0x9b, 0x30, 0x7a, 0x2c, 0xd6, 0xe0, 0x26, 0x5d, 0x1c, 0xb5, 0x03, 0x7e,
	0x8b, 0xce, 0xee, 0x17, 0x15, 0x86, 0x1c, 0x7f, 0x46, 0xb2, 0x29, 0x7f, 0xac, 0xce, 0x01, 0x6a,
	0xe1, 0xa3, 0xf5, 0x8a, 0x5e, 0x6b, 0x8f, 0xf4, 0xf9, 0x7e, 0x6a, 0xfe, 0xfd, 0xf1, 0xeb, 0xb7,
	0x4f, 0x9d, 0x15, 0x73, 0x49, 0xbc, 0xda, 0xf2, 0xe5, 0xdf, 0x57, 0xb6, 0xd0, 0x73, 0xe8, 0x4b,
	0x0d, 0xa3, 0xba, 0xe4, 0x5a, 0xf3, 0xfa, 0x1c, 0x27, 0x35, 0xff, 0x11, 0xd9, 0x56, 0xd1, 0x4a,
	0x33, 0x9b, 0xf3, 0x2e, 0xf0, 0xdf, 0xa3, 0x13, 0x18, 0x94, 0xb2, 0x42, 0x6b, 0x15, 0xb6, 0xa1,
	0x5d, 0x7d, 0x9e, 0x97, 0x9a, 0x6b, 0x22, 0xe5, 0x32, 0x6a, 0x11, 0x44, 0x17, 0x00, 0xf5, 0x60,
	0x1b, 0x45, 0xb7, 0x74, 0xa3, 0xcf, 0xf7, 0x53, 0x73, 0x43, 0xe4, 0x5c, 0xd7, 0xaf, 0xd3, 0xe4,
	0x95, 0xbf, 0x02, 0xa8, 0xa7, 0xd4, 0xc8, 0xdd, 0x9a, 0xad, 0x3e, 0xdf, 0x5f, 0xb5, 0x60, 0xeb,
	0x7a, 0xee, 0xc3, 0x7b, 0x17, 0xf6, 0x24, 0x60, 0x97, 0xf9, 0xd8, 0xf6, 0x92, 0xc8, 0x39, 0x3d,
	0x3b, 0x3a, 0x70, 0x29, 0xc3, 0xde, 0x55, 0xee, 0xd0, 0x4b, 0x9c, 0x11, 0x7f, 0x7b, 0x92, 0x6c,
	0x8b, 0xb7, 0xd5, 0x91, 0x7f, 0xc3, 0xe3, 0x05, 0x61, 0xde, 0xff, 0x1e, 0x00, 0x00, 0xff, 0xff,
	0x40, 0x97, 0x8b, 0x1c, 0x98, 0x07, 0x00, 0x00,
}
