// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin/v1/admin.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy            string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	TipoIdentificacion   string                 `protobuf:"bytes,3,opt,name=tipo_identificacion,json=tipoIdentificacion,proto3" json:"tipo_identificacion,omitempty"`
	Identificacion       string                 `protobuf:"bytes,4,opt,name=identificacion,proto3" json:"identificacion,omitempty"`
	Nombres              string                 `protobuf:"bytes,5,opt,name=nombres,proto3" json:"nombres,omitempty"`
	Apellidos            string                 `protobuf:"bytes,6,opt,name=apellidos,proto3" json:"apellidos,omitempty"`
	Direccion            string                 `protobuf:"bytes,7,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Pais                 string                 `protobuf:"bytes,8,opt,name=pais,proto3" json:"pais,omitempty"`
	Departamento         string                 `protobuf:"bytes,9,opt,name=departamento,proto3" json:"departamento,omitempty"`
	Ciudad               string                 `protobuf:"bytes,10,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
	Correo               string                 `protobuf:"bytes,11,opt,name=correo,proto3" json:"correo,omitempty"`
	Contrasena           string                 `protobuf:"bytes,12,opt,name=contrasena,proto3" json:"contrasena,omitempty"`
	IndicativoTelefono   string                 `protobuf:"bytes,13,opt,name=indicativo_telefono,json=indicativoTelefono,proto3" json:"indicativo_telefono,omitempty"`
	Telefono             string                 `protobuf:"bytes,14,opt,name=telefono,proto3" json:"telefono,omitempty"`
	IndicativoWhatsApp   string                 `protobuf:"bytes,15,opt,name=indicativo_whatsApp,json=indicativoWhatsApp,proto3" json:"indicativo_whatsApp,omitempty"`
	WhatsApp             string                 `protobuf:"bytes,16,opt,name=whatsApp,proto3" json:"whatsApp,omitempty"`
	MensajeEstado        string                 `protobuf:"bytes,17,opt,name=mensaje_estado,json=mensajeEstado,proto3" json:"mensaje_estado,omitempty"`
	Rol                  string                 `protobuf:"bytes,18,opt,name=rol,proto3" json:"rol,omitempty"`
	UsuarioEmpresarial   string                 `protobuf:"bytes,19,opt,name=usuario_empresarial,json=usuarioEmpresarial,proto3" json:"usuario_empresarial,omitempty"`
	LenguajeUsuario      string                 `protobuf:"bytes,20,opt,name=lenguajeUsuario,proto3" json:"lenguajeUsuario,omitempty"`
	BA                   bool                   `protobuf:"varint,21,opt,name=bA,proto3" json:"bA,omitempty"`
	SU                   bool                   `protobuf:"varint,22,opt,name=sU,proto3" json:"sU,omitempty"`
	Collaborator         bool                   `protobuf:"varint,23,opt,name=collaborator,proto3" json:"collaborator,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AdminEntity) Reset()         { *m = AdminEntity{} }
func (m *AdminEntity) String() string { return proto.CompactTextString(m) }
func (*AdminEntity) ProtoMessage()    {}
func (*AdminEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{0}
}

func (m *AdminEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminEntity.Unmarshal(m, b)
}
func (m *AdminEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminEntity.Marshal(b, m, deterministic)
}
func (m *AdminEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminEntity.Merge(m, src)
}
func (m *AdminEntity) XXX_Size() int {
	return xxx_messageInfo_AdminEntity.Size(m)
}
func (m *AdminEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AdminEntity proto.InternalMessageInfo

func (m *AdminEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AdminEntity) GetTipoIdentificacion() string {
	if m != nil {
		return m.TipoIdentificacion
	}
	return ""
}

func (m *AdminEntity) GetIdentificacion() string {
	if m != nil {
		return m.Identificacion
	}
	return ""
}

func (m *AdminEntity) GetNombres() string {
	if m != nil {
		return m.Nombres
	}
	return ""
}

func (m *AdminEntity) GetApellidos() string {
	if m != nil {
		return m.Apellidos
	}
	return ""
}

func (m *AdminEntity) GetDireccion() string {
	if m != nil {
		return m.Direccion
	}
	return ""
}

func (m *AdminEntity) GetPais() string {
	if m != nil {
		return m.Pais
	}
	return ""
}

func (m *AdminEntity) GetDepartamento() string {
	if m != nil {
		return m.Departamento
	}
	return ""
}

func (m *AdminEntity) GetCiudad() string {
	if m != nil {
		return m.Ciudad
	}
	return ""
}

func (m *AdminEntity) GetCorreo() string {
	if m != nil {
		return m.Correo
	}
	return ""
}

func (m *AdminEntity) GetContrasena() string {
	if m != nil {
		return m.Contrasena
	}
	return ""
}

func (m *AdminEntity) GetIndicativoTelefono() string {
	if m != nil {
		return m.IndicativoTelefono
	}
	return ""
}

func (m *AdminEntity) GetTelefono() string {
	if m != nil {
		return m.Telefono
	}
	return ""
}

func (m *AdminEntity) GetIndicativoWhatsApp() string {
	if m != nil {
		return m.IndicativoWhatsApp
	}
	return ""
}

func (m *AdminEntity) GetWhatsApp() string {
	if m != nil {
		return m.WhatsApp
	}
	return ""
}

func (m *AdminEntity) GetMensajeEstado() string {
	if m != nil {
		return m.MensajeEstado
	}
	return ""
}

func (m *AdminEntity) GetRol() string {
	if m != nil {
		return m.Rol
	}
	return ""
}

func (m *AdminEntity) GetUsuarioEmpresarial() string {
	if m != nil {
		return m.UsuarioEmpresarial
	}
	return ""
}

func (m *AdminEntity) GetLenguajeUsuario() string {
	if m != nil {
		return m.LenguajeUsuario
	}
	return ""
}

func (m *AdminEntity) GetBA() bool {
	if m != nil {
		return m.BA
	}
	return false
}

func (m *AdminEntity) GetSU() bool {
	if m != nil {
		return m.SU
	}
	return false
}

func (m *AdminEntity) GetCollaborator() bool {
	if m != nil {
		return m.Collaborator
	}
	return false
}

func (m *AdminEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *AdminEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AdminEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateAdminReq struct {
	Data                 *AdminEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateAdminReq) Reset()         { *m = CreateAdminReq{} }
func (m *CreateAdminReq) String() string { return proto.CompactTextString(m) }
func (*CreateAdminReq) ProtoMessage()    {}
func (*CreateAdminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{1}
}

func (m *CreateAdminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminReq.Unmarshal(m, b)
}
func (m *CreateAdminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminReq.Marshal(b, m, deterministic)
}
func (m *CreateAdminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminReq.Merge(m, src)
}
func (m *CreateAdminReq) XXX_Size() int {
	return xxx_messageInfo_CreateAdminReq.Size(m)
}
func (m *CreateAdminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminReq proto.InternalMessageInfo

func (m *CreateAdminReq) GetData() *AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateAdminRes struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AdminEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateAdminRes) Reset()         { *m = CreateAdminRes{} }
func (m *CreateAdminRes) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRes) ProtoMessage()    {}
func (*CreateAdminRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{2}
}

func (m *CreateAdminRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRes.Unmarshal(m, b)
}
func (m *CreateAdminRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRes.Marshal(b, m, deterministic)
}
func (m *CreateAdminRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRes.Merge(m, src)
}
func (m *CreateAdminRes) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRes.Size(m)
}
func (m *CreateAdminRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRes proto.InternalMessageInfo

func (m *CreateAdminRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateAdminRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateAdminRes) GetData() *AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAdminReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminReq) Reset()         { *m = GetAdminReq{} }
func (m *GetAdminReq) String() string { return proto.CompactTextString(m) }
func (*GetAdminReq) ProtoMessage()    {}
func (*GetAdminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{3}
}

func (m *GetAdminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminReq.Unmarshal(m, b)
}
func (m *GetAdminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminReq.Marshal(b, m, deterministic)
}
func (m *GetAdminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminReq.Merge(m, src)
}
func (m *GetAdminReq) XXX_Size() int {
	return xxx_messageInfo_GetAdminReq.Size(m)
}
func (m *GetAdminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminReq proto.InternalMessageInfo

func (m *GetAdminReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAdminRes struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AdminEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAdminRes) Reset()         { *m = GetAdminRes{} }
func (m *GetAdminRes) String() string { return proto.CompactTextString(m) }
func (*GetAdminRes) ProtoMessage()    {}
func (*GetAdminRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{4}
}

func (m *GetAdminRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminRes.Unmarshal(m, b)
}
func (m *GetAdminRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminRes.Marshal(b, m, deterministic)
}
func (m *GetAdminRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminRes.Merge(m, src)
}
func (m *GetAdminRes) XXX_Size() int {
	return xxx_messageInfo_GetAdminRes.Size(m)
}
func (m *GetAdminRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminRes proto.InternalMessageInfo

func (m *GetAdminRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAdminRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAdminRes) GetData() *AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListAdminReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAdminReq) Reset()         { *m = ListAdminReq{} }
func (m *ListAdminReq) String() string { return proto.CompactTextString(m) }
func (*ListAdminReq) ProtoMessage()    {}
func (*ListAdminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{5}
}

func (m *ListAdminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAdminReq.Unmarshal(m, b)
}
func (m *ListAdminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAdminReq.Marshal(b, m, deterministic)
}
func (m *ListAdminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdminReq.Merge(m, src)
}
func (m *ListAdminReq) XXX_Size() int {
	return xxx_messageInfo_ListAdminReq.Size(m)
}
func (m *ListAdminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdminReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdminReq proto.InternalMessageInfo

func (m *ListAdminReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAdminReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAdminReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListAdminRes struct {
	Success              bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*AdminEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64          `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListAdminRes) Reset()         { *m = ListAdminRes{} }
func (m *ListAdminRes) String() string { return proto.CompactTextString(m) }
func (*ListAdminRes) ProtoMessage()    {}
func (*ListAdminRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{6}
}

func (m *ListAdminRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAdminRes.Unmarshal(m, b)
}
func (m *ListAdminRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAdminRes.Marshal(b, m, deterministic)
}
func (m *ListAdminRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdminRes.Merge(m, src)
}
func (m *ListAdminRes) XXX_Size() int {
	return xxx_messageInfo_ListAdminRes.Size(m)
}
func (m *ListAdminRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdminRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdminRes proto.InternalMessageInfo

func (m *ListAdminRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListAdminRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListAdminRes) GetData() []*AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListAdminRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateAdminReq struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *AdminEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateAdminReq) Reset()         { *m = UpdateAdminReq{} }
func (m *UpdateAdminReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAdminReq) ProtoMessage()    {}
func (*UpdateAdminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{7}
}

func (m *UpdateAdminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAdminReq.Unmarshal(m, b)
}
func (m *UpdateAdminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAdminReq.Marshal(b, m, deterministic)
}
func (m *UpdateAdminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAdminReq.Merge(m, src)
}
func (m *UpdateAdminReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAdminReq.Size(m)
}
func (m *UpdateAdminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAdminReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAdminReq proto.InternalMessageInfo

func (m *UpdateAdminReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAdminReq) GetData() *AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateAdminRes struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AdminEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateAdminRes) Reset()         { *m = UpdateAdminRes{} }
func (m *UpdateAdminRes) String() string { return proto.CompactTextString(m) }
func (*UpdateAdminRes) ProtoMessage()    {}
func (*UpdateAdminRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{8}
}

func (m *UpdateAdminRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAdminRes.Unmarshal(m, b)
}
func (m *UpdateAdminRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAdminRes.Marshal(b, m, deterministic)
}
func (m *UpdateAdminRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAdminRes.Merge(m, src)
}
func (m *UpdateAdminRes) XXX_Size() int {
	return xxx_messageInfo_UpdateAdminRes.Size(m)
}
func (m *UpdateAdminRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAdminRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAdminRes proto.InternalMessageInfo

func (m *UpdateAdminRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateAdminRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateAdminRes) GetData() *AdminEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteAdminReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminReq) Reset()         { *m = DeleteAdminReq{} }
func (m *DeleteAdminReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminReq) ProtoMessage()    {}
func (*DeleteAdminReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{9}
}

func (m *DeleteAdminReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminReq.Unmarshal(m, b)
}
func (m *DeleteAdminReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminReq.Marshal(b, m, deterministic)
}
func (m *DeleteAdminReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminReq.Merge(m, src)
}
func (m *DeleteAdminReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminReq.Size(m)
}
func (m *DeleteAdminReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminReq proto.InternalMessageInfo

func (m *DeleteAdminReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAdminRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdminRes) Reset()         { *m = DeleteAdminRes{} }
func (m *DeleteAdminRes) String() string { return proto.CompactTextString(m) }
func (*DeleteAdminRes) ProtoMessage()    {}
func (*DeleteAdminRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_937866dbbed593e0, []int{10}
}

func (m *DeleteAdminRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdminRes.Unmarshal(m, b)
}
func (m *DeleteAdminRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdminRes.Marshal(b, m, deterministic)
}
func (m *DeleteAdminRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdminRes.Merge(m, src)
}
func (m *DeleteAdminRes) XXX_Size() int {
	return xxx_messageInfo_DeleteAdminRes.Size(m)
}
func (m *DeleteAdminRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdminRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdminRes proto.InternalMessageInfo

func (m *DeleteAdminRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteAdminRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AdminEntity)(nil), "admin.v1.AdminEntity")
	proto.RegisterType((*CreateAdminReq)(nil), "admin.v1.CreateAdminReq")
	proto.RegisterType((*CreateAdminRes)(nil), "admin.v1.CreateAdminRes")
	proto.RegisterType((*GetAdminReq)(nil), "admin.v1.GetAdminReq")
	proto.RegisterType((*GetAdminRes)(nil), "admin.v1.GetAdminRes")
	proto.RegisterType((*ListAdminReq)(nil), "admin.v1.ListAdminReq")
	proto.RegisterType((*ListAdminRes)(nil), "admin.v1.ListAdminRes")
	proto.RegisterType((*UpdateAdminReq)(nil), "admin.v1.UpdateAdminReq")
	proto.RegisterType((*UpdateAdminRes)(nil), "admin.v1.UpdateAdminRes")
	proto.RegisterType((*DeleteAdminReq)(nil), "admin.v1.DeleteAdminReq")
	proto.RegisterType((*DeleteAdminRes)(nil), "admin.v1.DeleteAdminRes")
}

func init() {
	proto.RegisterFile("admin/v1/admin.proto", fileDescriptor_937866dbbed593e0)
}

var fileDescriptor_937866dbbed593e0 = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0x56, 0x92, 0xfe, 0x24, 0x4e, 0x9b, 0x2e, 0xde, 0xb6, 0x6b, 0x46, 0x5b, 0xa8, 0x46, 0x02,
	0x95, 0x95, 0x9a, 0xd1, 0x16, 0x6e, 0x80, 0xab, 0xec, 0xb6, 0x42, 0x08, 0x2e, 0xd0, 0x6c, 0x2b,
	0x24, 0x10, 0x0a, 0x9e, 0xf1, 0x69, 0xea, 0xd5, 0xcc, 0x78, 0xb0, 0x9d, 0xa2, 0x0a, 0x71, 0x03,
	0x8f, 0x80, 0xc4, 0x8b, 0x21, 0xf1, 0x04, 0x3c, 0x08, 0xf2, 0x99, 0x9f, 0xcc, 0x8c, 0x1a, 0x15,
	0xb1, 0xda, 0x3b, 0x7f, 0x3f, 0xe7, 0xf8, 0x8c, 0x7d, 0x8e, 0x13, 0xb2, 0xcf, 0x45, 0x2a, 0xb3,
	0xe0, 0xf6, 0x79, 0x80, 0x8b, 0x69, 0xae, 0x95, 0x55, 0x74, 0x58, 0x80, 0xdb, 0xe7, 0xde, 0xfb,
	0x0b, 0xa5, 0x16, 0x09, 0x04, 0xc8, 0x47, 0xcb, 0xeb, 0xc0, 0xca, 0x14, 0x8c, 0xe5, 0x69, 0x5e,
	0x58, 0xbd, 0xa7, 0xa5, 0x81, 0xe7, 0x32, 0xe0, 0x59, 0xa6, 0x2c, 0xb7, 0x52, 0x65, 0xa6, 0x50,
	0xfd, 0x3f, 0xb7, 0xc9, 0x78, 0xe6, 0x72, 0x5d, 0x64, 0x56, 0xda, 0x3b, 0x3a, 0x21, 0x7d, 0x29,
	0x58, 0xef, 0xb8, 0x77, 0x32, 0x0a, 0xfb, 0x52, 0xd0, 0x23, 0x42, 0x62, 0x0d, 0xdc, 0x82, 0x98,
	0x47, 0x77, 0xac, 0x8f, 0xfc, 0xa8, 0x64, 0x5e, 0xdc, 0xd1, 0x80, 0x3c, 0xb6, 0x32, 0x57, 0x73,
	0x29, 0x20, 0xb3, 0xf2, 0x5a, 0xc6, 0x3c, 0x96, 0x2a, 0x63, 0x03, 0xf4, 0x51, 0x27, 0x7d, 0xd9,
	0x52, 0xe8, 0x87, 0x64, 0xd2, 0xf1, 0x6e, 0xa0, 0xb7, 0xc3, 0x52, 0x46, 0xb6, 0x33, 0x95, 0x46,
	0x1a, 0x0c, 0xdb, 0x44, 0x43, 0x05, 0xe9, 0x53, 0x32, 0xe2, 0x39, 0x24, 0x89, 0x14, 0xca, 0xb0,
	0xad, 0xa2, 0xa0, 0x9a, 0x70, 0xaa, 0x90, 0x1a, 0x62, 0x4c, 0xbd, 0x5d, 0xa8, 0x35, 0x41, 0x29,
	0xd9, 0xc8, 0xb9, 0x34, 0x6c, 0x88, 0x02, 0xae, 0xa9, 0x4f, 0x76, 0x04, 0xe4, 0x5c, 0x5b, 0x9e,
	0x42, 0x66, 0x15, 0x1b, 0xa1, 0xd6, 0xe2, 0xe8, 0x21, 0xd9, 0x8a, 0xe5, 0x52, 0x70, 0xc1, 0x08,
	0xaa, 0x25, 0x42, 0x5e, 0x69, 0x0d, 0x8a, 0x8d, 0x4b, 0x1e, 0x11, 0x7d, 0x8f, 0x90, 0x58, 0x65,
	0x56, 0x73, 0x03, 0x19, 0x67, 0x3b, 0xa8, 0x35, 0x18, 0x77, 0x6c, 0x32, 0x13, 0x32, 0xe6, 0x56,
	0xde, 0xaa, 0xb9, 0x85, 0x04, 0xae, 0x55, 0xa6, 0xd8, 0x6e, 0x71, 0x6c, 0x2b, 0xe9, 0xb2, 0x54,
	0xa8, 0x47, 0x86, 0xb5, 0x6b, 0x82, 0xae, 0x1a, 0x77, 0x92, 0xfd, 0x7c, 0xc3, 0xad, 0x99, 0xe5,
	0x39, 0xdb, 0xeb, 0x26, 0xfb, 0xb6, 0x54, 0x5c, 0xb2, 0xda, 0xf5, 0xa8, 0x48, 0x56, 0x61, 0xfa,
	0x01, 0x99, 0xa4, 0x90, 0x19, 0xfe, 0x1a, 0xe6, 0xae, 0x8b, 0x84, 0x62, 0xef, 0xa0, 0x63, 0xb7,
	0x64, 0x2f, 0x90, 0xa4, 0x8f, 0xc8, 0x40, 0xab, 0x84, 0x51, 0xd4, 0xdc, 0xd2, 0x55, 0xb1, 0x34,
	0x4b, 0xae, 0xa5, 0x9a, 0x43, 0x9a, 0x6b, 0x30, 0x5c, 0x4b, 0x9e, 0xb0, 0xc7, 0x45, 0x15, 0xa5,
	0x74, 0xb1, 0x52, 0xe8, 0x09, 0xd9, 0x4b, 0x20, 0x5b, 0x2c, 0xf9, 0x6b, 0xb8, 0x2a, 0x54, 0xb6,
	0x8f, 0xe6, 0x2e, 0xed, 0x7a, 0x32, 0x9a, 0xb1, 0x83, 0xe3, 0xde, 0xc9, 0x30, 0xec, 0x47, 0x33,
	0x87, 0xcd, 0x15, 0x3b, 0x2c, 0xb0, 0xb9, 0x72, 0x37, 0x18, 0xab, 0x24, 0xe1, 0x91, 0xd2, 0xdc,
	0x2a, 0xcd, 0x9e, 0xa0, 0xd2, 0xe2, 0xe8, 0xa7, 0xab, 0x3e, 0xe6, 0x96, 0xb1, 0xe3, 0xde, 0xc9,
	0xf8, 0xcc, 0x9b, 0x16, 0xa3, 0x31, 0xad, 0x66, 0x67, 0x7a, 0x59, 0xcd, 0x4e, 0xdd, 0xe3, 0x33,
	0xeb, 0x42, 0x97, 0xb9, 0xa8, 0x42, 0xdf, 0x7d, 0x38, 0xb4, 0x74, 0x17, 0xa1, 0x02, 0x12, 0x28,
	0x43, 0xbd, 0x87, 0x43, 0x4b, 0xf7, 0xcc, 0xfa, 0x9f, 0x93, 0xc9, 0x4b, 0x2c, 0x01, 0xa7, 0x33,
	0x84, 0x9f, 0xe8, 0x47, 0x64, 0x43, 0x70, 0xcb, 0x71, 0x38, 0xc7, 0x67, 0x07, 0xd3, 0xea, 0x09,
	0x98, 0x36, 0xe6, 0x37, 0x44, 0x8b, 0xaf, 0x3a, 0xc1, 0xc6, 0xcd, 0x93, 0x59, 0xc6, 0x31, 0x18,
	0x83, 0xf1, 0xc3, 0xb0, 0x82, 0x4e, 0x49, 0xc1, 0x18, 0xbe, 0x80, 0x72, 0xbc, 0x2b, 0x58, 0x6f,
	0x38, 0x78, 0x78, 0xc3, 0x23, 0x32, 0xfe, 0x02, 0x6c, 0x5d, 0x6a, 0xe7, 0x15, 0xf1, 0x93, 0xa6,
	0xfc, 0xd6, 0x8b, 0xf9, 0x86, 0xec, 0x7c, 0x2d, 0xcd, 0xaa, 0x1a, 0x9c, 0xfa, 0x05, 0xe0, 0x5e,
	0x9b, 0x21, 0xae, 0xe9, 0x3e, 0xd9, 0x4c, 0x64, 0x2a, 0x2d, 0x6e, 0xb3, 0x19, 0x16, 0xc0, 0xcd,
	0xb3, 0x01, 0xae, 0xe3, 0x9b, 0xf2, 0x05, 0x2b, 0x91, 0xff, 0x7b, 0xaf, 0x95, 0xf2, 0x4d, 0xbf,
	0x60, 0xf0, 0xc0, 0x17, 0xb8, 0xea, 0xac, 0xb2, 0x3c, 0xc1, 0xc7, 0x71, 0x10, 0x16, 0xc0, 0xff,
	0x8a, 0x4c, 0xae, 0xb0, 0xb5, 0xd6, 0x9d, 0x73, 0xbd, 0x45, 0xff, 0x3f, 0xb5, 0x48, 0x2b, 0xd9,
	0x5b, 0xbf, 0x95, 0x63, 0x32, 0x39, 0xc7, 0xee, 0x5e, 0xdb, 0x25, 0xe7, 0x1d, 0xc7, 0xff, 0x2a,
	0xe9, 0xec, 0xef, 0x01, 0xd9, 0xc1, 0x04, 0xaf, 0x40, 0xdf, 0xca, 0x18, 0xe8, 0xf7, 0x64, 0xdc,
	0x18, 0x06, 0xca, 0x56, 0x45, 0xb6, 0x07, 0xcc, 0x5b, 0xa7, 0x18, 0x9f, 0xfd, 0xf6, 0xd7, 0x3f,
	0x7f, 0xf4, 0xa9, 0xbf, 0x8b, 0xbf, 0xa2, 0xd5, 0x6f, 0xf1, 0x67, 0xbd, 0x67, 0xf4, 0x92, 0x0c,
	0xab, 0xce, 0xa6, 0x8d, 0xcf, 0x6f, 0x0c, 0x83, 0x77, 0x2f, 0x6d, 0x7c, 0x0f, 0x73, 0xee, 0x53,
	0xda, 0xca, 0x19, 0xfc, 0x22, 0xc5, 0xaf, 0x34, 0x24, 0xa3, 0xba, 0xdd, 0xe8, 0xe1, 0x2a, 0xbe,
	0xd9, 0xd6, 0xde, 0xfd, 0xbc, 0xf1, 0x0f, 0x30, 0xf1, 0x1e, 0x6d, 0x17, 0x4b, 0x7f, 0x24, 0xe3,
	0xc6, 0x85, 0x37, 0x8f, 0xa1, 0xdd, 0x54, 0xde, 0x3a, 0xc5, 0xf8, 0x47, 0x98, 0xf9, 0x89, 0x77,
	0x4f, 0xc9, 0xee, 0x2c, 0x7e, 0x20, 0xe3, 0xc6, 0xfd, 0x35, 0x77, 0x68, 0x5f, 0xbc, 0xb7, 0x4e,
	0xa9, 0x0f, 0xe5, 0xd9, 0x3d, 0x3b, 0xbc, 0xf8, 0xe4, 0xbb, 0xb3, 0x85, 0xb4, 0x37, 0xcb, 0x68,
	0x1a, 0xab, 0x34, 0x78, 0x75, 0x3e, 0xbb, 0x9c, 0x9d, 0xbe, 0x54, 0x89, 0x4a, 0x23, 0xc9, 0x03,
	0x73, 0xc3, 0x35, 0x88, 0xd3, 0x85, 0x3a, 0xc5, 0x67, 0x35, 0xa8, 0xfe, 0x35, 0x45, 0x5b, 0x88,
	0x3f, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x3f, 0x1d, 0x0f, 0x48, 0x09, 0x00, 0x00,
}
