// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ws/v1/ws.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WsEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WsEntity) Reset()         { *m = WsEntity{} }
func (m *WsEntity) String() string { return proto.CompactTextString(m) }
func (*WsEntity) ProtoMessage()    {}
func (*WsEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{0}
}

func (m *WsEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsEntity.Unmarshal(m, b)
}
func (m *WsEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsEntity.Marshal(b, m, deterministic)
}
func (m *WsEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsEntity.Merge(m, src)
}
func (m *WsEntity) XXX_Size() int {
	return xxx_messageInfo_WsEntity.Size(m)
}
func (m *WsEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_WsEntity.DiscardUnknown(m)
}

var xxx_messageInfo_WsEntity proto.InternalMessageInfo

func (m *WsEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WsEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WsEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WsEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *WsEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *WsEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *WsEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *WsEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *WsEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *WsEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WsEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *WsEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *WsEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *WsEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateWsReq struct {
	Data                 *WsEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateWsReq) Reset()         { *m = CreateWsReq{} }
func (m *CreateWsReq) String() string { return proto.CompactTextString(m) }
func (*CreateWsReq) ProtoMessage()    {}
func (*CreateWsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{1}
}

func (m *CreateWsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWsReq.Unmarshal(m, b)
}
func (m *CreateWsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWsReq.Marshal(b, m, deterministic)
}
func (m *CreateWsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWsReq.Merge(m, src)
}
func (m *CreateWsReq) XXX_Size() int {
	return xxx_messageInfo_CreateWsReq.Size(m)
}
func (m *CreateWsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWsReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWsReq proto.InternalMessageInfo

func (m *CreateWsReq) GetData() *WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateWsRes struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *WsEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateWsRes) Reset()         { *m = CreateWsRes{} }
func (m *CreateWsRes) String() string { return proto.CompactTextString(m) }
func (*CreateWsRes) ProtoMessage()    {}
func (*CreateWsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{2}
}

func (m *CreateWsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWsRes.Unmarshal(m, b)
}
func (m *CreateWsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWsRes.Marshal(b, m, deterministic)
}
func (m *CreateWsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWsRes.Merge(m, src)
}
func (m *CreateWsRes) XXX_Size() int {
	return xxx_messageInfo_CreateWsRes.Size(m)
}
func (m *CreateWsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWsRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWsRes proto.InternalMessageInfo

func (m *CreateWsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateWsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateWsRes) GetData() *WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetWsReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWsReq) Reset()         { *m = GetWsReq{} }
func (m *GetWsReq) String() string { return proto.CompactTextString(m) }
func (*GetWsReq) ProtoMessage()    {}
func (*GetWsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{3}
}

func (m *GetWsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWsReq.Unmarshal(m, b)
}
func (m *GetWsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWsReq.Marshal(b, m, deterministic)
}
func (m *GetWsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWsReq.Merge(m, src)
}
func (m *GetWsReq) XXX_Size() int {
	return xxx_messageInfo_GetWsReq.Size(m)
}
func (m *GetWsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWsReq proto.InternalMessageInfo

func (m *GetWsReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetWsRes struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *WsEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetWsRes) Reset()         { *m = GetWsRes{} }
func (m *GetWsRes) String() string { return proto.CompactTextString(m) }
func (*GetWsRes) ProtoMessage()    {}
func (*GetWsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{4}
}

func (m *GetWsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWsRes.Unmarshal(m, b)
}
func (m *GetWsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWsRes.Marshal(b, m, deterministic)
}
func (m *GetWsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWsRes.Merge(m, src)
}
func (m *GetWsRes) XXX_Size() int {
	return xxx_messageInfo_GetWsRes.Size(m)
}
func (m *GetWsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWsRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetWsRes proto.InternalMessageInfo

func (m *GetWsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetWsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetWsRes) GetData() *WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListWsReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWsReq) Reset()         { *m = ListWsReq{} }
func (m *ListWsReq) String() string { return proto.CompactTextString(m) }
func (*ListWsReq) ProtoMessage()    {}
func (*ListWsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{5}
}

func (m *ListWsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWsReq.Unmarshal(m, b)
}
func (m *ListWsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWsReq.Marshal(b, m, deterministic)
}
func (m *ListWsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWsReq.Merge(m, src)
}
func (m *ListWsReq) XXX_Size() int {
	return xxx_messageInfo_ListWsReq.Size(m)
}
func (m *ListWsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListWsReq proto.InternalMessageInfo

func (m *ListWsReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListWsReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListWsReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListWsRes struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*WsEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListWsRes) Reset()         { *m = ListWsRes{} }
func (m *ListWsRes) String() string { return proto.CompactTextString(m) }
func (*ListWsRes) ProtoMessage()    {}
func (*ListWsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{6}
}

func (m *ListWsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWsRes.Unmarshal(m, b)
}
func (m *ListWsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWsRes.Marshal(b, m, deterministic)
}
func (m *ListWsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWsRes.Merge(m, src)
}
func (m *ListWsRes) XXX_Size() int {
	return xxx_messageInfo_ListWsRes.Size(m)
}
func (m *ListWsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListWsRes proto.InternalMessageInfo

func (m *ListWsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListWsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListWsRes) GetData() []*WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListWsRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateWsReq struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *WsEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateWsReq) Reset()         { *m = UpdateWsReq{} }
func (m *UpdateWsReq) String() string { return proto.CompactTextString(m) }
func (*UpdateWsReq) ProtoMessage()    {}
func (*UpdateWsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{7}
}

func (m *UpdateWsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWsReq.Unmarshal(m, b)
}
func (m *UpdateWsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWsReq.Marshal(b, m, deterministic)
}
func (m *UpdateWsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWsReq.Merge(m, src)
}
func (m *UpdateWsReq) XXX_Size() int {
	return xxx_messageInfo_UpdateWsReq.Size(m)
}
func (m *UpdateWsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWsReq proto.InternalMessageInfo

func (m *UpdateWsReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateWsReq) GetData() *WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateWsRes struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *WsEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateWsRes) Reset()         { *m = UpdateWsRes{} }
func (m *UpdateWsRes) String() string { return proto.CompactTextString(m) }
func (*UpdateWsRes) ProtoMessage()    {}
func (*UpdateWsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{8}
}

func (m *UpdateWsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWsRes.Unmarshal(m, b)
}
func (m *UpdateWsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWsRes.Marshal(b, m, deterministic)
}
func (m *UpdateWsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWsRes.Merge(m, src)
}
func (m *UpdateWsRes) XXX_Size() int {
	return xxx_messageInfo_UpdateWsRes.Size(m)
}
func (m *UpdateWsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWsRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWsRes proto.InternalMessageInfo

func (m *UpdateWsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateWsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateWsRes) GetData() *WsEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteWsReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWsReq) Reset()         { *m = DeleteWsReq{} }
func (m *DeleteWsReq) String() string { return proto.CompactTextString(m) }
func (*DeleteWsReq) ProtoMessage()    {}
func (*DeleteWsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{9}
}

func (m *DeleteWsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWsReq.Unmarshal(m, b)
}
func (m *DeleteWsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWsReq.Marshal(b, m, deterministic)
}
func (m *DeleteWsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWsReq.Merge(m, src)
}
func (m *DeleteWsReq) XXX_Size() int {
	return xxx_messageInfo_DeleteWsReq.Size(m)
}
func (m *DeleteWsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWsReq proto.InternalMessageInfo

func (m *DeleteWsReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteWsRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWsRes) Reset()         { *m = DeleteWsRes{} }
func (m *DeleteWsRes) String() string { return proto.CompactTextString(m) }
func (*DeleteWsRes) ProtoMessage()    {}
func (*DeleteWsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b13138b2790ed, []int{10}
}

func (m *DeleteWsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWsRes.Unmarshal(m, b)
}
func (m *DeleteWsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWsRes.Marshal(b, m, deterministic)
}
func (m *DeleteWsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWsRes.Merge(m, src)
}
func (m *DeleteWsRes) XXX_Size() int {
	return xxx_messageInfo_DeleteWsRes.Size(m)
}
func (m *DeleteWsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWsRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWsRes proto.InternalMessageInfo

func (m *DeleteWsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteWsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*WsEntity)(nil), "ws.v1.WsEntity")
	proto.RegisterMapType((map[string]string)(nil), "ws.v1.WsEntity.MetadataEntry")
	proto.RegisterType((*CreateWsReq)(nil), "ws.v1.CreateWsReq")
	proto.RegisterType((*CreateWsRes)(nil), "ws.v1.CreateWsRes")
	proto.RegisterType((*GetWsReq)(nil), "ws.v1.GetWsReq")
	proto.RegisterType((*GetWsRes)(nil), "ws.v1.GetWsRes")
	proto.RegisterType((*ListWsReq)(nil), "ws.v1.ListWsReq")
	proto.RegisterType((*ListWsRes)(nil), "ws.v1.ListWsRes")
	proto.RegisterType((*UpdateWsReq)(nil), "ws.v1.UpdateWsReq")
	proto.RegisterType((*UpdateWsRes)(nil), "ws.v1.UpdateWsRes")
	proto.RegisterType((*DeleteWsReq)(nil), "ws.v1.DeleteWsReq")
	proto.RegisterType((*DeleteWsRes)(nil), "ws.v1.DeleteWsRes")
}

func init() {
	proto.RegisterFile("ws/v1/ws.proto", fileDescriptor_464b13138b2790ed)
}

var fileDescriptor_464b13138b2790ed = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x96, 0xe3, 0x24, 0x75, 0x26, 0xfd, 0x7a, 0x57, 0x7d, 0xdf, 0xd7, 0xb2, 0xa8, 0xb0, 0xcc,
	0xc5, 0xaa, 0x54, 0x5b, 0x0d, 0x17, 0x5a, 0x2e, 0x24, 0x6d, 0x85, 0x10, 0x94, 0x83, 0x5b, 0x54,
	0x89, 0x0b, 0xda, 0xd8, 0xdb, 0x74, 0x45, 0xfc, 0x81, 0x77, 0x9d, 0x2a, 0x20, 0x2e, 0xfc, 0x05,
	0xae, 0xfc, 0x2b, 0xfe, 0x02, 0x7f, 0x82, 0x1b, 0xda, 0xf5, 0xda, 0x31, 0x69, 0xa1, 0x12, 0xa8,
	0xb7, 0x9d, 0x99, 0x9d, 0xc7, 0xcf, 0xcc, 0x33, 0xb3, 0x86, 0xf5, 0x2b, 0xe6, 0xcf, 0xf6, 0xfc,
	0x2b, 0xe6, 0x65, 0x79, 0xca, 0x53, 0xd4, 0xb9, 0x62, 0xde, 0x6c, 0xcf, 0xba, 0x3f, 0x49, 0xd3,
	0xc9, 0x94, 0xf8, 0xd2, 0x39, 0x2e, 0x2e, 0x7c, 0x4e, 0x63, 0xc2, 0x38, 0x8e, 0xb3, 0xf2, 0x9e,
	0x75, 0x4f, 0x5d, 0xc0, 0x19, 0xf5, 0x71, 0x92, 0xa4, 0x1c, 0x73, 0x9a, 0x26, 0x0a, 0xc5, 0xf9,
	0xd2, 0x06, 0xe3, 0x9c, 0x1d, 0x27, 0x9c, 0xf2, 0x39, 0x5a, 0x87, 0x16, 0x8d, 0x4c, 0xcd, 0xd6,
	0xdc, 0x5e, 0xd0, 0xa2, 0x11, 0x42, 0xd0, 0x4e, 0x70, 0x4c, 0xcc, 0x96, 0xf4, 0xc8, 0x33, 0xb2,
	0xa1, 0x1f, 0x11, 0x16, 0xe6, 0x34, 0x13, 0x30, 0xa6, 0x2e, 0x43, 0x4d, 0x17, 0xfa, 0x0f, 0xba,
	0x8c, 0x63, 0x5e, 0x30, 0xb3, 0x6d, 0x6b, 0xae, 0x11, 0x28, 0x0b, 0x6d, 0x82, 0x8e, 0x27, 0xc4,
	0xec, 0xd8, 0x9a, 0xdb, 0x09, 0xc4, 0x11, 0x6d, 0x41, 0x87, 0xa7, 0x1c, 0x4f, 0xcd, 0xae, 0xad,
	0xb9, 0x7a, 0x50, 0x1a, 0xc2, 0x9b, 0xe5, 0x34, 0x24, 0xe6, 0x8a, 0xad, 0xb9, 0x5a, 0x50, 0x1a,
	0x82, 0x0b, 0xc7, 0x13, 0x66, 0x1a, 0xb6, 0x2e, 0xb8, 0x88, 0x33, 0x32, 0x61, 0x25, 0x29, 0xe2,
	0x31, 0xc9, 0x99, 0xd9, 0xb3, 0x75, 0xb7, 0x13, 0x54, 0x26, 0xda, 0x07, 0x23, 0x26, 0x1c, 0x47,
	0x98, 0x63, 0x13, 0x6c, 0xdd, 0xed, 0x0f, 0xb6, 0x3d, 0xd9, 0x2f, 0xaf, 0x2a, 0xd6, 0x3b, 0x51,
	0xf1, 0xe3, 0x84, 0xe7, 0xf3, 0xa0, 0xbe, 0x8e, 0xb6, 0x01, 0xc2, 0x9c, 0x60, 0x4e, 0xa2, 0x37,
	0xe3, 0xb9, 0xd9, 0x97, 0xf5, 0xf5, 0x94, 0x67, 0x34, 0x47, 0xfb, 0x8b, 0x30, 0xe6, 0xe6, 0xaa,
	0xad, 0xb9, 0xfd, 0x81, 0xe5, 0x95, 0x3d, 0xf6, 0x2a, 0x11, 0xbc, 0xb3, 0x4a, 0x84, 0x3a, 0x75,
	0xc8, 0x45, 0x6a, 0x91, 0x45, 0x55, 0xea, 0xda, 0xed, 0xa9, 0xea, 0x76, 0x99, 0x1a, 0x91, 0x29,
	0x51, 0xa9, 0xeb, 0xb7, 0xa7, 0xaa, 0xdb, 0x43, 0x6e, 0x3d, 0x86, 0xb5, 0x9f, 0x4a, 0x15, 0x3a,
	0xbc, 0x25, 0x73, 0x25, 0xb3, 0x38, 0x8a, 0x8e, 0xcf, 0xf0, 0xb4, 0xa8, 0x84, 0x2e, 0x8d, 0x83,
	0xd6, 0x23, 0xcd, 0x19, 0x40, 0xff, 0x50, 0xf2, 0x3f, 0x67, 0x01, 0x79, 0x87, 0x1e, 0x40, 0x5b,
	0xb6, 0x54, 0x93, 0x04, 0x36, 0x96, 0x5a, 0x1a, 0xc8, 0xa0, 0x73, 0xd1, 0xcc, 0x91, 0x22, 0xb1,
	0x22, 0x0c, 0x09, 0x63, 0x32, 0xcd, 0x08, 0x2a, 0x53, 0x44, 0x62, 0xc2, 0x98, 0x18, 0x8a, 0xf2,
	0xc3, 0x95, 0x59, 0x7f, 0x47, 0xff, 0xdd, 0x77, 0x2c, 0x30, 0x9e, 0x12, 0x5e, 0x12, 0x5b, 0x9a,
	0x5c, 0x27, 0xac, 0x63, 0x77, 0x48, 0xe0, 0x04, 0x7a, 0x2f, 0x28, 0x53, 0x0c, 0x10, 0xb4, 0x33,
	0x01, 0xa4, 0xc9, 0xf1, 0x96, 0x67, 0xd1, 0xd7, 0x29, 0x8d, 0x29, 0x97, 0xe8, 0x9d, 0xa0, 0x34,
	0xe4, 0x7e, 0x10, 0x9c, 0x87, 0x97, 0x6a, 0x79, 0x94, 0xe5, 0xbc, 0x5f, 0xc0, 0xfd, 0x2d, 0x69,
	0xfd, 0x97, 0xa4, 0x17, 0x3b, 0xd7, 0x6e, 0xec, 0x9c, 0x33, 0x82, 0xfe, 0x2b, 0x39, 0x6c, 0x37,
	0xb6, 0xb3, 0x46, 0x6e, 0xdd, 0xa2, 0xfb, 0x02, 0xe3, 0x0e, 0xdb, 0xbe, 0x0d, 0xfd, 0x23, 0x39,
	0xdd, 0x37, 0x4b, 0x3f, 0x6c, 0x86, 0xff, 0x88, 0xc6, 0xe0, 0x7b, 0x0b, 0x7a, 0xe7, 0xec, 0x94,
	0xe4, 0x33, 0xf1, 0xf2, 0x3c, 0x03, 0xa3, 0x9a, 0x67, 0x84, 0x14, 0xa5, 0xc6, 0x52, 0x58, 0xd7,
	0x7d, 0xcc, 0xf9, 0xf7, 0xd3, 0xd7, 0x6f, 0x9f, 0x5b, 0x1b, 0x0e, 0xc8, 0x67, 0x57, 0x3e, 0xdb,
	0x07, 0xda, 0x0e, 0x1a, 0x41, 0x47, 0x8e, 0x25, 0xaa, 0x4a, 0xab, 0x06, 0xd8, 0x5a, 0x72, 0x30,
	0xe7, 0x7f, 0x89, 0xf0, 0x0f, 0xda, 0x58, 0x20, 0xf8, 0x1f, 0x68, 0xf4, 0x11, 0x3d, 0x81, 0x6e,
	0x39, 0x26, 0x68, 0x53, 0xe5, 0xd4, 0x43, 0x68, 0x2d, 0x7b, 0x98, 0x83, 0x24, 0xcc, 0x2a, 0x6a,
	0x10, 0x41, 0x2f, 0xc1, 0xa8, 0x84, 0xaa, 0x0b, 0x6a, 0xa8, 0x6f, 0x5d, 0xf7, 0x31, 0xc7, 0x92,
	0x38, 0x5b, 0xd6, 0x32, 0x1d, 0x51, 0xd5, 0x73, 0x30, 0xaa, 0x8e, 0xd7, 0x78, 0x0d, 0x85, 0xac,
	0xeb, 0xbe, 0xba, 0xbc, 0x9d, 0x65, 0xbc, 0xd1, 0xde, 0x6b, 0x7f, 0x42, 0xf9, 0x65, 0x31, 0xf6,
	0xc2, 0x34, 0xf6, 0x4f, 0x8f, 0x86, 0x67, 0xc3, 0xdd, 0xc3, 0x74, 0x9a, 0xc6, 0x63, 0x8a, 0x7d,
	0x76, 0x89, 0x73, 0x12, 0xed, 0x4e, 0xd2, 0x5d, 0xf9, 0xe6, 0xf9, 0xf2, 0x97, 0x38, 0xee, 0x4a,
	0xe3, 0xe1, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0xa6, 0x97, 0x7c, 0x22, 0x07, 0x00, 0x00,
}
