// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ws/v1/ws.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WsService_CreateWs_FullMethodName = "/ws.v1.WsService/CreateWs"
	WsService_GetWs_FullMethodName    = "/ws.v1.WsService/GetWs"
	WsService_ListWs_FullMethodName   = "/ws.v1.WsService/ListWs"
	WsService_UpdateWs_FullMethodName = "/ws.v1.WsService/UpdateWs"
	WsService_DeleteWs_FullMethodName = "/ws.v1.WsService/DeleteWs"
)

// WsServiceClient is the client API for WsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsServiceClient interface {
	CreateWs(ctx context.Context, in *CreateWsReq, opts ...grpc.CallOption) (*CreateWsRes, error)
	GetWs(ctx context.Context, in *GetWsReq, opts ...grpc.CallOption) (*GetWsRes, error)
	ListWs(ctx context.Context, in *ListWsReq, opts ...grpc.CallOption) (*ListWsRes, error)
	UpdateWs(ctx context.Context, in *UpdateWsReq, opts ...grpc.CallOption) (*UpdateWsRes, error)
	DeleteWs(ctx context.Context, in *DeleteWsReq, opts ...grpc.CallOption) (*DeleteWsRes, error)
}

type wsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWsServiceClient(cc grpc.ClientConnInterface) WsServiceClient {
	return &wsServiceClient{cc}
}

func (c *wsServiceClient) CreateWs(ctx context.Context, in *CreateWsReq, opts ...grpc.CallOption) (*CreateWsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWsRes)
	err := c.cc.Invoke(ctx, WsService_CreateWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsServiceClient) GetWs(ctx context.Context, in *GetWsReq, opts ...grpc.CallOption) (*GetWsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWsRes)
	err := c.cc.Invoke(ctx, WsService_GetWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsServiceClient) ListWs(ctx context.Context, in *ListWsReq, opts ...grpc.CallOption) (*ListWsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWsRes)
	err := c.cc.Invoke(ctx, WsService_ListWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsServiceClient) UpdateWs(ctx context.Context, in *UpdateWsReq, opts ...grpc.CallOption) (*UpdateWsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWsRes)
	err := c.cc.Invoke(ctx, WsService_UpdateWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsServiceClient) DeleteWs(ctx context.Context, in *DeleteWsReq, opts ...grpc.CallOption) (*DeleteWsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWsRes)
	err := c.cc.Invoke(ctx, WsService_DeleteWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsServiceServer is the server API for WsService service.
// All implementations must embed UnimplementedWsServiceServer
// for forward compatibility.
type WsServiceServer interface {
	CreateWs(context.Context, *CreateWsReq) (*CreateWsRes, error)
	GetWs(context.Context, *GetWsReq) (*GetWsRes, error)
	ListWs(context.Context, *ListWsReq) (*ListWsRes, error)
	UpdateWs(context.Context, *UpdateWsReq) (*UpdateWsRes, error)
	DeleteWs(context.Context, *DeleteWsReq) (*DeleteWsRes, error)
	mustEmbedUnimplementedWsServiceServer()
}

// UnimplementedWsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWsServiceServer struct{}

func (UnimplementedWsServiceServer) CreateWs(context.Context, *CreateWsReq) (*CreateWsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWs not implemented")
}
func (UnimplementedWsServiceServer) GetWs(context.Context, *GetWsReq) (*GetWsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWs not implemented")
}
func (UnimplementedWsServiceServer) ListWs(context.Context, *ListWsReq) (*ListWsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWs not implemented")
}
func (UnimplementedWsServiceServer) UpdateWs(context.Context, *UpdateWsReq) (*UpdateWsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWs not implemented")
}
func (UnimplementedWsServiceServer) DeleteWs(context.Context, *DeleteWsReq) (*DeleteWsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWs not implemented")
}
func (UnimplementedWsServiceServer) mustEmbedUnimplementedWsServiceServer() {}
func (UnimplementedWsServiceServer) testEmbeddedByValue()                   {}

// UnsafeWsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsServiceServer will
// result in compilation errors.
type UnsafeWsServiceServer interface {
	mustEmbedUnimplementedWsServiceServer()
}

func RegisterWsServiceServer(s grpc.ServiceRegistrar, srv WsServiceServer) {
	// If the following call panics, it indicates UnimplementedWsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WsService_ServiceDesc, srv)
}

func _WsService_CreateWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServiceServer).CreateWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsService_CreateWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServiceServer).CreateWs(ctx, req.(*CreateWsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_GetWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServiceServer).GetWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsService_GetWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServiceServer).GetWs(ctx, req.(*GetWsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_ListWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServiceServer).ListWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsService_ListWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServiceServer).ListWs(ctx, req.(*ListWsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_UpdateWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServiceServer).UpdateWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsService_UpdateWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServiceServer).UpdateWs(ctx, req.(*UpdateWsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsService_DeleteWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServiceServer).DeleteWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsService_DeleteWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServiceServer).DeleteWs(ctx, req.(*DeleteWsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WsService_ServiceDesc is the grpc.ServiceDesc for WsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ws.v1.WsService",
	HandlerType: (*WsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWs",
			Handler:    _WsService_CreateWs_Handler,
		},
		{
			MethodName: "GetWs",
			Handler:    _WsService_GetWs_Handler,
		},
		{
			MethodName: "ListWs",
			Handler:    _WsService_ListWs_Handler,
		},
		{
			MethodName: "UpdateWs",
			Handler:    _WsService_UpdateWs_Handler,
		},
		{
			MethodName: "DeleteWs",
			Handler:    _WsService_DeleteWs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws/v1/ws.proto",
}
