syntax = "proto3";

package centrifugodf.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/SDATA-Colombia/shared-go-proto/centrifugodf/v1";

// -------------------------------------------------------------------
// Centrifugodf Entity message
// -------------------------------------------------------------------

message CentrifugodfEntity {
  string id = 1;
  string name = 2;
  string description = 3;
  bool status = 4;
  int32 age = 5;
  int64 total = 6;
  double price = 7;
  repeated string tags = 8;
  repeated int32 numbers = 9;
  map<string, string> metadata = 10;

  string created_by = 11;

  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
  google.protobuf.Timestamp deleted_at = 14;
}

// -------------------------------------------------------------------
// Request / Response
// -------------------------------------------------------------------

// -------------------------------------------------------------------
// CreateCentrifugodf
// -------------------------------------------------------------------

message CreateCentrifugodfReq {
  CentrifugodfEntity data = 1;
}

message CreateCentrifugodfRes {
  bool success = 1;
  string message = 2;
  CentrifugodfEntity data = 3;
}

// -------------------------------------------------------------------
// GetCentrifugodf
// -------------------------------------------------------------------

message GetCentrifugodfReq {
  string id = 1;
}

message GetCentrifugodfRes {
  bool success = 1;
  string message = 2;
  CentrifugodfEntity data = 3;
}

// -------------------------------------------------------------------
// ListCentrifugodf
// -------------------------------------------------------------------

message ListCentrifugodfReq {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message ListCentrifugodfRes {
  bool success = 1;
  string message = 2;
  repeated CentrifugodfEntity data = 3;
  int64 total = 4;
}

// -------------------------------------------------------------------
// UpdateCentrifugodf
// -------------------------------------------------------------------

message UpdateCentrifugodfReq {
  string id = 1;
  CentrifugodfEntity data = 2;
}

message UpdateCentrifugodfRes {
  bool success = 1;
  string message = 2;
  CentrifugodfEntity data = 3;
}

// -------------------------------------------------------------------
// DeleteCentrifugodf
// -------------------------------------------------------------------

message DeleteCentrifugodfReq {
  string id = 1;
}

message DeleteCentrifugodfRes {
  bool success = 1;
  string message = 2;
}

// -------------------------------------------------------------------
// Service gRPC
// -------------------------------------------------------------------

service CentrifugodfService {

  rpc CreateCentrifugodf(CreateCentrifugodfReq) returns (CreateCentrifugodfRes) {
    option (google.api.http) = {
      post: "/api/v1/centrifugodf"
      body: "*"
    };
  }

  rpc GetCentrifugodf(GetCentrifugodfReq) returns (GetCentrifugodfRes) {
    option (google.api.http) = {
      get: "/api/v1/centrifugodf/{id}"
    };
  }

  rpc ListCentrifugodf(ListCentrifugodfReq) returns (ListCentrifugodfRes) {
    option (google.api.http) = {
      get: "/api/v1/centrifugodf"
    };
  }

  rpc UpdateCentrifugodf(UpdateCentrifugodfReq) returns (UpdateCentrifugodfRes) {
    option (google.api.http) = {
      put: "/api/v1/centrifugodf/{id}"
      body: "*"
    };
  }

  rpc DeleteCentrifugodf(DeleteCentrifugodfReq) returns (DeleteCentrifugodfRes) {
    option (google.api.http) = {
      delete: "/api/v1/centrifugodf/{id}"
    };
  }

}
