// Code generated by protoc-gen-go. DO NOT EDIT.
// source: centrifugodf/v1/centrifugodf.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CentrifugodfEntity struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Age                  int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Total                int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                 []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers              []int32                `protobuf:"varint,9,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CentrifugodfEntity) Reset()         { *m = CentrifugodfEntity{} }
func (m *CentrifugodfEntity) String() string { return proto.CompactTextString(m) }
func (*CentrifugodfEntity) ProtoMessage()    {}
func (*CentrifugodfEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{0}
}

func (m *CentrifugodfEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CentrifugodfEntity.Unmarshal(m, b)
}
func (m *CentrifugodfEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CentrifugodfEntity.Marshal(b, m, deterministic)
}
func (m *CentrifugodfEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CentrifugodfEntity.Merge(m, src)
}
func (m *CentrifugodfEntity) XXX_Size() int {
	return xxx_messageInfo_CentrifugodfEntity.Size(m)
}
func (m *CentrifugodfEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_CentrifugodfEntity.DiscardUnknown(m)
}

var xxx_messageInfo_CentrifugodfEntity proto.InternalMessageInfo

func (m *CentrifugodfEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CentrifugodfEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CentrifugodfEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CentrifugodfEntity) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CentrifugodfEntity) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CentrifugodfEntity) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CentrifugodfEntity) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CentrifugodfEntity) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CentrifugodfEntity) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *CentrifugodfEntity) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CentrifugodfEntity) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CentrifugodfEntity) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CentrifugodfEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CentrifugodfEntity) GetDeletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateCentrifugodfReq struct {
	Data                 *CentrifugodfEntity `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateCentrifugodfReq) Reset()         { *m = CreateCentrifugodfReq{} }
func (m *CreateCentrifugodfReq) String() string { return proto.CompactTextString(m) }
func (*CreateCentrifugodfReq) ProtoMessage()    {}
func (*CreateCentrifugodfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{1}
}

func (m *CreateCentrifugodfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCentrifugodfReq.Unmarshal(m, b)
}
func (m *CreateCentrifugodfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCentrifugodfReq.Marshal(b, m, deterministic)
}
func (m *CreateCentrifugodfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCentrifugodfReq.Merge(m, src)
}
func (m *CreateCentrifugodfReq) XXX_Size() int {
	return xxx_messageInfo_CreateCentrifugodfReq.Size(m)
}
func (m *CreateCentrifugodfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCentrifugodfReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCentrifugodfReq proto.InternalMessageInfo

func (m *CreateCentrifugodfReq) GetData() *CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateCentrifugodfRes struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugodfEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateCentrifugodfRes) Reset()         { *m = CreateCentrifugodfRes{} }
func (m *CreateCentrifugodfRes) String() string { return proto.CompactTextString(m) }
func (*CreateCentrifugodfRes) ProtoMessage()    {}
func (*CreateCentrifugodfRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{2}
}

func (m *CreateCentrifugodfRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCentrifugodfRes.Unmarshal(m, b)
}
func (m *CreateCentrifugodfRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCentrifugodfRes.Marshal(b, m, deterministic)
}
func (m *CreateCentrifugodfRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCentrifugodfRes.Merge(m, src)
}
func (m *CreateCentrifugodfRes) XXX_Size() int {
	return xxx_messageInfo_CreateCentrifugodfRes.Size(m)
}
func (m *CreateCentrifugodfRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCentrifugodfRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCentrifugodfRes proto.InternalMessageInfo

func (m *CreateCentrifugodfRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateCentrifugodfRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCentrifugodfRes) GetData() *CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCentrifugodfReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCentrifugodfReq) Reset()         { *m = GetCentrifugodfReq{} }
func (m *GetCentrifugodfReq) String() string { return proto.CompactTextString(m) }
func (*GetCentrifugodfReq) ProtoMessage()    {}
func (*GetCentrifugodfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{3}
}

func (m *GetCentrifugodfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentrifugodfReq.Unmarshal(m, b)
}
func (m *GetCentrifugodfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentrifugodfReq.Marshal(b, m, deterministic)
}
func (m *GetCentrifugodfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentrifugodfReq.Merge(m, src)
}
func (m *GetCentrifugodfReq) XXX_Size() int {
	return xxx_messageInfo_GetCentrifugodfReq.Size(m)
}
func (m *GetCentrifugodfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentrifugodfReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentrifugodfReq proto.InternalMessageInfo

func (m *GetCentrifugodfReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCentrifugodfRes struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugodfEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetCentrifugodfRes) Reset()         { *m = GetCentrifugodfRes{} }
func (m *GetCentrifugodfRes) String() string { return proto.CompactTextString(m) }
func (*GetCentrifugodfRes) ProtoMessage()    {}
func (*GetCentrifugodfRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{4}
}

func (m *GetCentrifugodfRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCentrifugodfRes.Unmarshal(m, b)
}
func (m *GetCentrifugodfRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCentrifugodfRes.Marshal(b, m, deterministic)
}
func (m *GetCentrifugodfRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCentrifugodfRes.Merge(m, src)
}
func (m *GetCentrifugodfRes) XXX_Size() int {
	return xxx_messageInfo_GetCentrifugodfRes.Size(m)
}
func (m *GetCentrifugodfRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCentrifugodfRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetCentrifugodfRes proto.InternalMessageInfo

func (m *GetCentrifugodfRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetCentrifugodfRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCentrifugodfRes) GetData() *CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListCentrifugodfReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCentrifugodfReq) Reset()         { *m = ListCentrifugodfReq{} }
func (m *ListCentrifugodfReq) String() string { return proto.CompactTextString(m) }
func (*ListCentrifugodfReq) ProtoMessage()    {}
func (*ListCentrifugodfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{5}
}

func (m *ListCentrifugodfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCentrifugodfReq.Unmarshal(m, b)
}
func (m *ListCentrifugodfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCentrifugodfReq.Marshal(b, m, deterministic)
}
func (m *ListCentrifugodfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCentrifugodfReq.Merge(m, src)
}
func (m *ListCentrifugodfReq) XXX_Size() int {
	return xxx_messageInfo_ListCentrifugodfReq.Size(m)
}
func (m *ListCentrifugodfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCentrifugodfReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListCentrifugodfReq proto.InternalMessageInfo

func (m *ListCentrifugodfReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCentrifugodfReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListCentrifugodfReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListCentrifugodfRes struct {
	Success              bool                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*CentrifugodfEntity `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListCentrifugodfRes) Reset()         { *m = ListCentrifugodfRes{} }
func (m *ListCentrifugodfRes) String() string { return proto.CompactTextString(m) }
func (*ListCentrifugodfRes) ProtoMessage()    {}
func (*ListCentrifugodfRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{6}
}

func (m *ListCentrifugodfRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCentrifugodfRes.Unmarshal(m, b)
}
func (m *ListCentrifugodfRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCentrifugodfRes.Marshal(b, m, deterministic)
}
func (m *ListCentrifugodfRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCentrifugodfRes.Merge(m, src)
}
func (m *ListCentrifugodfRes) XXX_Size() int {
	return xxx_messageInfo_ListCentrifugodfRes.Size(m)
}
func (m *ListCentrifugodfRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCentrifugodfRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListCentrifugodfRes proto.InternalMessageInfo

func (m *ListCentrifugodfRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListCentrifugodfRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListCentrifugodfRes) GetData() []*CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListCentrifugodfRes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpdateCentrifugodfReq struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *CentrifugodfEntity `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateCentrifugodfReq) Reset()         { *m = UpdateCentrifugodfReq{} }
func (m *UpdateCentrifugodfReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCentrifugodfReq) ProtoMessage()    {}
func (*UpdateCentrifugodfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{7}
}

func (m *UpdateCentrifugodfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCentrifugodfReq.Unmarshal(m, b)
}
func (m *UpdateCentrifugodfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCentrifugodfReq.Marshal(b, m, deterministic)
}
func (m *UpdateCentrifugodfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCentrifugodfReq.Merge(m, src)
}
func (m *UpdateCentrifugodfReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCentrifugodfReq.Size(m)
}
func (m *UpdateCentrifugodfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCentrifugodfReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCentrifugodfReq proto.InternalMessageInfo

func (m *UpdateCentrifugodfReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCentrifugodfReq) GetData() *CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateCentrifugodfRes struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *CentrifugodfEntity `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateCentrifugodfRes) Reset()         { *m = UpdateCentrifugodfRes{} }
func (m *UpdateCentrifugodfRes) String() string { return proto.CompactTextString(m) }
func (*UpdateCentrifugodfRes) ProtoMessage()    {}
func (*UpdateCentrifugodfRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{8}
}

func (m *UpdateCentrifugodfRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCentrifugodfRes.Unmarshal(m, b)
}
func (m *UpdateCentrifugodfRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCentrifugodfRes.Marshal(b, m, deterministic)
}
func (m *UpdateCentrifugodfRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCentrifugodfRes.Merge(m, src)
}
func (m *UpdateCentrifugodfRes) XXX_Size() int {
	return xxx_messageInfo_UpdateCentrifugodfRes.Size(m)
}
func (m *UpdateCentrifugodfRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCentrifugodfRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCentrifugodfRes proto.InternalMessageInfo

func (m *UpdateCentrifugodfRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateCentrifugodfRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateCentrifugodfRes) GetData() *CentrifugodfEntity {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteCentrifugodfReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCentrifugodfReq) Reset()         { *m = DeleteCentrifugodfReq{} }
func (m *DeleteCentrifugodfReq) String() string { return proto.CompactTextString(m) }
func (*DeleteCentrifugodfReq) ProtoMessage()    {}
func (*DeleteCentrifugodfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{9}
}

func (m *DeleteCentrifugodfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCentrifugodfReq.Unmarshal(m, b)
}
func (m *DeleteCentrifugodfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCentrifugodfReq.Marshal(b, m, deterministic)
}
func (m *DeleteCentrifugodfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCentrifugodfReq.Merge(m, src)
}
func (m *DeleteCentrifugodfReq) XXX_Size() int {
	return xxx_messageInfo_DeleteCentrifugodfReq.Size(m)
}
func (m *DeleteCentrifugodfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCentrifugodfReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCentrifugodfReq proto.InternalMessageInfo

func (m *DeleteCentrifugodfReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCentrifugodfRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCentrifugodfRes) Reset()         { *m = DeleteCentrifugodfRes{} }
func (m *DeleteCentrifugodfRes) String() string { return proto.CompactTextString(m) }
func (*DeleteCentrifugodfRes) ProtoMessage()    {}
func (*DeleteCentrifugodfRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e6c367a5f59854, []int{10}
}

func (m *DeleteCentrifugodfRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCentrifugodfRes.Unmarshal(m, b)
}
func (m *DeleteCentrifugodfRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCentrifugodfRes.Marshal(b, m, deterministic)
}
func (m *DeleteCentrifugodfRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCentrifugodfRes.Merge(m, src)
}
func (m *DeleteCentrifugodfRes) XXX_Size() int {
	return xxx_messageInfo_DeleteCentrifugodfRes.Size(m)
}
func (m *DeleteCentrifugodfRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCentrifugodfRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCentrifugodfRes proto.InternalMessageInfo

func (m *DeleteCentrifugodfRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteCentrifugodfRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CentrifugodfEntity)(nil), "centrifugodf.v1.CentrifugodfEntity")
	proto.RegisterMapType((map[string]string)(nil), "centrifugodf.v1.CentrifugodfEntity.MetadataEntry")
	proto.RegisterType((*CreateCentrifugodfReq)(nil), "centrifugodf.v1.CreateCentrifugodfReq")
	proto.RegisterType((*CreateCentrifugodfRes)(nil), "centrifugodf.v1.CreateCentrifugodfRes")
	proto.RegisterType((*GetCentrifugodfReq)(nil), "centrifugodf.v1.GetCentrifugodfReq")
	proto.RegisterType((*GetCentrifugodfRes)(nil), "centrifugodf.v1.GetCentrifugodfRes")
	proto.RegisterType((*ListCentrifugodfReq)(nil), "centrifugodf.v1.ListCentrifugodfReq")
	proto.RegisterType((*ListCentrifugodfRes)(nil), "centrifugodf.v1.ListCentrifugodfRes")
	proto.RegisterType((*UpdateCentrifugodfReq)(nil), "centrifugodf.v1.UpdateCentrifugodfReq")
	proto.RegisterType((*UpdateCentrifugodfRes)(nil), "centrifugodf.v1.UpdateCentrifugodfRes")
	proto.RegisterType((*DeleteCentrifugodfReq)(nil), "centrifugodf.v1.DeleteCentrifugodfReq")
	proto.RegisterType((*DeleteCentrifugodfRes)(nil), "centrifugodf.v1.DeleteCentrifugodfRes")
}

func init() {
	proto.RegisterFile("centrifugodf/v1/centrifugodf.proto", fileDescriptor_97e6c367a5f59854)
}

var fileDescriptor_97e6c367a5f59854 = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xd6, 0xc4, 0x49, 0x9b, 0x4e, 0xfe, 0x5e, 0x34, 0xbd, 0xc8, 0xf5, 0xdf, 0xff, 0xaf, 0x31,
	0x15, 0x58, 0x95, 0x6a, 0xab, 0x65, 0x01, 0x6d, 0x57, 0xe9, 0x45, 0x2c, 0xa0, 0x12, 0x72, 0x8b,
	0x90, 0xd8, 0xc0, 0xc4, 0x9e, 0xa6, 0x23, 0x62, 0x3b, 0x78, 0xc6, 0x91, 0x22, 0x2e, 0x12, 0x08,
	0x84, 0xc4, 0x96, 0x0d, 0xcf, 0xc1, 0x92, 0xd7, 0xe0, 0x15, 0x78, 0x10, 0x34, 0x63, 0x3b, 0x4d,
	0x6d, 0x57, 0x49, 0x8b, 0xd4, 0xdd, 0x9c, 0x33, 0xe7, 0xf2, 0x9d, 0xf3, 0x9d, 0x33, 0x36, 0x34,
	0x5c, 0x12, 0xf0, 0x88, 0x9e, 0xc6, 0xed, 0xd0, 0x3b, 0xb5, 0x7b, 0x9b, 0xf6, 0xb0, 0x6c, 0x75,
	0xa3, 0x90, 0x87, 0x68, 0xf6, 0x82, 0xae, 0xb7, 0xa9, 0xad, 0xb6, 0xc3, 0xb0, 0xdd, 0x21, 0xb6,
	0xbc, 0x6e, 0xc5, 0xa7, 0x36, 0xa7, 0x3e, 0x61, 0x1c, 0xfb, 0xdd, 0xc4, 0x43, 0x5b, 0x49, 0x0d,
	0x70, 0x97, 0xda, 0x38, 0x08, 0x42, 0x8e, 0x39, 0x0d, 0x03, 0x96, 0xdc, 0x1a, 0x3f, 0xab, 0x10,
	0xed, 0x0f, 0x85, 0x3c, 0x0c, 0x38, 0xe5, 0x7d, 0x34, 0x03, 0x2b, 0xd4, 0x53, 0x81, 0x0e, 0xcc,
	0x29, 0xa7, 0x42, 0x3d, 0x84, 0x60, 0x35, 0xc0, 0x3e, 0x51, 0x2b, 0x52, 0x23, 0xcf, 0x48, 0x87,
	0x0d, 0x8f, 0x30, 0x37, 0xa2, 0x5d, 0x11, 0x50, 0x55, 0xe4, 0xd5, 0xb0, 0x0a, 0x2d, 0xc1, 0x09,
	0xc6, 0x31, 0x8f, 0x99, 0x5a, 0xd5, 0x81, 0x59, 0x77, 0x52, 0x09, 0xcd, 0x41, 0x05, 0xb7, 0x89,
	0x5a, 0xd3, 0x81, 0x59, 0x73, 0xc4, 0x11, 0x2d, 0xc0, 0x1a, 0x0f, 0x39, 0xee, 0xa8, 0x13, 0x3a,
	0x30, 0x15, 0x27, 0x11, 0x84, 0xb6, 0x1b, 0x51, 0x97, 0xa8, 0x93, 0x3a, 0x30, 0x81, 0x93, 0x08,
	0x02, 0x0b, 0xc7, 0x6d, 0xa6, 0xd6, 0x75, 0x45, 0x60, 0x11, 0x67, 0xa4, 0xc2, 0xc9, 0x20, 0xf6,
	0x5b, 0x24, 0x62, 0xea, 0x94, 0xae, 0x98, 0x35, 0x27, 0x13, 0xd1, 0x11, 0xac, 0xfb, 0x84, 0x63,
	0x0f, 0x73, 0xac, 0x42, 0x5d, 0x31, 0x1b, 0x5b, 0x9b, 0x56, 0xae, 0x87, 0x56, 0xb1, 0x01, 0xd6,
	0x51, 0xea, 0x73, 0x18, 0xf0, 0xa8, 0xef, 0x0c, 0x42, 0xa0, 0xff, 0x20, 0x74, 0x23, 0x82, 0x39,
	0xf1, 0x5e, 0xb4, 0xfa, 0x6a, 0x43, 0xd6, 0x3c, 0x95, 0x6a, 0xf6, 0xfa, 0x68, 0xfb, 0xfc, 0x1a,
	0x73, 0xf5, 0x1f, 0x1d, 0x98, 0x8d, 0x2d, 0xcd, 0x4a, 0x18, 0xb0, 0x32, 0x8a, 0xac, 0x93, 0x8c,
	0xa2, 0x81, 0x6b, 0x93, 0x0b, 0xd7, 0xb8, 0xeb, 0x65, 0xae, 0xd3, 0xa3, 0x5d, 0x53, 0xeb, 0xc4,
	0xd5, 0x23, 0x1d, 0x92, 0xba, 0xce, 0x8c, 0x76, 0x4d, 0xad, 0x9b, 0x5c, 0xdb, 0x85, 0xd3, 0x17,
	0x4a, 0x15, 0xdc, 0xbc, 0x22, 0xfd, 0x94, 0x7a, 0x71, 0x14, 0x2c, 0xf4, 0x70, 0x27, 0xce, 0xc8,
	0x4f, 0x84, 0x9d, 0xca, 0x03, 0x60, 0x3c, 0x81, 0x8b, 0xfb, 0x12, 0xff, 0x70, 0x03, 0x1d, 0xf2,
	0x1a, 0xdd, 0x87, 0x55, 0xd9, 0x70, 0x20, 0xa1, 0xdc, 0x1e, 0xa3, 0xe1, 0x8e, 0x74, 0x30, 0x3e,
	0x81, 0xf2, 0x90, 0x92, 0x61, 0x16, 0xbb, 0x2e, 0x61, 0x4c, 0x46, 0xad, 0x3b, 0x99, 0x28, 0x6e,
	0x7c, 0xc2, 0x98, 0x98, 0xa8, 0x04, 0x61, 0x26, 0x0e, 0x60, 0x28, 0x57, 0x85, 0xb1, 0x06, 0xd1,
	0x43, 0xc2, 0xf3, 0x55, 0xe5, 0x96, 0xc2, 0xf8, 0x00, 0x4a, 0xcc, 0x6e, 0x18, 0xe9, 0x33, 0x38,
	0xff, 0x98, 0xb2, 0x02, 0x54, 0x04, 0xab, 0x5d, 0x91, 0x06, 0xc8, 0x15, 0x93, 0x67, 0xc1, 0x63,
	0x87, 0xfa, 0x94, 0xcb, 0xdc, 0x35, 0x27, 0x11, 0xe4, 0x8e, 0x12, 0x1c, 0xb9, 0x67, 0xe9, 0x02,
	0xa7, 0x92, 0xf1, 0x1d, 0x94, 0x45, 0xfe, 0xdb, 0xea, 0x94, 0x2b, 0x55, 0x77, 0xfe, 0x2c, 0x54,
	0x87, 0x9e, 0x05, 0xe3, 0x25, 0x5c, 0x7c, 0x2a, 0x67, 0x7f, 0x04, 0x41, 0x83, 0xbc, 0x95, 0xeb,
	0x8c, 0x61, 0x59, 0x8a, 0x1b, 0x26, 0xf7, 0x2e, 0x5c, 0x3c, 0x90, 0x9b, 0x3a, 0x6a, 0x12, 0x1f,
	0x95, 0x1b, 0x5e, 0x0b, 0xee, 0xd6, 0x8f, 0x1a, 0x9c, 0x1f, 0x8e, 0x73, 0x4c, 0xa2, 0x9e, 0x78,
	0x77, 0x3f, 0x03, 0x88, 0x8a, 0xbb, 0x89, 0xee, 0x14, 0xeb, 0x29, 0x7b, 0x13, 0xb4, 0xf1, 0xec,
	0x98, 0xb1, 0xfa, 0xf1, 0xd7, 0xef, 0x6f, 0x95, 0x65, 0x63, 0x41, 0x7e, 0xb1, 0x72, 0x5f, 0xc1,
	0x1d, 0xb0, 0x8e, 0xde, 0xc3, 0xd9, 0xdc, 0xd6, 0xa1, 0x62, 0x4f, 0x8b, 0xeb, 0xab, 0x8d, 0x61,
	0xc4, 0x8c, 0x5b, 0x32, 0xfb, 0xbf, 0x68, 0xb9, 0x2c, 0xbb, 0xfd, 0x86, 0x7a, 0xef, 0xd0, 0x5b,
	0x38, 0x97, 0x5f, 0x0c, 0xb4, 0x56, 0x88, 0x5d, 0xb2, 0x95, 0xda, 0x38, 0x56, 0xcc, 0x58, 0x91,
	0x10, 0x96, 0x50, 0x69, 0x03, 0xd0, 0x57, 0x00, 0x51, 0x71, 0x34, 0x4b, 0x58, 0x28, 0x5d, 0x11,
	0x6d, 0x3c, 0x3b, 0x66, 0xac, 0x49, 0x10, 0xff, 0x6b, 0x97, 0xf7, 0x41, 0x50, 0xf1, 0x05, 0x40,
	0x54, 0x1c, 0xbc, 0x12, 0x30, 0xa5, 0x63, 0xac, 0x8d, 0x67, 0x37, 0x20, 0x65, 0xfd, 0x72, 0x30,
	0x7b, 0xbb, 0xcf, 0xb7, 0xdb, 0x94, 0x9f, 0xc5, 0x2d, 0xcb, 0x0d, 0x7d, 0xfb, 0xf8, 0xa0, 0x79,
	0xd2, 0xdc, 0xd8, 0x0f, 0x3b, 0xa1, 0xdf, 0xa2, 0xd8, 0x66, 0x67, 0x38, 0x22, 0xde, 0x46, 0x3b,
	0xdc, 0x90, 0x1f, 0x43, 0x3b, 0xf7, 0x9f, 0xd5, 0x9a, 0x90, 0xea, 0x7b, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0xf5, 0x08, 0x9b, 0x81, 0x09, 0x00, 0x00,
}
